prodMetadata/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Press_Outlet__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Press Outlet</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

prodMetadata/src/objects/Press_Hit__c.object
<CustomObject>
    <fields>
        <fullName>Article_Teaser__c</fullName>
        <description>Teaser section that goes in the list of press hits (as opposed to the full text).</description>
        <inlineHelpText>Teaser section that goes in the list of press hits (as opposed to the full text).</inlineHelpText>
        <label>Article Teaser</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Article_Text__c</fullName>
        <label>Article Text</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Details_Show__c</fullName>
        <label>Details/Show</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Press_Outlet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Press Outlet</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Press Hits</relationshipLabel>
        <relationshipName>Press_Hits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publish_on_website__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show press hit on force.com press site</description>
        <inlineHelpText>Show press hit on force.com press site</inlineHelpText>
        <label>Publish on website</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Story_Date__c</fullName>
        <label>Story Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Alternative Therapy</fullName>
                </value>
                <value>
                    <fullName>Clay Hunt SAV Act</fullName>
                </value>
                <value>
                    <fullName>COV</fullName>
                </value>
                <value>
                    <fullName>Discrimination</fullName>
                </value>
                <value>
                    <fullName>DOD</fullName>
                </value>
                <value>
                    <fullName>Employment &amp; Financial Hardship</fullName>
                </value>
                <value>
                    <fullName>Gala</fullName>
                </value>
                <value>
                    <fullName>GI Bill</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Homelessness</fullName>
                </value>
                <value>
                    <fullName>Iraq</fullName>
                </value>
                <value>
                    <fullName>Iraqi Interpreters</fullName>
                </value>
                <value>
                    <fullName>Local Events</fullName>
                </value>
                <value>
                    <fullName>Love</fullName>
                </value>
                <value>
                    <fullName>Member Survey</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Military COLA</fullName>
                </value>
                <value>
                    <fullName>Military Recruitment</fullName>
                </value>
                <value>
                    <fullName>Military Sexual Trauma</fullName>
                </value>
                <value>
                    <fullName>NGIB</fullName>
                </value>
                <value>
                    <fullName>NYC Veterans</fullName>
                </value>
                <value>
                    <fullName>Online Campaigns</fullName>
                </value>
                <value>
                    <fullName>Op-Ed</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Overextended Military</fullName>
                </value>
                <value>
                    <fullName>Partnerships</fullName>
                </value>
                <value>
                    <fullName>Politics</fullName>
                </value>
                <value>
                    <fullName>PTSD</fullName>
                </value>
                <value>
                    <fullName>Rally</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Press Hit</label>
    <nameField>
        <displayFormat>PH-{00000}</displayFormat>
        <label>Press Hit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Press Hits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/press_hits_controller_extn.cls
public class press_hits_controller_extn {
 
    Press_Hit__c ph;

    public press_hits_controller_extn(ApexPages.StandardController controller) {
      ph = (Press_Hit__c) controller.getRecord();        
    }


    public List<Press_Hit__c> getPressHits() {
      return [select Press_Outlet__r.Name, Article_Title__c, Article_Teaser__c, Article_Text__c,
      				Story_Date__c, Link__c, Tier__c, Topic__c, Details_Show__c from Press_Hit__c 
      				where Publish_on_website__c=true order by Story_Date__c DESC];
    }



/*
   public press_hits_controller_extn(ApexPages.StandardSetController setController)
    {
        if ( setController == null )
        {
            setController = new ApexPages.StandardSetController(Database.getQueryLocator(
            	[select Press_Outlet__r.Name, Article_Title__c, Article_Teaser__c, Article_Text__c,
      				Story_Date__c, Link__c, Tier__c, Topic__c, Details_Show__c from Press_Hit__c 
      				where Publish_on_website__c = true order by Story_Date__c DESC]
            ));
        }
    }
*/

}