prodMetadata/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geo_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Geo Location</label>
        <referenceTo>Geo_Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Discharge_Status__c</fullName>
        <label>Discharge Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Honorable</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Other than Honorable</fullName>
                </value>
                <value>
                    <fullName>Bad Conduct</fullName>
                </value>
                <value>
                    <fullName>Dishonorable</fullName>
                </value>
                <value>
                    <fullName>Medical Retirement</fullName>
                </value>
                <value>
                    <fullName>Medical Discharge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_ID__c</fullName>
        <externalId>true</externalId>
        <label>Membership ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Paperwork_Confirmation_Type__c</fullName>
        <label>Paperwork Confirmation Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Paperwork_Confirmation__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Deployed OEF/OIF/OND</fullName>
                </value>
                <value>
                    <fullName>Deployed Elsewhere post 9/11</fullName>
                </value>
                <value>
                    <fullName>Not Deployed post 9/11</fullName>
                </value>
                <value>
                    <fullName>Pre-9/11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paperwork_Confirmation__c</fullName>
        <label>Paperwork Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paperwork Not Requested Yet</fullName>
                </value>
                <value>
                    <fullName>Paperwork Requested</fullName>
                </value>
                <value>
                    <fullName>Sent First Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Sent Second Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Standard Question/Issue</fullName>
                </value>
                <value>
                    <fullName>Paperwork Received</fullName>
                </value>
                <value>
                    <fullName>Paperwork Accepted</fullName>
                </value>
                <value>
                    <fullName>Paperwork Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Veteran_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates whether or not a contact is a Veteran Member, confirmed or unconfirmed.  Only membership should modify this field.</description>
        <label>Veteran Member</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Geo_Location__c.object
<CustomObject>
    <description>Holds a Geo cordinate, and information to build a balloon for this point</description>
    <fields>
        <fullName>lat__c</fullName>
        <label>lat</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lon__c</fullName>
        <label>lon</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <label>Geo Location</label>
    <nameField>
        <label>Geo Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Giveaways</fullName>
                </value>
                <value>
                    <fullName>Discounts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</description>
        <inlineHelpText>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</inlineHelpText>
        <label>City, ST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>E.g. “Watch the Orioles take on the Cardinals in a battle of the Birds. Seats are in the lower deck along the third base line.”</description>
        <inlineHelpText>E.g. “Watch the Orioles take on the Cardinals in a battle of the Birds. Seats are in the lower deck along the third base line.”</inlineHelpText>
        <label>Short Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Geo_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Geo Location object which stores Latitude, Longitude values</description>
        <label>Geo Location</label>
        <referenceTo>Geo_Location__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Description__c</fullName>
        <description>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</description>
        <inlineHelpText>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</inlineHelpText>
        <label>Location or Venue</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Maximum_Units_per_Member__c</fullName>
        <description>If greater than 1 and &quot;Member Cannot Select Quantity&quot; is unchecked, member can choose desired quantity of units up to this maximum,  If blank, quantity is unlimited.</description>
        <inlineHelpText>If greater than 1 and &quot;Member Cannot Select Quantity&quot; is unchecked, member can choose desired quantity of units up to this maximum,  If blank, quantity is unlimited.</inlineHelpText>
        <label>Maximum Units per Member</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>National_Give__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overides zip codes and states.</description>
        <inlineHelpText>Overrides zip codes and states.</inlineHelpText>
        <label>National Give</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <label>Num. Units</label>
        <summarizedField>Give_Instance__c.Number_of_Units__c</summarizedField>
        <summaryForeignKey>Give_Instance__c.Give__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed Visible</fullName>
                </value>
                <value>
                    <fullName>Closed Invisible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code_s__c</fullName>
        <inlineHelpText>Multiple Zip Codes should be Separate Gives</inlineHelpText>
        <label>Location by Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <description>Quantity of give items available.</description>
        <inlineHelpText>Quantity of give items available.</inlineHelpText>
        <label>Num. Units</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Request__c.object
<CustomObject>
    <description>Connects applicants to give</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Street Address</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Give_Instance__c</fullName>
        <label>Give Instance</label>
        <referenceTo>Give_Instance__c</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Give Request</label>
    <nameField>
        <displayFormat>GR-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Give Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Request_Guest__c.object
<CustomObject>
    <description>This object is used to capture information about the guests a member is bringing.</description>
    <fields>
        <fullName>Give_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Give Request</label>
        <referenceTo>Give_Request__c</referenceTo>
        <relationshipLabel>Give_Request_Guests</relationshipLabel>
        <relationshipName>Give_Request_Guests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Give Request Guest</label>
    <nameField>
        <label>Give Request Guest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Give_Request_Guests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partnerships</relationshipLabel>
        <relationshipName>Partnership_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_partner_logo_on_rewards_homepage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines whether logo shows up in logo block on Rewards site</description>
        <inlineHelpText>Determines whether logo shows up in logo block on Rewards site</inlineHelpText>
        <label>Partner logo in logo block</label>
        <type>Checkbox</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/test_Utilities.cls
public class test_Utilities {
    public static Give_Instance__c createSimpleGiveInstance() {
        return createSimpleGiveInstance(createSimpleGive());  
    }
    
    public static Give_Instance__c createSimpleGiveInstance(Give__c give) {
        Give_Instance__c instance = new Give_Instance__c();
        System.debug(System.LoggingLevel.INFO, give);
        instance.Give__c = give.Id;
        instance.Status__c = 'Open';
        instance.Number_of_Units__c = 100;
        insert instance;
        return instance;
    }

    public static Give__c createSimpleGive() {
        Partnership_Request__c PR = createPartnership();
        Geo_Location__c geo = createGeo('Test', 40, 120);
        Geo_Location__c closedgeo = createGeo('Test', 50, 120);
        
        Give__c give = new Give__c( Name = 'Test Simple Give', Geo_Location__c = geo.id, Partnership_Request__c = PR.id, 
        	Category__c = 'Events', City__c = 'Test City', National_Give__c = false, Zip_Code_s__c = '95050', 
        	Location_Description__c = 'Test',Status__c = 'Open', Maximum_Units_per_Member__c = 10,  
        	Description__c = 'Test');
        
        insert give;
        return give;
    }

    public static Give__c createSimpleGive(Partnership_Request__c PR) {
        Geo_Location__c geo = createGeo('Test', 40, 120);
        Geo_Location__c closedgeo = createGeo('Test', 50, 120);
        
        Give__c give = new Give__c( Name = 'Test Simple Give', Geo_Location__c = geo.id, Partnership_Request__c = PR.id, 
        	Category__c = 'Events', City__c = 'Test City', National_Give__c = false, Zip_Code_s__c = '95050', 
        	Location_Description__c = 'Test',Status__c = 'Open', Maximum_Units_per_Member__c = 10,  
        	Description__c = 'Test');
        
        insert give;
        return give;
    }
    
    public static Geo_Location__c createGeo(String name, Double lat, Double lon) {
        Geo_Location__c geo = new Geo_Location__c();
        geo.name = name;
        geo.lat__c = lat;
        geo.lon__c = lon;
        insert geo; 
        return geo;
    }
    
    public static Partnership_Request__c createPartnership(){
        Account a = new Account(name='testtesttesttest');
        insert a;
        
        Partnership_Request__c PR = new Partnership_Request__c(name='testtest',organization__c=a.id,public_partner_name__c='testtesttest', Show_partner_logo_on_rewards_homepage__c=true);
                
        insert PR;
        
        return PR; 
    }
    
    public static Contact createSimpleContact(String lastName, String email, string memId) {
		Contact con = new Contact();
        con.lastname = lastName;
        con.email = email;
        con.Membership_Id__c = memId;
        con.Veteran_Member__c = true;
        con.Paperwork_Confirmation__c = 'Paperwork Accepted';
        con.Paperwork_Confirmation_Type__c = 'Deployed OEF/OIF/OND';
        con.Discharge_Status__c =  'General';
 		con.Mailingstreet = 'test';
        insert con;
        return con;
    }
    
    public static Give_Request__c createSimpleGiveRequest(Give__c give, Give_Instance__c instance, Contact con) {
    	Give_Request__c request = new Give_Request__c();
    	
    	request.Address__c = '1000 Grand Ave';
    	request.Applicant__c = con.Id;
    	request.City__c = 'New York';
    	request.Confirmed_21__c = true;
    	request.Email_Address__c = con.Email;
    	request.Give_Instance__c = instance.Id;
    	request.Guest_s_21_and_Over__c = true;
    	request.Member_DL_Num__c = 'asdf';
    	request.Member_DOB__c = Date.Today().addYears(-18);
    	request.Member_Shirt_Size__c = 'Adult – Large (L)';
    	request.Primary_Phone__c = '111-222-3333';
    	request.Stage__c = 'Tentative confirmation';
    	request.Units_Requested__c = 2;
    	request.State__c = 'NY';
    	request.Zip_Code__c = '95050';
    	insert request;
    	
    	createSimpleGuest(request, con);
    	
    	return request;
    }
    
    public static Give_Request_Guest__c createSimpleGuest(Give_Request__c request, Contact con) {
    	Give_Request_Guest__c guest = new Give_Request_Guest__c();
    	guest.Applicant__c = con.Id;
    	guest.Birthdate__c = Date.Today().addYears(-50);
    	guest.Drivers_License__c = 'sadsadfsdaf';
    	guest.First_Name__c = 'First';
    	guest.Last_Name__c = 'Last';
    	guest.Give_Request__c = request.Id;
    	guest.Shirt_Size__c = 'Adult - Large (L)';
    	
    	insert guest;
    	
    	return guest;
    }
}