prodMetadata/src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>AIR_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AIR Completed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/AIR__c.object
<CustomObject>
    <description>After Impact Review</description>
    <fields>
        <fullName>Activity_ID__c</fullName>
        <description>Can&apos;t have lookup to Activities so using a text field instead to store the ID.</description>
        <label>Activity ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Event_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Give__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipName>Event_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AIR</label>
    <nameField>
        <label>AIR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AIRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/AIR_Completed_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used by AIRCountComplete trigger which checks/unchecks the AIR Completed box on the related record if the Completed box is checked/unchecked on the AIR.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines whether or not this field is checked in the trigger that checks the Completed box on the related record.</description>
        <inlineHelpText>Determines whether or not this field is checked in the trigger that checks the Completed box on the related record.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <description>Name of field on AIR record containing a related record ID</description>
        <inlineHelpText>Name of field on AIR record containing a related record ID</inlineHelpText>
        <label>Field API Name on AIR containing an ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AIR Completed Settings</label>
</CustomObject>

prodMetadata/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>AIR_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AIR Completed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>AIR_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AIR Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to indicate that Campaign Members are to receive notifications.</description>
        <inlineHelpText>This field will be used to indicate that Campaign Members are to receive notifications.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zip_Code_s__c</fullName>
        <inlineHelpText>Multiple Zip Codes should be Separate Gives</inlineHelpText>
        <label>Location by Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/AIRCompleteCheckerTests.cls
/*
 *
 * Tests for AIRCountComplete trigger and AIRCompleteChecker class.
 *
 * SD 2012
 */
 
 @isTest
private class AIRCompleteCheckerTests {

  ////////// Tests //////////
  
  static testMethod void testAIRCompleteChecker() {

    Campaign c = new Campaign(Name = 'Unit Test Campaign');
    insert c;

    Campaign c2 = new Campaign(Name = 'Unit Test Campaign 2');
    insert c2;
    
    Partnership_Request__c p = new Partnership_Request__c(Name = 'Unit Test Partnership', Public_Partner_Name__c = 'Unit Test Partner Name');
    insert p;

    Give__c g = new Give__c(Name = 'Unit Test Give', Zip_Code_s__c = '10012', Partnership_Request__c = p.id);
    insert g;
    
    AIR_Completed_Settings__c s_g = new AIR_Completed_Settings__c(Name='Give', Active__c=true, Field_API_Name__c='Give__c');
    insert s_g;
    AIR_Completed_Settings__c s_c = new AIR_Completed_Settings__c(Name='Campaign', Active__c=true, Field_API_Name__c='Campaign__c');
    insert s_c;
    AIR_Completed_Settings__c s_a = new AIR_Completed_Settings__c(Name='Activity', Active__c=true, Field_API_Name__c='Activity_ID__c');
    insert s_a;
    
    AIR__c air1 = new AIR__c (Name = 'Unit Test AIR 1', Completed__c = false, Give__c = g.id);
    insert air1;
    System.assertEquals(false, [select AIR_Completed__c from Give__c where id = :g.id].AIR_Completed__c);
    
    AIR__c air2 = new AIR__c (Name = 'Unit Test AIR 2', Completed__c = true, Give__c = g.id);
    insert air2;
    System.assertEquals(true, [select AIR_Completed__c from Give__c where id = :g.id].AIR_Completed__c);

    System.assertEquals(false, [select AIR_Completed__c from Campaign where id = :c.id].AIR_Completed__c);
    air2.Campaign__c = c.id;
    update air2;
    System.assertEquals(true, [select AIR_Completed__c from Campaign where id = :c.id].AIR_Completed__c);

    System.assertEquals(false, [select AIR_Completed__c from Campaign where id = :c2.id].AIR_Completed__c);
    air1.Campaign__c = c2.id;
    update air1;
    System.assertEquals(false, [select AIR_Completed__c from Campaign where id = :c2.id].AIR_Completed__c);

    air1.Completed__c = true;
    update air1;
    System.assertEquals(true, [select AIR_Completed__c from Campaign where id = :c2.id].AIR_Completed__c);

    air1.Campaign__c = c.id;
    update air1;
    System.assertEquals(false, [select AIR_Completed__c from Campaign where id = :c2.id].AIR_Completed__c);

    air1.Give__c = NULL;
    update air1;
    System.assertEquals(true, [select AIR_Completed__c from Give__c where id = :g.id].AIR_Completed__c);

    air2.Give__c = NULL;
    update air2;
    System.assertEquals(false, [select AIR_Completed__c from Give__c where id = :g.id].AIR_Completed__c);


    delete air1;
    System.assertEquals(true, [select AIR_Completed__c from Campaign where id = :c.id].AIR_Completed__c);

    delete air2;
    System.assertEquals(false, [select AIR_Completed__c from Campaign where id = :c.id].AIR_Completed__c);
 
 	// Now test the Activity_ID__c field which is a Text instead of a Lookup
 
    Task t = new Task(OwnerId = UserInfo.getUserId());
    insert t;

    AIR__c air3 = new AIR__c (Name = 'Unit Test AIR 3', Completed__c = true, Activity_ID__c = (String)t.Id);
    insert air3;
    System.assertEquals(true, [select AIR_Completed__c from Task where id = :t.id].AIR_Completed__c);   

	air3.Completed__c = false;
	update air3;
    System.assertEquals(false, [select AIR_Completed__c from Task where id = :t.id].AIR_Completed__c);   

	air3.Activity_ID__c = 'test non-ID string';	
	try {
            update air3;
        } catch (DmlException e) {
            //Assert Error Message 
            System.assert( e.getMessage().contains('The value in Activity_ID__c' + 
            	' does not appear to be a valid ID.'), 
                e.getMessage() );
        } //catch 	

    AIR__c air4 = new AIR__c (Name = 'Unit Test AIR 4', Completed__c = true, Activity_ID__c = (String)t.Id);
    insert air4;
    System.assertEquals(true, [select AIR_Completed__c from Task where id = :t.id].AIR_Completed__c);   

	delete air4;
    System.assertEquals(false, [select AIR_Completed__c from Task where id = :t.id].AIR_Completed__c);   

  }
  
}