prodMetadata/src/objects/AIR__c.object
<CustomObject>
    <description>After Impact Review</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Event_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>IAVAEvent__c</referenceTo>
        <relationshipLabel>AIRs</relationshipLabel>
        <relationshipName>AIRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Give__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipName>Event_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AIR</label>
    <nameField>
        <label>AIR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AIRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>AIR_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AIR Required</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

prodMetadata/src/objects/Event__c.object
<CustomObject>
    <description>This object is reserved for DC event and congressional testimony tracking</description>
    <label>DC Popularity Index</label>
    <nameField>
        <displayFormat>E-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DC Popularity Index</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>AIR_Required__c</fullName>
        <defaultValue>true</defaultValue>
        <label>AIR Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to indicate that Campaign Members are to receive notifications.</description>
        <inlineHelpText>This field will be used to indicate that Campaign Members are to receive notifications.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>National_Give__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overides zip codes and states.</description>
        <inlineHelpText>Overrides zip codes and states.</inlineHelpText>
        <label>National Give</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>National__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to indicate that the notification will be sent nation-wide to all Contacts.</description>
        <inlineHelpText>This field will be used to indicate that the notification will be sent nation-wide to all Contacts.</inlineHelpText>
        <label>National</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/IAVAEvent__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/testAIRCountComplete.cls
@isTest(seeAllData = true)
public class testAIRCountComplete
{
    private static testMethod void insertCampaignAIR()
    {
        Campaign c = new Campaign(Name = 'airRequiredCampaign', isActive = true, AIR_Required__c = true);
        insert c;
        
        AIR__c a = new AIR__c(Name = 'airRequiredCampaign AIR', Campaign__c = c.Id, Completed__c = true);
        insert a;
    }

    private static testMethod void insertEventAIR()
    {
        IAVAEvent__c ie = new IAVAEvent__c(Name = 'airRequiredEvent');
        insert ie;
        
        AIR__c a = new AIR__c(Name = 'airRequiredCampaign AIR', Event__c = ie.Id, Completed__c = true);
        try
        {
            insert a;
        }
        catch (Exception e)
        {
            System.debug('ERROR:' + e);
        }
    }
    
    private static testMethod void deleteCampaignAIR()
    {
        Campaign c = new Campaign(Name = 'airRequiredCampaign', isActive = true, AIR_Required__c = true);
        insert c;
        
        AIR__c a = new AIR__c(Name = 'airRequiredCampaign AIR', Campaign__c = c.Id, Completed__c = true);
        insert a;
        
        test.startTest();
        delete a;
        test.stopTest();
    }
    
    private static testMethod void completeCampaignAIR()
    {
        Campaign c = new Campaign(Name = 'airRequiredCampaign', isActive = true, AIR_Required__c = true);
        insert c;
        
        AIR__c a = new AIR__c(Name = 'airRequiredCampaign AIR', Campaign__c = c.Id);
        insert a;
        
        a.Completed__c = true;
        test.startTest();
        update a;
        test.stopTest();
    }
    
    private static testMethod void changeAIRParent()
    {
        Campaign c = new Campaign(Name = 'airRequiredCampaign', isActive = true, AIR_Required__c = true);
        insert c;
        
        AIR__c a = new AIR__c(Name = 'airRequiredCampaign AIR', Campaign__c = c.Id, Completed__c = true);
        insert a;
        
        Partnership_Request__c p = new Partnership_Request__c(Name = 'partnershipForGive', Public_Partner_Name__c = 'partner');
        insert p;
        
        Give__c g = new Give__c(Name = 'airRequiredGive', AIR_Required__c = true, Partnership_Request__c = p.Id, National__c = true, National_Give__c = true);
        insert g;
        
        a.Campaign__c = null;
        a.Give__c = g.Id;
        test.startTest();
        update a;
        test.stopTest();
    }
}