prodMetadata/src/objects/AIR__c.object
<CustomObject>
    <description>After Impact Review</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Event_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AIR</label>
    <nameField>
        <label>AIR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AIRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Volunteer - Leader/Host</fullName>
                </value>
                <value>
                    <fullName>Volunteer - General</fullName>
                </value>
                <value>
                    <fullName>Recruited At</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>KW_Chief_of_Staff__c</fullName>
        <description>If the KnowWho Title contains Chief of Staff but not Assistant to the Chief of Staff or Deputy Chief of Staff, this field will be &quot;True&quot;</description>
        <formula>IF(
AND(CONTAINS(kw__Title__c,&quot;Chief of Staff&quot;),
(NOT(CONTAINS(kw__Title__c,&quot;Assistant Chief of Staff&quot;))), 
(NOT(CONTAINS(kw__Title__c,&quot;Assistant to the Chief of Staff&quot;))),
(NOT(CONTAINS(kw__Title__c,&quot;Deputy Chief of Staff&quot;)))),
&quot;True&quot;,&quot;&quot;)</formula>
        <inlineHelpText>If the KnowWho Title contains Chief of Staff but not Assistant to the Chief of Staff or Deputy Chief of Staff, this field will be &quot;True&quot;</inlineHelpText>
        <label>KW Chief of Staff</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KW_Comms_Director__c</fullName>
        <description>KnowWho Records with the KnowWho Title containing Communications Director but not Deputy Communications Director</description>
        <formula>IF(
AND(CONTAINS(kw__Title__c,&quot;Communications Director&quot;),
(NOT(CONTAINS(kw__Title__c,&quot;Assistant Communications Director&quot;))),
(NOT(CONTAINS(kw__Title__c,&quot;Deputy Communications Director&quot;)))),
&quot;True&quot;,&quot;&quot;)</formula>
        <inlineHelpText>KnowWho Records with the KnowWho Title containing Communications Director but not Deputy Communications Director</inlineHelpText>
        <label>KW Comms Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KW_IsTheMember__c</fullName>
        <description>True if the contact record is the primary Member of Congress for the Member&apos;s office.</description>
        <formula>if(  ispickval(kw__KW_Category__c, &quot;Fed Legislator&quot;)   , &quot;True&quot;, &quot;&quot;)</formula>
        <inlineHelpText>True if the contact record is the primary Member of Congress for the Member&apos;s office.</inlineHelpText>
        <label>KW IsTheMember</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KW_Leg_Assistant__c</fullName>
        <description>If KW Title contains Legislative Assistant, this will be True.</description>
        <formula>IF(CONTAINS( kw__Title__c , &quot;Legislative Assistant&quot;), &quot;True&quot;,&quot;&quot;)</formula>
        <inlineHelpText>If KW Title contains Legislative Assistant, this will be True.</inlineHelpText>
        <label>KW Leg Assistant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KW_Leg_Director__c</fullName>
        <description>Contains Legislative Director but not Deputy Legislative or anything &quot;to the Legislative Director&quot;</description>
        <formula>IF(
AND(
CONTAINS(kw__Title__c , &quot;Legislative Director&quot;),
NOT(CONTAINS(kw__Title__c , &quot;to the Legislative Director&quot;)),
NOT(CONTAINS(kw__Title__c , &quot;Assistant Legislative Director&quot;)), 
NOT(CONTAINS(kw__Title__c , &quot;Deputy Legislative Director&quot;)))
,&quot;True&quot;,&quot;&quot;)</formula>
        <inlineHelpText>Contains Legislative Director but not Deputy Legislative or anything &quot;to the Legislative Director&quot;</inlineHelpText>
        <label>KW Leg Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KW_Scheduler__c</fullName>
        <description>KW Title contains Scheduler but not assistant or deputy Scheduler</description>
        <formula>IF(
AND(CONTAINS(kw__Title__c,&quot;Scheduler&quot;),
(NOT(CONTAINS(kw__Title__c,&quot;Assistant Scheduler&quot;))),
(NOT(CONTAINS(kw__Title__c,&quot;Deputy Scheduler&quot;)))),
&quot;True&quot;,&quot;&quot;)</formula>
        <inlineHelpText>KW Title contains Scheduler but not assistant or deputy Scheduler</inlineHelpText>
        <label>KW Scheduler</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Contact_Leg_junction__c.object
<CustomObject>
    <description>Relates Contacts to Legislation object with many to many relationship</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>KW - Member Record, KW - Staffer Record</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Legislation related to this Contact</relationshipLabel>
        <relationshipName>Contact_Leg_junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Legislation__c</fullName>
        <label>Legislation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Legislation__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Legislation__c</referenceTo>
        <relationshipLabel>Contacts related to this Legislation</relationshipLabel>
        <relationshipName>Contact_Leg</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Co-sponsor</fullName>
                </value>
                <value>
                    <fullName>Key Ally</fullName>
                </value>
                <value>
                    <fullName>Leaning Oppose</fullName>
                </value>
                <value>
                    <fullName>Lean Support</fullName>
                </value>
                <value>
                    <fullName>On Fence</fullName>
                </value>
                <value>
                    <fullName>Oppose</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Target</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Related to Legislation</label>
    <nameField>
        <displayFormat>ContLeg-{0000}</displayFormat>
        <label>Contact-Leg ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Related to Legislation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Legislation__c.object
<CustomObject>
    <label>Legislation</label>
    <nameField>
        <label>Bill ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legislation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/LegTargetingController.cls
/*

TO DO:

- use something more universal than AIR__c for the Campaign lookup
- separate page 2 forms into two separate forms so the enter key works
- separate contacts list into separate component (requires some controller stuff i dont quite get)

*/



public with sharing class LegTargetingController {

	private final Legislation__c leg;

    public SelectOption[] allPositions { get; set; }
    public SelectOption[] selectedPositions { get; set; }
    public SelectOption[] allRoles { get; set; }
    public SelectOption[] selectedRoles { get; set; }

    public String positions { get; set; }
    public String roles { get; set; }
    //public String qresult1 { get; set; }
    //public String qresult2 { get; set; }
    public String confMsg { get; set; }
    
    public Campaign theCampaign { get; set; }
    
    public Integer numContactsTargeted { get; set; }
    public Integer numContactsAdded { get; set; }
    public Integer numContactsAlreadyThere { get; set; }

    public String newCampaignName { get; set; }
    public AIR__c idHolder { get; set; }

    
    //public List<Contact_Leg_junction__c> cl { get; set; }
    //public List<Contact> ctcs1 { get; set; }
    //public List<Account> accts { get; set; }
    public List<Contact> ctcs2 { get; set; }

    public LegTargetingController(ApexPages.StandardController stdController) {
		// System.debug('in LegTargetingController()');

		 this.leg = (Legislation__c)stdController.getRecord();
		 
		 
		 idHolder = new AIR__c();
		 
		 //ctcs1 = new List<Contact>();
		 //accts = new List<Account>();
		 ctcs2 = new List<Contact>();

         selectedPositions = new List<SelectOption>();
         allPositions = new List<SelectOption>();

         Schema.DescribeFieldResult positionResult = Contact_Leg_junction__c.Role__c.getDescribe();
         List<Schema.PicklistEntry> ple = positionResult.getPicklistValues();
         for( Schema.PicklistEntry f : ple) {
             allPositions.add(new SelectOption(f.getLabel(), f.getValue()));
         }
		// System.debug('allPositions: ' + allPositions);  
       
         selectedRoles = new List<SelectOption>();
         allRoles = new List<SelectOption>();

         allRoles.add(new SelectOption('KW_IsTheMember__c','The Member'));
         allRoles.add(new SelectOption('KW_Chief_of_Staff__c','Chief of Staff'));
         allRoles.add(new SelectOption('KW_Comms_Director__c','Communications Director'));
         allRoles.add(new SelectOption('KW_Leg_Assistant__c','Legislative Assistant'));
         allRoles.add(new SelectOption('KW_Leg_Director__c','Legislative Director'));
         allRoles.add(new SelectOption('KW_Scheduler__c','Scheduler'));

		 // System.debug('allRoles: ' + allRoles);  

}

	public Legislation__c getTheLeg()
	{
	   return [select Name from Legislation__c limit 1];
	}
	
	public PageReference step1() {
		return Page.LegTarget;
	}
	public PageReference step2() {
		return Page.LegTarget2;
	}
	public PageReference step3() {
		return Page.LegTarget3;
	}

	public PageReference doIt() {
		if (selectedPositions.size() == 0) {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'You have to select at least one Position on the bill to target.'));
			return null;
		} else {
			getContacts();
			return step2();
		}
	}
	
    public void getContacts() {
		System.debug('in getContacts()');
    	
        positions = '';
        Boolean first = true;
        for ( SelectOption sp : selectedPositions ) {
            if (!first) {
                positions += ', ';
            }
            positions += sp.getLabel();
            first = false;
        }
        
        roles = '';
        Boolean firstrole1 = true;
        for ( SelectOption sr : selectedRoles ) {
            if (!firstrole1) {
                roles += ', ';
            }
            roles += sr.getLabel();
            firstrole1 = false;
        }
        
		System.debug('positions: ' + positions);   
		
		String q1 = 'SELECT Contact__c from Contact_Leg_junction__c where Legislation__c = \'' + leg.Id + '\'';
		q1 += ' and Role__c in (';
        Boolean firstposition = true;
        for ( SelectOption sp : selectedPositions ) {
            if (!firstposition) {
                q1 += ', ';
            }
            q1 += '\'' + sp.getLabel() + '\'';
            firstposition = false;
        }
        q1 += ')';

		System.debug ('q1: ' + q1);

		/*
		List<Contact_Leg_junction__c> cl = new List<Contact_Leg_junction__c>();
		cl = Database.query(q1);
		*/
		
		String q2= 'SELECT AccountId from Contact where id in (' + q1 + ')';
		System.debug ('q2: ' + q2);
		List<Contact> ctcs1 = Database.query(q2);

		list<id> AccountIDs = new list<id>();
		map<id, Account> AccountMap = new map<id, Account>();

		for (Contact ctc1 : ctcs1) {
			AccountIDs.add(ctc1.AccountId);			
		}

		String q4= 'SELECT Id, Name, AccountId, Account.Name, ' +
		+ 'KW_IsTheMember__c, KW_Chief_of_Staff__c, KW_Comms_Director__c, KW_Scheduler__c, KW_Leg_Assistant__c, KW_Leg_Director__c ' 
		+ 'from Contact where AccountId in :AccountIDs';
		
        Boolean firstrole = true;
        for ( SelectOption sr : selectedRoles ) {
            if (firstrole) {
            	q4 += ' and (';
            }
            else {
                q4 += ' or ';
            }
	        q4 += sr.getValue() + '=\'True\'';
            firstrole = false;
        }		
        if (selectedRoles.size() > 0) q4 += ')';
		
		System.debug ('q4: ' + q4);
		ctcs2 = Database.query(q4);
		numContactsTargeted = ctcs2.size();
		
		
		     
		System.debug('about to return from getContacts()');        
        //return null;       
    }
	
	
	public PageReference addToNew(){
		
		if (newCampaignName == null || newCampaignName == '') {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please enter a name for the new campaign to be created.'));
			return null;			
		} else {
			theCampaign = new Campaign(Name=newCampaignName, IsActive=true);	
			try {
				insert theCampaign;
			} catch (Exception e) {
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, e.getMessage()));
				return null;			
			}
			System.debug('theCampaign: ' + theCampaign);
			System.debug('theCampaign.Id: ' + theCampaign.Id);
			List<CampaignMember> CampaignMembersToInsert = new List<CampaignMember>();
			for (Contact theContact : ctcs2) {
				CampaignMembersToInsert.add(new CampaignMember(ContactId=theContact.Id, CampaignId=theCampaign.Id));
			}
			try {
				insert CampaignMembersToInsert;
			} catch (Exception e) {
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, e.getMessage()));
				return null;
			}
			numContactsAdded = CampaignMembersToInsert.size();		
			confMsg = 'Done.  Hot Damn.';
			return step3();
		}
		
	}

    public PageReference addToExisting(){
    	
 		if (idHolder.Campaign__c == null ) {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please select an existing campaign to which to add the contacts.'));
			return null;			
		} else {
			theCampaign = [select Id, Name from Campaign where id = :idHolder.Campaign__c];	
			System.debug('theCampaign.Id: ' + theCampaign.Id);
			List<CampaignMember> existingCMs = [select ContactId from CampaignMember where CampaignId = :theCampaign.Id];
			Set<Id> existingCMIds = new Set<Id>();
			for (CampaignMember cmem : existingCMs) {
				existingCMIds.add(cmem.ContactId);
			}
			System.debug('existingCMIds: ' + existingCMIds);
			List<CampaignMember> CampaignMembersToInsert = new List<CampaignMember>();
			numContactsAlreadyThere = 0;
			for (Contact theContact : ctcs2) {
				System.debug('theContact.Id: ' + theContact.Id);
				System.debug('existingCMIds.contains(theContact.Id): ' + existingCMIds.contains(theContact.Id));
				if (existingCMIds.contains(theContact.Id)) {
					numContactsAlreadyThere += 1;
				} else {
					CampaignMembersToInsert.add(new CampaignMember(ContactId=theContact.Id, CampaignId=theCampaign.Id));
				}
			}
			try {
				insert CampaignMembersToInsert;
			} catch (Exception e) {
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, e.getMessage()));
				return null;
			}			
			numContactsAdded = CampaignMembersToInsert.size();		
			confMsg = 'Done.  Hot Damn.';
			return step3();
		}
    }
    

}