prodMetadata/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Event_Public_Details__c</fullName>
        <description>Public event details for display on COV and external sites</description>
        <inlineHelpText>Public event details for display on COV and external sites. For images use the &quot;Web Address&quot; tab rather than uploading an image here directly (the latter will not work).  If you need a place to host the image you can use the Amazon S3 server.</inlineHelpText>
        <label>Public Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Show_Inside_COV_To__c</fullName>
        <description>&quot;Everyone&quot; means show the announcement to everyone. After the user dismisses the announcement they are added to the campaign.  &quot;Campaign Members&quot; means only show to those people, and when they dismiss change the campaign status accordingly.</description>
        <inlineHelpText>&quot;Everyone&quot; means show the announcement to everyone. After the user dismisses the announcement they are added to the campaign.  &quot;Campaign Members&quot; means only show to those people, and when they dismiss change the campaign status accordingly.</inlineHelpText>
        <label>Show Inside COV To</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Everyone</fullName>
                </value>
                <value>
                    <fullName>Campaign Members</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

prodMetadata/src/objects/Campaign_Image__c.object
<CustomObject>
    <description>Child object to attach images, in order to circumvent limited campaign permissions</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Images</relationshipLabel>
        <relationshipName>Campaign_Images</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Thumbnail</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Campaign Image</label>
    <nameField>
        <displayFormat>CmpImg-{00000}</displayFormat>
        <label>Campaign image Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/cov_announcements_TESTS.cls
@isTest
private class cov_announcements_TESTS {
	
static testMethod void cov_announcements_Test() {
        
		Campaign c1 = new Campaign(name='Test Campaign 1', Type='COV Announcement', IsActive=TRUE);
		c1.Event_Public_Details__c ='These are the public details';
		c1.Show_Inside_COV_To__c = 'Everyone';
		insert c1;

		Campaign c2 = new Campaign(name='Test Campaign 2', Type='COV Announcement', IsActive=TRUE);
		c2.Event_Public_Details__c ='These are the public details';
		c2.Show_Inside_COV_To__c = 'Campaign Members';
		insert c2;
		
       	Campaign_Image__c ci = new Campaign_Image__c();
       	ci.Campaign__c = c1.Id;
       	ci.Size__c = 'Thumbnail';
       	insert ci;


       	cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u = testusers.getPortalUser();
        
        System.runAs(u) {

        	cov_user_utility.self.refreshSelf();
	        
    		PageReference pageRef = Page.cov_announcements_dash;
	        Test.setCurrentPage(pageRef);
	        
	        cov_announcements_controller controller = new cov_announcements_controller();

	        System.assertEquals(1, controller.announcementsList.size());

	        // Test that dismissing the announcement adds the contact to the campaign with Status Dismissed
	        System.assertEquals(0, [select Status from CampaignMember where CampaignId = :c1.Id and ContactId = :u.ContactId limit 1].size());
	        controller.cmpIdChosen = c1.Id;
	        controller.dismiss();
	        CampaignMember cm = [select Status from CampaignMember where CampaignId = :c1.Id and ContactId = :u.ContactId limit 1];
	        System.assertEquals('Dismissed', cm.Status);

	        // Test that dismissing the announcement changes the campaignmember Status to Dismissed
	        cm.Status = 'Sent';
	        update cm;
	        cm = [select Status from CampaignMember where CampaignId = :c1.Id and ContactId = :u.ContactId limit 1];
	        System.assertEquals('Sent', cm.Status);
	        controller.dismiss();
	        cm = [select Status from CampaignMember where CampaignId = :c1.Id and ContactId = :u.ContactId limit 1];
	        System.assertEquals('Dismissed', cm.Status);


	        // Test that a 'CampaignMembers only' campaign is returned if the member is added to the campaign
	        controller = new cov_announcements_controller();
	        System.assertEquals(0, controller.announcementsList.size());
	        CampaignMember cm2 = new CampaignMember(CampaignId = c2.id, ContactId = u.ContactId);
	        insert cm2;
	        controller = new cov_announcements_controller();
	        System.assertEquals(1, controller.announcementsList.size());

	        cm = [select Status from CampaignMember where CampaignId = :c2.Id and ContactId = :u.ContactId limit 1];
	        System.assertNotEquals('Dismissed', cm.Status);
	      	controller.cmpIdChosen = c2.Id;
	        controller.dismiss();
	        cm = [select Status from CampaignMember where CampaignId = :c2.Id and ContactId = :u.ContactId limit 1];
	        System.assertEquals('Dismissed', cm.Status);


        }        


    }


	static testMethod void cov_announcements_internalUser_Test() {
        
		Campaign c1 = new Campaign(name='Test Campaign 1', Type='COV Announcement', IsActive=TRUE);
		c1.Event_Public_Details__c ='These are the public details';
		c1.Show_Inside_COV_To__c = 'Everyone';
		insert c1;

		Campaign c2 = new Campaign(name='Test Campaign 2', Type='COV Announcement', IsActive=FALSE);
		c2.Event_Public_Details__c ='These are the public details';
		c2.Show_Inside_COV_To__c = 'Campaign Members';
		insert c2;
		
       	Campaign_Image__c ci = new Campaign_Image__c();
       	ci.Campaign__c = c1.Id;
       	ci.Size__c = 'Thumbnail';
       	insert ci;

       	cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u2 = testusers.getInternalUser();
		Contact con2 = testusers.getInternalContact();
        
        System.runAs(u2) {
	        
    		PageReference pageRef2 = Page.cov_announcements_dash;
	        Test.setCurrentPage(pageRef2);
	        
	        cov_announcements_controller controller2 = new cov_announcements_controller();
	        controller2.cmpIdChosen = c1.Id;
	        controller2.dismiss();

	        System.assertEquals('Dismissed',[select Status from CampaignMember where CampaignId = :c1.Id and ContactId = :con2.Id limit 1].Status);

        }         


    }


	static testMethod void cov_announcements_Petition_Test() {
        
		Campaign c1 = new Campaign(name='Test Petition 1', Type='Petition', IsActive=TRUE);
		c1.Event_Public_Details__c ='These are the public details';
		c1.Show_Inside_COV_To__c = 'Everyone';
		insert c1;

		Campaign c2 = new Campaign(name='Test Campaign 2', Type='COV Announcement', IsActive=FALSE);
		c2.Event_Public_Details__c ='These are the public details';
		c2.Show_Inside_COV_To__c = 'Campaign Members';
		insert c2;
		
       	Campaign_Image__c ci = new Campaign_Image__c();
       	ci.Campaign__c = c1.Id;
       	ci.Size__c = 'Full';
       	insert ci;

       	cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u2 = testusers.getInternalUser();
		Contact con2 = testusers.getInternalContact();
        
        System.runAs(u2) {
	        
    		PageReference pageRef2 = Page.cov_announcements_dash;
	        Test.setCurrentPage(pageRef2);
	        
	        cov_announcements_controller controller = new cov_announcements_controller();
	        controller.cmpIdChosen = c1.Id;
	        controller.signPetition();

	        System.assertEquals('Signed',[select Status from CampaignMember where CampaignId = :c1.Id and ContactId = :con2.Id limit 1].Status);

	        // This caused an Implementation restriction: FeedItem requires a filter by Id
	        //System.assertEquals(true, [select Body from FeedItem where parentId = :u2.Id limit 1].Body.contains('just signed the petition'));

	        System.assertEquals(true, ApexPages.getMessages().get(0).getSummary().contains('signed the petition.'));

        }         


    }
   

	
}