prodMetadata/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Veteran_Family_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Veteran Family Member</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

prodMetadata/src/objects/Chatter_Group_Mirror__c.object
<CustomObject>
    <description>Object to add additional info to chatter groups (CollaborationGroups)</description>
    <fields>
        <fullName>Add_everyone_to_group__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Add everyone to the group the first time they log in to the community</description>
        <inlineHelpText>Add everyone to the group the first time they log in to the community</inlineHelpText>
        <label>Add everyone to group (deprec.)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Add_to_Group__c</fullName>
        <description>For any categories selected here, contacts matching those member categories will be automatically added to this group on their first visit to myIAVA.</description>
        <inlineHelpText>For any categories selected here, contacts matching those member categories will be automatically added to this group on their first visit to myIAVA.</inlineHelpText>
        <label>Auto-Add These Categories to Group</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Other Era</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Everyone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Add_to_Selected_States__c</fullName>
        <description>For any categories selected here, contacts matching those member categories and whose state is selected in the &quot;Auto-Add States&quot; field will be automatically added to this group on their first visit to myIAVA.</description>
        <inlineHelpText>For any categories selected here, contacts matching those member categories and whose state is selected in the &quot;Auto-Add States&quot; field will be automatically added to this group on their first visit to myIAVA.</inlineHelpText>
        <label>Auto-Add Categories for Selected States</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Other Era</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Everyone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_add_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>People in this campaign will be added to this group during first login to COV</description>
        <inlineHelpText>People in this campaign will be added to this group during first login to COV</inlineHelpText>
        <label>Auto-add Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Chatter Group Mirrors</relationshipLabel>
        <relationshipName>Chatter_Group_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_add_States__c</fullName>
        <description>People with address in these states will be added to this group during first login to COV</description>
        <inlineHelpText>People with address in these states will be added to this group during first login to COV</inlineHelpText>
        <label>Auto-add States</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Chatter Group Mirror</label>
    <nameField>
        <label>Chatter Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chatter Group Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Member_Categories__c</fullName>
        <description>Semi-colon-separated list of all member categories that apply (Confirmed;Unconfirmed;OtherEra;Family)</description>
        <formula>if ( Veteran_Member_Status__c = &quot;Confirmed&quot;, &quot;Confirmed&quot;, 
  if( CONTAINS(Veteran_Member_Status__c, &quot;Unconfirmed&quot;), &quot;Unconfirmed&quot;, &quot;&quot;)
)
&amp; &quot;;&quot; &amp;
if ( Veteran_of_Other_Era__c , &quot;OtherEra&quot;, &quot;&quot;)
&amp; &quot;;&quot; &amp;
if (  Veteran_Family_Member__c , &quot;Family&quot;, &quot;&quot;)
&amp; &quot;;&quot; &amp;
if ( Not_a_Veteran__c, &quot;Non-veteran&quot;,&quot;&quot;)
&amp; &quot;;&quot; &amp; &quot;Everyone&quot;</formula>
        <inlineHelpText>Semi-colon-separated list of all member categories that apply (Confirmed;Unconfirmed;OtherEra;Family)</inlineHelpText>
        <label>Member Categories</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paperwork_Confirmation_Type__c</fullName>
        <label>Paperwork Confirmation Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Paperwork_Confirmation__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Deployed OEF/OIF/OND</fullName>
                </value>
                <value>
                    <fullName>Deployed Elsewhere post 9/11</fullName>
                </value>
                <value>
                    <fullName>Not Deployed post 9/11</fullName>
                </value>
                <value>
                    <fullName>Pre-9/11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paperwork_Confirmation__c</fullName>
        <label>Paperwork Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paperwork Not Requested Yet</fullName>
                </value>
                <value>
                    <fullName>Paperwork Requested</fullName>
                </value>
                <value>
                    <fullName>Sent First Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Sent Second Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Standard Question/Issue</fullName>
                </value>
                <value>
                    <fullName>Paperwork Received</fullName>
                </value>
                <value>
                    <fullName>Paperwork Accepted</fullName>
                </value>
                <value>
                    <fullName>Paperwork Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated user for portal (COV)</description>
        <inlineHelpText>Associated user for portal (COV)</inlineHelpText>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PortalContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Veteran_Family_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Veteran Family Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Veteran_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates whether or not a contact is a Veteran Member, confirmed or unconfirmed.  Only membership should modify this field.</description>
        <label>Veteran Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Veteran_of_Other_Era__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Veteran of Other Era</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Date_of_COV_Terms_and_Conduct_Acceptance__c</fullName>
        <description>Date the user joined COV, thereby accepting any terms and conditions listed on the COV Gateway page.</description>
        <inlineHelpText>Date the user joined COV, thereby accepting any terms and conditions listed on the COV Gateway page.</inlineHelpText>
        <label>Date of COV Terms and Conduct Acceptance</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_first_COV_login__c</fullName>
        <description>Marking the first time the user logs in to COV</description>
        <inlineHelpText>Marking the first time the user logs in to COV</inlineHelpText>
        <label>Date of first COV login</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

prodMetadata/src/classes/cov_firstlogin_controller_TESTS.cls
@isTest
private class cov_firstlogin_controller_TESTS {
	
	@isTest static void test_firstlogin() {
		
       	cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u1 = testusers.getPortalUser();
		Contact c1 = testusers.getPortalContact();

       	cov_user_TEST_utility testusers2 = new cov_user_TEST_utility();
		Contact c2 = testusers2.getPortalContact();

		npe4__Relationship__c r1 = new npe4__Relationship__c(
											npe4__Contact__c = c1.Id
											, npe4__RelatedContact__c = c2.Id
											, npe4__Type__c = 'Vouched for by'
											, npe4__Status__c = 'Current'
											);
		insert r1;

		// no longer works - validation rule prevents relationship to own contact
		// also try a relationship between a contact and itself to make sure
		// it doesnt attempt to follow self
		//npe4__Relationship__c r2 = new npe4__Relationship__c(
		//									npe4__Contact__c = c1.Id
		//									, npe4__RelatedContact__c = c1.Id
		//									, npe4__Type__c = 'Vouched for by'
		//									, npe4__Status__c = 'Current'
		//									);
		//insert r2;


		Id theNetwork = cov_user_utility.self.getNetworkId();
		CollaborationGroup cg1 = new CollaborationGroup(Name='Test Group 1', CollaborationType='Public', NetworkId=theNetwork);
		CollaborationGroup cg2 = new CollaborationGroup(Name='Test Group 2', CollaborationType='Public', NetworkId=theNetwork);
		CollaborationGroup cg3 = new CollaborationGroup(Name='Test Group 3', CollaborationType='Public', NetworkId=theNetwork);
		CollaborationGroup cg4 = new CollaborationGroup(Name='Test Group 4', CollaborationType='Public', NetworkId=theNetwork);
		CollaborationGroup cg5 = new CollaborationGroup(Name='Test Group 5', CollaborationType='Public', NetworkId=theNetwork);
		insert new List<CollaborationGroup>{cg1, cg2, cg3, cg4, cg5};
		Chatter_Group_Mirror__c cgm2 = new Chatter_Group_Mirror__c(Name=cg2.Name);
		Chatter_Group_Mirror__c cgm3 = new Chatter_Group_Mirror__c(Name=cg3.Name);
		Chatter_Group_Mirror__c cgm4 = new Chatter_Group_Mirror__c(Name=cg4.Name);
		Chatter_Group_Mirror__c cgm5 = new Chatter_Group_Mirror__c(Name=cg5.Name);
		insert new List<Chatter_Group_Mirror__c>{cgm2, cgm3, cgm4, cgm5};

		Campaign cmp = new Campaign(Name='Test Campaign 123');
		insert cmp;
		CampaignMember cmpmemb = new CampaignMember(ContactId = c1.Id, CampaignId = cmp.Id);
		insert cmpmemb;
		c1.MailingState = 'NM';
		c1.Veteran_Member__c = true;
		c1.Email = u1.Email;
		update c1;


		System.RunAs(u1) {
			System.debug('Running as u1.Id: ' + u1.Id);

			cov_user_utility.self.refreshSelf();
			system.debug('current member category: ' + cov_user_utility.self.getC().Member_Categories__c);
			//system.assertEquals(c1.Id, cov_user_utility.self.getC().Id);
			cov_firstlogin_controller controller = new cov_firstlogin_controller();
			
			// without an acceptance date the user will get redirected to the gateway page
			System.assertEquals(Page.cov_gateway.getUrl(), controller.checkFirstLogin().getUrl());

			u1.Date_of_COV_Terms_and_Conduct_Acceptance__c = datetime.now();
			update u1;

			cov_firstlogin_controller.u = null;
			cov_user_utility.self.refreshSelf();
			controller = new cov_firstlogin_controller();

			Test.startTest();

			// pre-method baseline
			//System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Name='Introduce Yourself'].size());
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg1.Id].size());
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg2.Id].size());
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg3.Id].size());
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg4.Id].size());
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg5.Id].size());


			controller.checkFirstLogin();
			List <EntitySubscription> follows = [select parentId, subscriberid, networkId from EntitySubscription
				where subscriberid = :c1.Portal_User__c and parentid = :c2.Portal_User__c limit 1000];	
			System.debug('c1.Portal_User__c: ' + c1.Portal_User__c);
			System.debug('c2.Portal_User__c: ' + c2.Portal_User__c);
			System.assertEquals(1, follows.size());

			//System.assertEquals('Supporter', [select CompanyName from User where Id = :u1.Id limit 1].CompanyName);

			// still should be 0 since none of the mirrors were marked as add everyone
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg1.Id].size());
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg2.Id].size());
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg3.Id].size());
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg4.Id].size());
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg5.Id].size());

			//cgm2.Add_everyone_to_group__c = true;
			cgm2.Auto_Add_to_Group__c = 'Unconfirmed';
			cgm4.Auto_add_Campaign__c = cmp.Id;
			cgm3.Auto_add_States__c = 'DE;WY'; // shouldnt match the contact's state
			cgm3.Auto_Add_to_Selected_States__c = 'Everyone';
			cgm5.Auto_add_States__c = 'NY;NM;CA'; // should match the contact's state
			cgm5.Auto_Add_to_Selected_States__c = 'Everyone';
			update new List<Chatter_Group_Mirror__c>{cgm2, cgm4, cgm3, cgm5};
			u1.Date_of_first_COV_login__c = null;
			update u1;
			cov_firstlogin_controller.u = null;
			cov_firstlogin_controller.isFirstLogin = null;
			cov_user_utility.self.refreshSelf();
			controller = new cov_firstlogin_controller();
			controller.checkFirstLogin();
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg1.Id].size());
			System.assertEquals(1, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg2.Id].size());
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg3.Id].size());
			System.assertEquals(1, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg4.Id].size());
			System.assertEquals(1, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Id = :cg5.Id].size());


			//if ([select Id from CollaborationGroupMember where CollaborationGroup.Name='Introduce Yourself'].size() > 0) {
			//	System.assertEquals(1, [select Id from CollaborationGroupMember where MemberId = :u1.Id and CollaborationGroup.Name='Introduce Yourself'].size());
			//}

			// cover the case if First Login Date already filled in
			cov_firstlogin_controller.isFirstLogin = null;
			controller.checkFirstLogin();

			Test.stopTest();

		}

	}

	@isTest static void test_firstlogin_group_targeting_1() {

		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u1 = testusers.getPortalUser();
		Contact c1 = testusers.getPortalContact();

		Id theNetwork = cov_user_utility.self.getNetworkId();
		CollaborationGroup cg1 = new CollaborationGroup(Name='Test Group 1', CollaborationType='Public', NetworkId=theNetwork);
		insert cg1;
		Chatter_Group_Mirror__c cgm1 = new Chatter_Group_Mirror__c(Name=cg1.Name, Auto_Add_to_Group__c = 'Unconfirmed');
		insert cgm1;

		c1.Email = u1.Email;
		update c1;

		System.RunAs(u1) {
			u1.Date_of_COV_Terms_and_Conduct_Acceptance__c = datetime.now();
			update u1;
		}

		runTheTest(u1, cg1, 0, 'Everyone');

		c1.Veteran_Member__c = true;
		update c1;

		runTheTest(u1, cg1, 1, 'Unconfirmed');

		removeFromGroup(u1, cg1);
		cgm1.Auto_Add_to_Group__c = 'Confirmed';
		update cgm1;

		runTheTest(u1, cg1, 0, 'Unconfirmed');

		cgm1.Auto_Add_to_Group__c = 'Unconfirmed;Family';
		update cgm1;
		runTheTest(u1, cg1, 1, 'Unconfirmed');

	}

	@isTest static void test_firstlogin_group_targeting_2() {

		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u1 = testusers.getPortalUser();
		Contact c1 = testusers.getPortalContact();

		Id theNetwork = cov_user_utility.self.getNetworkId();
		CollaborationGroup cg1 = new CollaborationGroup(Name='Test Group 1', CollaborationType='Public', NetworkId=theNetwork);
		insert cg1;
		Chatter_Group_Mirror__c cgm1 = new Chatter_Group_Mirror__c(Name=cg1.Name, Auto_Add_to_Group__c = 'Unconfirmed');
		insert cgm1;

		c1.Email = u1.Email;
		update c1;

		System.RunAs(u1) {
			u1.Date_of_COV_Terms_and_Conduct_Acceptance__c = datetime.now();
			update u1;
		}

		c1.Veteran_of_Other_Era__c = true;
		update c1;
		cgm1.Auto_Add_to_Group__c = 'Other Era';
		update cgm1;

		runTheTest(u1, cg1, 1, 'OtherEra');

		removeFromGroup(u1, cg1);
		cgm1.Auto_Add_to_Group__c = 'Confirmed;Family';
		update cgm1;
		runTheTest(u1, cg1, 0, 'OtherEra');

		c1.Veteran_Family_Member__c = true;
		update c1;
		runTheTest(u1, cg1, 1, 'Family');

	}

	@isTest static void test_firstlogin_group_targeting_3() {

		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u1 = testusers.getPortalUser();
		Contact c1 = testusers.getPortalContact();

		Id theNetwork = cov_user_utility.self.getNetworkId();
		CollaborationGroup cg1 = new CollaborationGroup(Name='Test Group 1', CollaborationType='Public', NetworkId=theNetwork);
		insert cg1;
		Chatter_Group_Mirror__c cgm1 = new Chatter_Group_Mirror__c(Name=cg1.Name, Auto_Add_to_Group__c = 'Unconfirmed');
		insert cgm1;

		c1.Email = u1.Email;
		update c1;

		System.RunAs(u1) {
			u1.Date_of_COV_Terms_and_Conduct_Acceptance__c = datetime.now();
			update u1;
		}

		cgm1.Auto_Add_to_Group__c = 'Confirmed;Other Era';
		update cgm1;
		c1.Paperwork_Confirmation__c = 'Paperwork Accepted';
		c1.Paperwork_Confirmation_Type__c = 'Deployed OEF/OIF/OND';
		update c1;
		runTheTest(u1, cg1, 1, 'Confirmed');		

		removeFromGroup(u1, cg1);
		cgm1.Auto_Add_to_Group__c = 'Everyone';
		update cgm1;
		runTheTest(u1, cg1, 1, 'Confirmed');		

		removeFromGroup(u1, cg1);
		c1.Paperwork_Confirmation__c = null;
		c1.Paperwork_Confirmation_Type__c = null;
		c1.Veteran_Member__c = false;
		update c1;
		runTheTest(u1, cg1, 1, 'Everyone');	

	}

	@isTest static void test_firstlogin_state_targeting_1() {

		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u1 = testusers.getPortalUser();
		Contact c1 = testusers.getPortalContact();

		Id theNetwork = cov_user_utility.self.getNetworkId();
		CollaborationGroup cg1 = new CollaborationGroup(Name='Test Group 1', CollaborationType='Public', NetworkId=theNetwork);
		insert cg1;
		Chatter_Group_Mirror__c cgm1 = new Chatter_Group_Mirror__c(Name=cg1.Name, Auto_add_States__c = 'NY;DE');
		insert cgm1;

		c1.Email = u1.Email;
		c1.Veteran_Member__c = true;
		c1.MailingState = 'NY';
		update c1;

		System.RunAs(u1) {
			u1.Date_of_COV_Terms_and_Conduct_Acceptance__c = datetime.now();
			update u1;
		}

		system.debug('scenario 1');
		runTheTest(u1, cg1, 0, 'Unconfirmed');		

		system.debug('scenario 2');
		cgm1.Auto_Add_to_Selected_States__c = 'Confirmed';
		update cgm1;
		runTheTest(u1, cg1, 0, 'Unconfirmed');		

		system.debug('scenario 3');
		cgm1.Auto_Add_to_Selected_States__c = 'Unconfirmed';
		update cgm1;
		runTheTest(u1, cg1, 1, 'Unconfirmed');		

		system.debug('scenario 4');
		removeFromGroup(u1, cg1);
		cgm1.Auto_Add_to_Selected_States__c = 'Other Era;Family';
		update cgm1;
		c1.Veteran_of_Other_Era__c = true;
		update c1;
		runTheTest(u1, cg1, 1, 'OtherEra');		

	}

	@isTest static void test_firstlogin_state_targeting_2() {

		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u1 = testusers.getPortalUser();
		Contact c1 = testusers.getPortalContact();

		Id theNetwork = cov_user_utility.self.getNetworkId();
		CollaborationGroup cg1 = new CollaborationGroup(Name='Test Group 1', CollaborationType='Public', NetworkId=theNetwork);
		insert cg1;
		Chatter_Group_Mirror__c cgm1 = new Chatter_Group_Mirror__c(Name=cg1.Name, Auto_add_States__c = 'NY;DE', Auto_Add_to_Selected_States__c = 'Everyone');
		insert cgm1;

		c1.Email = u1.Email;
		c1.MailingState = 'CA';
		update c1;

		System.RunAs(u1) {
			u1.Date_of_COV_Terms_and_Conduct_Acceptance__c = datetime.now();
			update u1;
		}

		system.debug('scenario 5');
		runTheTest(u1, cg1, 0, 'Everyone');	

		system.debug('scenario 6');
		c1.MailingState = 'NY';
		update c1;
		runTheTest(u1, cg1, 1, 'Everyone');	

		system.debug('scenario 7');
		removeFromGroup(u1, cg1);
		cgm1.Auto_Add_to_Selected_States__c = 'Confirmed';
		update cgm1;
		c1.Veteran_Member__c = true;
		c1.Paperwork_Confirmation__c = 'Paperwork Accepted';
		c1.Paperwork_Confirmation_Type__c = 'Deployed OEF/OIF/OND';
		update c1;
		runTheTest(u1, cg1, 1, 'Confirmed');	

	}


	private static void removeFromGroup(User theU, CollaborationGroup theCg) {
		delete [select Id from CollaborationGroupMember where MemberId = :theU.Id and CollaborationGroupId = :theCg.Id];
	}


	private static void runTheTest(User theU, CollaborationGroup theCg, Integer result, String memberCatContains) {
		System.RunAs(theU) {
			System.debug('Running as theU.Id: ' + theU.Id);

			theU.Date_of_COV_Terms_and_Conduct_Acceptance__c = datetime.now();
			theU.Date_of_first_COV_login__c = null;
			update theU;

			cov_firstlogin_controller.u = null;
			cov_user_utility.self.refreshSelf();
			system.assert(cov_user_utility.self.getC().Member_Categories__c.contains(memberCatContains));
			//system.assertEquals(c1.Id, cov_user_utility.self.getC().Id);
			cov_firstlogin_controller controller = new cov_firstlogin_controller();
			cov_firstlogin_controller.isFirstLogin = null;

			// pre-method baseline
			System.assertEquals(0, [select Id from CollaborationGroupMember where MemberId = :theU.Id and CollaborationGroup.Id = :theCg.Id].size());

			controller.checkFirstLogin();

			System.assertEquals(result, [select Id from CollaborationGroupMember where MemberId = :theU.Id and CollaborationGroup.Id = :theCg.Id].size());

		}
	}


	
}