prodMetadata/src/objects/Chatter_Group_Mirror__c.object
<CustomObject>
    <description>Object to add additional info to chatter groups (CollaborationGroups)</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Chatter Group Mirror</label>
    <nameField>
        <label>Chatter Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chatter Group Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Veteran Member</fullName>
                </value>
                <value>
                    <fullName>Veteran Supporter</fullName>
                </value>
                <value>
                    <fullName>Civilian Supporter</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Event__c.object
<CustomObject>
    <description>This object is reserved for DC event and congressional testimony tracking</description>
    <label>DC Popularity Index</label>
    <nameField>
        <displayFormat>E-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DC Popularity Index</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/IAVAEvent__c.object
<CustomObject>
    <fields>
        <fullName>Associated_Cost__c</fullName>
        <description>Cost associated with attending the event</description>
        <inlineHelpText>Cost associated with attending the event</inlineHelpText>
        <label>Associated Cost</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Chatter_Group_Mirror__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Chatter Group Mirror record for the group used to communicate with event attendees</description>
        <inlineHelpText>The Chatter Group Mirror record for the group used to communicate with event attendees (gets automatically populated on save).</inlineHelpText>
        <label>Chatter Group Mirror (auto populated)</label>
        <referenceTo>Chatter_Group_Mirror__c</referenceTo>
        <relationshipLabel>Related Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost_Description__c</fullName>
        <label>Cost Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Creator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the contact who has submitted the event via an external tool, or to be used to populate the contact of the local host whether or not they are in COV</description>
        <label>Host</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events_Hosted</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Accepted_Host_TOS__c</fullName>
        <description>Date/Time when event creator accepted IAVA Leader Code of Conduct</description>
        <inlineHelpText>Date/Time when event creator accepted IAVA Leader Code of Conduct</inlineHelpText>
        <label>Date Accepted Host TOS</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_City__c</fullName>
        <label>Location City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_State__c</fullName>
        <label>Location State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Street_Address__c</fullName>
        <label>Location Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Zip_Code__c</fullName>
        <inlineHelpText>Required if you want event to be located in geographic/zip searches.</inlineHelpText>
        <label>Location Zip Code (important)</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organizer_Type__c</fullName>
        <label>Organizer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Distributed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reply_Cap__c</fullName>
        <description>Maximum number of &quot;Yes&quot; responses before Event becomes closed to more replies. If blank then no cap.</description>
        <inlineHelpText>Maximum number of &quot;Yes&quot; responses before Event becomes closed to more replies. If blank then no cap.</inlineHelpText>
        <label>Reply Cap</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <inlineHelpText>Format: 12:15 PM (use local time for the event)</inlineHelpText>
        <label>Start Time (local)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unpublished</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Flagged/Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Thumbnail_image_URL__c</fullName>
        <description>When the user uploads a new photo to a published group, the URL of the thumbnail version is inserted here and takes precedence over any attached thumbnail images.</description>
        <inlineHelpText>When the user uploads a new photo to a published group, the URL of the thumbnail version is inserted here and takes precedence over any attached thumbnail images. For an external site use a secure HTTPS link to prevent a secure site certificate error.</inlineHelpText>
        <label>Thumbnail image URL (automatic) - HTTPS</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <inlineHelpText>1=IAVA mandated event (Press Conf/Testimony); 2=Creator is receptive to IAVA directives; 3=Creator is a reliable leader &amp; uses own devices; 4=Creator is using the VetTogether tool to promote their own event &amp; not interested in deeper engagement</inlineHelpText>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Awareness Action</fullName>
                </value>
                <value>
                    <fullName>Bar Gathering</fullName>
                </value>
                <value>
                    <fullName>Career Development</fullName>
                </value>
                <value>
                    <fullName>Concert</fullName>
                </value>
                <value>
                    <fullName>Cookout</fullName>
                </value>
                <value>
                    <fullName>DPAA Burial</fullName>
                </value>
                <value>
                    <fullName>Fundraiser</fullName>
                </value>
                <value>
                    <fullName>Internal IAVA Training</fullName>
                </value>
                <value>
                    <fullName>Movie Screening</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outdoor Activity</fullName>
                </value>
                <value>
                    <fullName>Parade</fullName>
                </value>
                <value>
                    <fullName>Run</fullName>
                </value>
                <value>
                    <fullName>Seminar/Education</fullName>
                </value>
                <value>
                    <fullName>Service Project</fullName>
                </value>
                <value>
                    <fullName>Social</fullName>
                </value>
                <value>
                    <fullName>Sporting Event</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>VetTogether</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prodMetadata/src/objects/IAVAEvent_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <formula>Event__r.Event_Date__c</formula>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>IAVAEvent__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reply_Status__c</fullName>
        <label>Reply Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>Atnd-{000000}</displayFormat>
        <label>Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/cov_event_entry_controller_TESTS.cls
// needs SeeAllData=true to test connectAPI method for adding photo to group
// but that causes an internal server error so commenting out
//@isTest(SeeAllData=true)

@isTest
private class cov_event_entry_controller_TESTS {

	static testMethod void test_event_entry() {

		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u = testusers.getPortalUser();
		Contact c = testusers.getPortalContact();

		IAVAEvent__c e1;

		System.runAs(u) {
			cov_user_utility.self.refreshSelf();

			PageReference pageRef = Page.cov_event_entry;
	        Test.setCurrentPage(pageRef);

	        e1 = new IAVAEvent__c();
	        ApexPages.StandardController sc = new ApexPages.standardController(e1);
	        cov_event_entry_controller controller = new cov_event_entry_controller(sc);
	        System.assertEquals(false, controller.costCheckbox);

	        e1.Name = 'Unit Test Name 1';
	        e1.Type__c = 'VetTogether';
	        e1.Event_Date__c = System.today().addDays(14);
	        e1.Start_Time__c = '7:00 PM';
	        //e1.Location_Street_Address__c = '1114 Main St';
	        //e1.Location_City__c = 'Test City';
	        //e1.Location_State__c = 'TS';
	        //e1.Location_Zip_Code__c = '12345';
	        e1.Reply_Cap__c = 5;
	        e1.Associated_Cost__c = 15.50;
	        e1.Cost_Description__c = 'Two people per entry';

	        PageReference pr = controller.save();

	        // save should not have worked without user agreeing to host TOS
	        system.assertEquals(null, pr);
	        System.AssertEquals(true, ApexPages.getMessages()[0].getSummary().contains('Leader Code of Conduct'));

	        // now check host TOS box and try again
	        controller.hostTOSAccepted = true;

	        pr = controller.save();

	        List<IAVAEvent__c> evs = [select Id, Name, Type__c, Organizer_Type__c, OwnerId
	        								, Date_Accepted_Host_TOS__c
	        								, Status__c, Chatter_Group_Mirror__c
	        								, Location_City__c, Location_State__c 
	        								, Location_Street_Address__c, Location_Zip_Code__c
	        								, Start_Time__c, Event_Date__c, Creator_Contact__c, Reply_Cap__c
	        								, Associated_Cost__c, Cost_Description__c, Tier__c
	        								from IAVAEvent__c where Name = 'Unit Test Name 1'
	        								];
	        System.assertEquals(1, evs.size());
	        System.assertNotEquals(null, evs[0].Date_Accepted_Host_TOS__c);
	        system.assert(evs[0].Date_Accepted_Host_TOS__c > System.now().addMinutes(-10) && evs[0].Date_Accepted_Host_TOS__c <= System.now());
	        System.assertEquals('/apex/cov_event?id=' + evs[0].Id, pr.getUrl());
	        System.assertEquals('VetTogether', evs[0].Type__c);
	        System.assertEquals('Distributed', evs[0].Organizer_Type__c);
	        System.assertEquals('Unpublished', evs[0].Status__c);
	        System.assertEquals('3', evs[0].Tier__c);
	        System.assertEquals(c.Id, evs[0].Creator_Contact__c);
	        System.assertEquals(5, evs[0].Reply_Cap__c);
	        System.assertEquals(e1.Associated_Cost__c, evs[0].Associated_Cost__c);
	        System.assertEquals(e1.Cost_Description__c, evs[0].Cost_Description__c);
	        System.assertEquals(null, evs[0].Chatter_Group_Mirror__c);
	        System.assertEquals(0, [select Id from CollaborationGroup where Name = :('[Event] ' + e1.Name)].size());

	        e1.Date_Accepted_Host_TOS__c = evs[0].Date_Accepted_Host_TOS__c;

	        pageRef = Page.cov_event_entry;
	        pageRef.getParameters().put('id', evs[0].Id);
	        Test.setCurrentPage(pageRef);
	        e1 = evs[0];
			sc = new ApexPages.standardController(e1);
	        controller = new cov_event_entry_controller(sc);
	        System.assertEquals(true, controller.costCheckbox);	        

	        e1.Location_Street_Address__c = '1114 Main St';
	        e1.Location_City__c = 'Test City';
	        e1.Location_State__c = 'TS';
	        e1.Location_Zip_Code__c = '12345';
	        controller.costCheckbox = false;
			pr = controller.save();
			String addressParam = (e1.Location_Street_Address__c + ' ' + e1.Location_City__c + ' ' + e1.Location_State__c + ' ' + e1.Location_Zip_Code__c).replaceAll(' ', '%2B');
	        System.assertEquals('/apex/cov_event_geolocate?address=' + addressParam + '&id=' + evs[0].Id, pr.getUrl());

	        System.assertEquals(null, evs[0].Associated_Cost__c);
	        System.assertEquals(null, evs[0].Cost_Description__c);

	        pageRef = Page.cov_event_entry;
	        pageRef.getParameters().put('id', evs[0].Id);
	        Test.setCurrentPage(pageRef);
	        e1 = evs[0];
			sc = new ApexPages.standardController(e1);
	        controller = new cov_event_entry_controller(sc);



	        //TEST ATTACHMENTS

	        // no attachments yet
	        System.assertEquals(null, controller.existingImageId);
	        System.assertEquals(0, [select Id, Name from Attachment where ParentId = :evs[0].Id].size());

	        // only a fullsize attachment added
	        controller.newImageFull = 'R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';
	        controller.newImageName = 'random-filename.jpg';
	        controller.newImageType = 'image/jpg';
	        controller.save();

	        System.assertNotEquals(null, controller.existingImageId);
	        List<Attachment> atts = [select Id, Name from Attachment where ParentId = :evs[0].Id];
	        System.assertEquals(1, atts.size());
	        System.assert(atts[0].Name.startsWith('image-full'));

	        // delete full size attachment
	        controller.deletePic();
	        System.assertEquals(null, controller.existingImageId);
	        System.assertEquals(0, [select Id, Name from Attachment where ParentId = :evs[0].Id].size());

	        // add both full size and thumbnail attachments
	        controller.newImageFull = 'R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';
	        controller.newImageThumb = 'R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';
	        controller.newImageName = 'random-filename.jpg';
	        controller.newImageType = 'image/jpg';
	        controller.save();

	        System.assertNotEquals(null, controller.existingImageId);
	        atts = [select Id, Name from Attachment where ParentId = :evs[0].Id];
	        System.assertEquals(2, atts.size());
	        System.assert(
	        	(atts[0].Name.startsWith('image-full') && atts[1].Name.startsWith('image-thumb'))
	        	||
	        	(atts[1].Name.startsWith('image-full') && atts[0].Name.startsWith('image-thumb'))
	        	);

	        // delete both attachments
	        controller.deletePic();
	        System.assertEquals(null, controller.existingImageId);
	        System.assertEquals(0, [select Id, Name from Attachment where ParentId = :evs[0].Id].size());


	        System.assertEquals('Unpublished', evs[0].Status__c);
	        System.assertEquals(0, [select Id from CollaborationGroup where Name = :('[Event] ' + e1.Name)].size());

	        e1 = evs[0];
			sc = new ApexPages.standardController(e1);
	        controller = new cov_event_entry_controller(sc);
	        System.assertEquals('Test City', evs[0].Location_City__c);
	        e1.Location_City__c = 'Changed City';
	        controller.save();
	        evs = [select Id, Name, Type__c, Organizer_Type__c, OwnerId
	        								, Date_Accepted_Host_TOS__c
	        								, Status__c, Chatter_Group_Mirror__c
	        								, Location_City__c, Location_State__c
	        								, Location_Street_Address__c, Location_Zip_Code__c
	        								, Start_Time__c, Event_Date__c
	        								, Associated_Cost__c, Cost_Description__c
	        								from IAVAEvent__c where Name = 'Unit Test Name 1'
	        								];
	        System.assertEquals('Changed City', evs[0].Location_City__c);
	        System.assertEquals(null, evs[0].Chatter_Group_Mirror__c);

			pageRef = Page.cov_event_entry;
	        pageRef.getParameters().put('id', evs[0].Id);
	        Test.setCurrentPage(pageRef);
	        e1 = evs[0];
	        system.debug('e1.Chatter_Group_Mirror__c before publish: ' + e1.Chatter_Group_Mirror__c);
			sc = new ApexPages.standardController(e1);
	        controller = new cov_event_entry_controller(sc);
	        System.assertEquals('7:00 PM', evs[0].Start_Time__c);
	        e1.Start_Time__c = '8:00 PM';
	        controller.savePublish();
	        evs = [select Id, Name, Type__c, Organizer_Type__c, OwnerId
	        								, Status__c, Chatter_Group_Mirror__c
	        								, Location_City__c, Location_State__c
	        								, Location_Street_Address__c, Location_Zip_Code__c
	        								, Start_Time__c, Event_Date__c
	        								from IAVAEvent__c where Name = 'Unit Test Name 1'
	        								];
	        system.debug('evs[0].Chatter_Group_Mirror__c after publish: ' + evs[0].Chatter_Group_Mirror__c);
	        System.assertEquals('8:00 PM', evs[0].Start_Time__c);
	        System.assertEquals('Published', evs[0].Status__c);
	        System.assertNotEquals(null, evs[0].Chatter_Group_Mirror__c);
	        List <CollaborationGroup> cgs = [select Id, FullPhotoUrl from CollaborationGroup where Name = :('[Event] ' + e1.Name)];
	        System.assertEquals(1, cgs.size());


	        // Test that event creator got added to event with a "Yes" reply
	        List<IAVAEvent_Attendee__c> creatorAttendee = [select Id, Reply_Status__c from IAVAEvent_Attendee__c 
	        												where Event__c = :evs[0].Id
	        												and Contact__c = :c.Id
	        												];
	        System.assertEquals(1, creatorAttendee.size());
	        System.assertEquals('Yes', creatorAttendee[0].Reply_Status__c);

	        List<CollaborationGroupMember> creatorGroupMember = [select Id, NotificationFrequency from CollaborationGroupMember 
	        												where CollaborationGroupId = :cgs[0].Id
	        												and MemberId = :u.Id
	        												];
	        System.assertEquals(1, creatorGroupMember.size());
	        System.assertEquals('P', creatorGroupMember[0].NotificationFrequency);

	        //Test that default group created feeditem was deleted
	        List<CollaborationGroupFeed> cgfeeditems = [select Id from CollaborationGroupFeed
	        								where Type = 'CollaborationGroupCreated'
	        								and ParentId = :u.Id
	        								and CreatedDate = TODAY
	        								];
	        System.assertEquals(0, cgfeeditems.size());

	        // Test that replacement feeditem got created
			List<UserFeed> ufeeditems = [select Id, Title from UserFeed
	        								where Type = 'LinkPost'
	        								and ParentId = :u.Id
	        								and CreatedDate = TODAY
	        								];
	        System.assertEquals(1, ufeeditems.size());
	        System.assertEquals(evs[0].Name, ufeeditems[0].Title);


	        // Currently it doesnt add the photo to the group unless it's uploaded to a published event
	        // so cant test this here
	        //System.assert(!cgs[0].FullPhotoUrl.contains('0F9'));

	        // delete both attachments after group created to get coverage chatterAPI photo deletion code
	        System.assertEquals(null, controller.existingImageId);
	        System.assertEquals(0, [select Id, Name from Attachment where ParentId = :evs[0].Id].size());
	        controller.newImageFull = 'R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';
	        controller.newImageThumb = 'R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';
	        controller.newImageName = 'random-filename.jpg';
	        controller.newImageType = 'image/jpg';
	        controller.save();
	        System.assertNotEquals(null, controller.existingImageId);
	        System.assertEquals(2, [select Id, Name from Attachment where ParentId = :evs[0].Id].size());
	        controller.deletePic();
	        System.assertEquals(null, controller.existingImageId);
	        System.assertEquals(0, [select Id, Name from Attachment where ParentId = :evs[0].Id].size());



	        // these were tests for the remote action method, now deprecated

	  //      String fileBody = 'R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';
	  //      String sitePrefix = 'http://my.iava.org';
	  //      Id attId = cov_event_entry_controller.uploadImage(e1.Id, sitePrefix, 'image-full-random-filename.jpg', 'image/jpg', fileBody);
	  //      controller = new cov_event_entry_controller(sc);

	  //     	System.assertNotEquals(null, controller.existingImageId);
	  //     	System.assertEquals(attId, controller.existingImageId);
	  //     	System.assertEquals(null, [select Thumbnail_image_URL__c from IAVAEvent__c where Id = :e1.Id].Thumbnail_image_URL__c);

	  //      controller.deletePic();
	  //      controller.existingImageId = null;
			//System.assertEquals(null, controller.existingImageId);	        

	  //      Id thumbId = cov_event_entry_controller.uploadImage(e1.Id, sitePrefix, 'image-thumb-random-filename.jpg', 'image/jpg', fileBody);
	  //      controller = new cov_event_entry_controller(sc);
	  //     	System.assertEquals(sitePrefix + 'servlet/servlet.FileDownload?file=' + thumbId, [select Thumbnail_image_URL__c from IAVAEvent__c where Id = :e1.Id].Thumbnail_image_URL__c);





	        //// fake test coverage on the photo getting added to the group
	        //controller.imageFile = new Attachment(Body=EncodingUtil.base64decode('R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==')
	        //										, Name='random-filename.jpg');
	        //controller.uploadImageContentType = '.jpg';
	        //system.debug('controller.imageFile in test after assignment: ' + controller.imageFile);
	        //controller.save();
	        evs = [select Id, Name, Type__c, Organizer_Type__c, OwnerId
	        								, Date_Accepted_Host_TOS__c
	        								, Status__c, Chatter_Group_Mirror__c
	        								, Location_City__c, Location_State__c
	        								, Location_Street_Address__c, Location_Zip_Code__c
	        								, Start_Time__c, Event_Date__c
	        								, Associated_Cost__c, Cost_Description__c
	        								from IAVAEvent__c where Name = 'Unit Test Name 1'
	        								];

	        e1 = evs[0];
			sc = new ApexPages.standardController(e1);
	        controller = new cov_event_entry_controller(sc);
	        controller.saveCancel();
	        evs = [select Id, Name, Type__c, Organizer_Type__c, OwnerId
	        								, Status__c, Chatter_Group_Mirror__c
	        								, Location_City__c, Location_State__c
	        								, Location_Street_Address__c, Location_Zip_Code__c
	        								, Start_Time__c, Event_Date__c
	        								, Associated_Cost__c, Cost_Description__c
	        								from IAVAEvent__c where Name = 'Unit Test Name 1'
	        								];
	        System.assertEquals('Canceled', evs[0].Status__c);


	        // test getStateOptions
	        List<SelectOption> states = controller.getStateOptions();
	        Set<String> statesSet = new Set<String>();
	        for(SelectOption s : states) {
	        	statesSet.add(s.getValue());
	        }
	        System.assert(statesSet.contains('CA'));
	        System.assert(statesSet.contains('NY'));
	        System.assert(statesSet.contains('HI'));
	        System.assert(statesSet.contains('NM'));

	        // ~ Imagefile
	        // √ create group
	        // x group photo
	        // Delete feeditems
	        // create feeditem

			//atts = [select Id, Reply_Status__c from IAVAEvent_Attendee__c where Event__c = :e1.Id and Contact__c = :c.Id];
	  //  	System.assertEquals(1, atts.size());	
	  //  	System.assertEquals('Yes', atts[0].Reply_Status__c);	




	  //      List<Apexpages.Message> msgs = ApexPages.getMessages();
			//boolean b = false;
			//for(Apexpages.Message msg:msgs){
			//    if (msg.getDetail().contains('Search requires more characters')) b = true;
			//}
			//system.assert(b);


		}


	}





}