prodMetadata/src/objects/Chatter_Group_Mirror__c.object
<CustomObject>
    <description>Object to add additional info to chatter groups (CollaborationGroups)</description>
    <fields>
        <fullName>Add_everyone_to_group__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Add everyone to the group the first time they log in to the community</description>
        <inlineHelpText>Add everyone to the group the first time they log in to the community</inlineHelpText>
        <label>Add everyone to group (deprec.)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Add_to_Group__c</fullName>
        <description>For any categories selected here, contacts matching those member categories will be automatically added to this group on their first visit to myIAVA.</description>
        <inlineHelpText>For any categories selected here, contacts matching those member categories will be automatically added to this group on their first visit to myIAVA.</inlineHelpText>
        <label>Auto-Add These Categories to Group</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Other Era</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Everyone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_Add_to_Selected_States__c</fullName>
        <description>For any categories selected here, contacts matching those member categories and whose state is selected in the &quot;Auto-Add States&quot; field will be automatically added to this group on their first visit to myIAVA.</description>
        <inlineHelpText>For any categories selected here, contacts matching those member categories and whose state is selected in the &quot;Auto-Add States&quot; field will be automatically added to this group on their first visit to myIAVA.</inlineHelpText>
        <label>Auto-Add Categories for Selected States</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Other Era</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Everyone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auto_add_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>People in this campaign will be added to this group during first login to COV</description>
        <inlineHelpText>People in this campaign will be added to this group during first login to COV</inlineHelpText>
        <label>Auto-add Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Chatter Group Mirrors</relationshipLabel>
        <relationshipName>Chatter_Group_Mirrors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_add_States__c</fullName>
        <description>People with address in these states will be added to this group during first login to COV</description>
        <inlineHelpText>People with address in these states will be added to this group during first login to COV</inlineHelpText>
        <label>Auto-add States</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <description>The group&apos;s Salesforce ID</description>
        <inlineHelpText>The group&apos;s Salesforce ID</inlineHelpText>
        <label>Group ID (filled in automatically)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chatter Group Mirror</label>
    <nameField>
        <label>Chatter Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chatter Group Mirrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Member_Categories__c</fullName>
        <description>Semi-colon-separated list of all member categories that apply (Confirmed;Unconfirmed;OtherEra;Family)</description>
        <formula>if ( Veteran_Member_Status__c = &quot;Confirmed&quot;, &quot;Confirmed&quot;, 
  if( CONTAINS(Veteran_Member_Status__c, &quot;Unconfirmed&quot;), &quot;Unconfirmed&quot;, &quot;&quot;)
)
&amp; &quot;;&quot; &amp;
if ( Veteran_of_Other_Era__c , &quot;OtherEra&quot;, &quot;&quot;)
&amp; &quot;;&quot; &amp;
if (  Veteran_Family_Member__c , &quot;Family&quot;, &quot;&quot;)
&amp; &quot;;&quot; &amp;
if ( Not_a_Veteran__c, &quot;Non-veteran&quot;,&quot;&quot;)
&amp; &quot;;&quot; &amp; &quot;Everyone&quot;</formula>
        <inlineHelpText>Semi-colon-separated list of all member categories that apply (Confirmed;Unconfirmed;OtherEra;Family)</inlineHelpText>
        <label>Member Categories</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated user for portal (COV)</description>
        <inlineHelpText>Associated user for portal (COV)</inlineHelpText>
        <label>Portal User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PortalContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Date_of_COV_Terms_and_Conduct_Acceptance__c</fullName>
        <description>Date the user joined COV, thereby accepting any terms and conditions listed on the COV Gateway page.</description>
        <inlineHelpText>Date the user joined COV, thereby accepting any terms and conditions listed on the COV Gateway page.</inlineHelpText>
        <label>Date of COV Terms and Conduct Acceptance</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_first_COV_login__c</fullName>
        <description>Marking the first time the user logs in to COV</description>
        <inlineHelpText>Marking the first time the user logs in to COV</inlineHelpText>
        <label>Date of first COV login</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

prodMetadata/src/classes/cov_firstlogin_controller.cls
public with sharing class cov_firstlogin_controller {

	// replaced with custom Chatter Group Mirror object
	//public List<Id> GROUPS_TO_ADD_EVERYONE = new List<Id>();

//	public static String sessionId {get; set;}
	public static Boolean isFirstLogin {get; set;}
	public static Boolean isFirstLoginDate {get; set;}
	public static User u {get; set;}
	
	public cov_firstlogin_controller(){}
	
	public PageReference checkFirstLogin() {
		System.debug('Initializing cov_firstlogin controller. isFirstLogin: ' + isFirstLogin);

		System.debug('u: ' + u);
		if (u == null) {
			u = cov_user_utility.self.getU();
			System.debug('u after query: ' + u);
			System.debug('u.Date_of_first_COV_login__c: ' + u.Date_of_first_COV_login__c);
			System.debug('u.Date_of_COV_Terms_and_Conduct_Acceptance__c: ' + u.Date_of_COV_Terms_and_Conduct_Acceptance__c);
			System.debug('u.ContactId: ' + u.ContactId);
		}

		if (u.Date_of_COV_Terms_and_Conduct_Acceptance__c == null) {
			System.debug('u.Date_of_COV_Terms_and_Conduct_Acceptance__c is null so sending over to cov_gateway');
			return Page.cov_gateway;
		}


		if (isFirstLogin == null) {
			System.debug('u.Date_of_first_COV_login__c: ' + u.Date_of_first_COV_login__c);
			if (u.Date_of_first_COV_login__c == null) {
				isFirstLogin = true;
				isFirstLoginDate = true;
				u.Date_of_first_COV_login__c = Date.today();
				try {
					update u;
				} catch (DMLException e) { cov_log_error.logError(e); }
/*				Id theContactId = u.ContactId;
				if (theContactId == null) {
					try {
							theContactId = [select Id
									, Portal_User__c
									from Contact
									where Portal_User__c = :u.Id
									limit 1
									].Id;
							System.debug ('theContactId: ' + theContactId);
					} catch(QueryException e){
						System.debug('No related contact found. e: ' + e);
					}
				}
*/

				Id theNetworkId = cov_user_utility.self.getNetworkId();
				NetworkMember nm = [select DefaultGroupNotificationFrequency from NetworkMember 
									where MemberId = :u.Id
									and NetworkId = :theNetworkId
									limit 1
									];
				if (nm != null) {
					nm.DefaultGroupNotificationFrequency = 'D';
					try {
						update nm;
					} catch (Exception e) { cov_log_error.logError(e); }
				}

				//Contact theContact = cov_user_utility.self.getC(new List<String>{'MailingState'});
				Contact theContact = cov_user_utility.self.getC();
				Id theContactId;
				String contactState = 'NONMATCH-VALUE'; // so if contact is null the query clause wont match
				Set<Id> campaignIdsWhereContactIsMember = new Set<Id>();
				if (theContact != null) {
					theContactId = theContact.Id;
					contactState = theContact.MailingState;
					//First query all campaigns where the contact has a groupmember
					List<CampaignMember> cms = [select Campaign.Id from CampaignMember where ContactId = :theContactId];
					for (CampaignMember cm : cms) {
						campaignIdsWhereContactIsMember.add(cm.Campaign.Id);
					}
				}

				String memberCatsToSearch = cov_groups_controller.getMemberCatsSetFromMemberCatsField(theContact.Member_Categories__c);

				//List<Chatter_Group_Mirror__c> targetGroupMirrors = [select Group_Id__c from Chatter_Group_Mirror__c 
				//													where Add_everyone_to_group__c = true
				//													or (Auto_add_Campaign__c != null and Auto_add_Campaign__c in :campaignIdsWhereContactIsMember)
				//													or (Auto_add_States__c != null and Auto_add_States__c includes (:contactState))
				//													];
				String q = 'select Group_Id__c from Chatter_Group_Mirror__c'
						+ ' where '
						+ ' (Auto_Add_to_Group__c != null and Auto_Add_to_Group__c includes (' + memberCatsToSearch + '))'
						+ ' or (Auto_add_Campaign__c != null and Auto_add_Campaign__c in :campaignIdsWhereContactIsMember)'
						+ ' or (Auto_add_States__c != null and Auto_add_States__c includes (:contactState) and Auto_Add_to_Selected_States__c != null and Auto_Add_to_Selected_States__c includes (' + memberCatsToSearch + '))'
						;
				List<Chatter_Group_Mirror__c> targetGroupMirrors = Database.query(q);


				system.debug('targetGroupMirrors: ' + targetGroupMirrors);
				List<CollaborationGroup> targetGroups = new List<CollaborationGroup>();
				if (targetGroupMirrors.size() > 0) {
					targetGroups = cov_groups_controller.findGroupsByMirrors(targetGroupMirrors);
				}

				System.debug('targetGroups: ' + targetGroups);
				cov_groups_controller.addToGroups(u, targetGroups);


				if (theContact != null) {
					System.debug('About to autofollow vouchers and vice versa');
					System.debug ('theContactId: ' + theContactId);
					cov_autofollow_relationships.followAllRelationships(theContactId, new List<String>{'Vouched for by', 'Invited to event by'}, true);
					System.debug('Done with autofollowing');

					List<Id> uIds = new List<Id>();
					uIds.add(u.Id);
					//cov_profile_controller.updateUserCompanyNames(uIds);
					cov_cohort_controller.addCohort(theContactId);
				}

			} else {
				isFirstLogin = false;
				if (u.Date_of_first_COV_login__c == Date.today()) {
					isFirstLoginDate = true;
				} else {
					isFirstLoginDate = false;
				}
			}

		}
		System.debug('Exiting cov_firstlogin controller. isFirstLogin: ' + isFirstLogin);
		return null;
	}
	
}