prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_ID__c</fullName>
        <externalId>true</externalId>
        <label>Membership ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Paperwork_Confirmation__c</fullName>
        <label>Paperwork Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paperwork Not Requested Yet</fullName>
                </value>
                <value>
                    <fullName>Paperwork Requested</fullName>
                </value>
                <value>
                    <fullName>Sent First Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Sent Second Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Standard Question/Issue</fullName>
                </value>
                <value>
                    <fullName>Paperwork Received</fullName>
                </value>
                <value>
                    <fullName>Paperwork Accepted</fullName>
                </value>
                <value>
                    <fullName>Paperwork Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/IAVA_Rewards_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Last_Member_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>AUTOMATICALLY MAINTAINED.  DO NOT UPDATE.
The Last Member ID assigned to a Contact.  Is 8 character string that looks like a number.  First number assigned to any Contact is 15325001.  Is sequential after that.</inlineHelpText>
        <label>Last Member ID</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IAVA Rewards Settings</label>
    <nameField>
        <label>IAVA Rewards Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IAVA Rewards Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Log__c.object
<CustomObject>
    <description>Integration and other custom logging records will be saved to this object.  These records should be purged periodically after they are no longer useful in order to free up storage space.</description>
    <fields>
        <fullName>Message__c</fullName>
        <description>The log message</description>
        <inlineHelpText>The log message</inlineHelpText>
        <label>Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <description>Name of the process being logged</description>
        <inlineHelpText>Name of the process being logged</inlineHelpText>
        <label>Process Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/ContactTriggerLogic.cls
/*
Copyright (c) 2010 Etherios LLC
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are not permitted.

Author: Mike Dannenfeldt, mike@etherios.com
*/
public class ContactTriggerLogic {

    public final static String CONFIRMED_VETERAN = 'Paperwork Accepted';
    public final static String CUSTOM_SETTINGS_NAME = 'Main';
    public final static String StubContact = '(Unknown)';

    // Called from ContactBeforeInsert.trigger to eliminate duplicate Stub Contacts
    public static List<Contact> kickDuplicateContacts(List<Contact> newContacts) {
        Set<String> eaddrs = new Set<String>();
        List<Contact> originals = new List<Contact>();
        for (Contact con : newContacts) if ((con.Name == StubContact) && (con.email != null)) eaddrs.add(con.email);
        if (eaddrs.size() == 0) return newContacts; // No eliminations required
        List<Contact> existing = [SELECT email FROM Contact WHERE Name = :StubContact AND email IN :eaddrs];
        eaddrs.clear();
        for (Contact con : existing) if (con.email != null) eaddrs.add(con.email);
        for (Contact con : newContacts)
            if ((con.Name == StubContact) && eaddrs.contains(con.email))
                con.addError('Contact ' + StubContact + ' with email address: ' + con.email + ' is a duplicate.');
            else {
                originals.add(con);
                if ((con.Name == StubContact) && (con.email != null)) eaddrs.add(con.email);
            }
        return originals;
    }
    
    // filters the contacts before generating membership IDs for the contacts.
    public static void generateMembershipIDs(List<Contact> contacts){
        // filter out those Contacts that already have a MembershipID or are not Confirmed
        List<Contact> filteredContacts = new List<Contact>();
        for(Contact c : contacts){
            if(c.Membership_ID__c==null && c.Paperwork_Confirmation__c!=null && c.Paperwork_Confirmation__c.equalsIgnoreCase(CONFIRMED_VETERAN))  filteredContacts.add(c);
        }
        if(!filteredContacts.isEmpty()) forceGenerateMembershipIDs(filteredContacts);
    }
    
    
    // Generates a Membership ID regardless if the Contact is confirmed or already has an ID.
    public static void forceGenerateMembershipIDs(List<Contact> contacts){
        
        // Retrieve the last membership ID value given out
        IAVA_Rewards_Settings__c settings = getMainSettings();
        
        if(settings!=null && !contacts.isEmpty()){
            // Loop through the contacts and assign the new value
            Integer startValue = integer.valueOf(settings.last_member_ID__c);
            Integer nextValue = startValue;
            for(Contact c : contacts){
                nextValue++;
                c.Membership_ID__c = string.valueOf(nextValue);
            }
            // Set the IAVA Rewards Setting value to the latest ID string
            settings.last_member_id__c = string.valueOf(nextValue);
            try{                
                update settings;
            } catch(Exception ex){
                String err = '************* ERROR updating IAVA_Rewards_Settings__c - '+CUSTOM_SETTINGS_NAME+': '+ex.getTypeName() +', '+ex.getMessage() +
                                '\nsettings.last_member_id__c='+settings.last_member_id__c;
                System.debug(err);
                insert new Log__c(message__c=err,process_name__c='ContactTriggerLogic : forceGenerateMembershipIDs');
                return;
            }
        } else {
            String err = '************* ERROR generating membership IDs: IAVA_Rewards_Settings==null';
            System.debug(err);
            return;
        }
    }
    
    public static void resetContactLatitudeLongitude(List<Contact> contacts, Map<Id, Contact> oldMap){
        for(Contact c: contacts){
            Contact oldContact = oldMap.get(c.Id);
            if( c.OtherPostalCode != oldContact.OtherPostalCode ||
                c.MailingPostalCode != oldContact.MailingPostalCode){
                c.Latitude__c = '';
                c.Longitude__c = '';
            }
        }
        return;
    }
    
    
    /***********************************  Helper / Utility Methods ***************************************/
    public static IAVA_Rewards_Settings__c getMainSettings(){   
        // Retrieve the last membership ID value given out
        try{
            IAVA_Rewards_Settings__c settings = [select id,name,last_member_id__c from IAVA_Rewards_Settings__c where name=:CUSTOM_SETTINGS_NAME limit 1];
            return settings;
        } catch(Exception e){
            String err = '*********** Error retrieving IAVA Rewards Settings: '+e.getTypeName() + ', '+e.getMessage();
            System.debug(err);
            insert new Log__c(message__c=err,process_name__c='ContactTriggerLogic : getMainSettings');
            // ApexPages.addMessages(e);
            return null;
        }
    }
    
}