prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MA_Latitude__c</fullName>
        <label>Latitude (MapAnything)</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MA_Longitude__c</fullName>
        <label>Longitude (MapAnything)</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Geo_Location__c.object
<CustomObject>
    <description>Holds a Geo cordinate, and information to build a balloon for this point</description>
    <fields>
        <fullName>lat__c</fullName>
        <label>lat</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lon__c</fullName>
        <label>lon</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <label>Geo Location</label>
    <nameField>
        <label>Geo Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Giveaways</fullName>
                </value>
                <value>
                    <fullName>Discounts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geo_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Geo Location object which stores Latitude, Longitude values</description>
        <label>Geo Location</label>
        <referenceTo>Geo_Location__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Highlight_Listing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates which past and present events appear on the page of highlighted events.</description>
        <inlineHelpText>Indicates which past and present events appear on the page of highlighted events.</inlineHelpText>
        <label>Highlight Listing on homepage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_by_State_s__c</fullName>
        <description>E.g. “NY, CT, NJ, VA, DC”.</description>
        <inlineHelpText>E.g. “NY, CT, NJ, VA, DC”.</inlineHelpText>
        <label>Location by State(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>National_Give__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overides zip codes and states.</description>
        <inlineHelpText>Overrides zip codes and states.</inlineHelpText>
        <label>National Give</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <label>Num. Units</label>
        <summarizedField>Give_Instance__c.Number_of_Units__c</summarizedField>
        <summaryForeignKey>Give_Instance__c.Give__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed Visible</fullName>
                </value>
                <value>
                    <fullName>Closed Invisible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code_s__c</fullName>
        <inlineHelpText>Multiple Zip Codes should be Separate Gives</inlineHelpText>
        <label>Location by Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <description>Quantity of give items available.</description>
        <inlineHelpText>Quantity of give items available.</inlineHelpText>
        <label>Num. Units</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Request__c.object
<CustomObject>
    <description>Connects applicants to give</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Street Address</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <description>Should be a confirmed member veteran only.</description>
        <inlineHelpText>Should be a confirmed member veteran only.</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Give_Instance__c</fullName>
        <label>Give Instance</label>
        <referenceTo>Give_Instance__c</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Give Request</label>
    <nameField>
        <displayFormat>GR-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Give Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/cov_rewards_controller_TESTS.cls
@isTest
private class cov_rewards_controller_TESTS {
	
	@isTest static void cov_rewards_controller_TEST() {

		Partnership_Request__c p = new Partnership_Request__c(Name='Test Partnership', Public_Partner_Name__c='Test Public Name');
		insert p;
		Give__c g = new Give__c(Name='Test Give', National_Give__c = true, Partnership_Request__c = p.Id, Highlight_Listing__c = true);
		insert g;
		Give_Instance__c gi = new Give_Instance__c(Give__c = g.Id, Number_of_Units__c=5, Status__c='Open');
		insert gi;
		Give__c g2 = new Give__c(Name='Test Give 2', National_Give__c = true, Partnership_Request__c = p.Id, Highlight_Listing__c = true, Category__c = 'Events');
		insert g2;
		Geo_Location__c gl1 = new Geo_Location__c(Name='94102', lat__c=37.778687100000000, lon__c=-122.421242399999980);
		insert gl1;
		Give__c g3 = new Give__c(Name='Test Give 3', Geo_Location__c=gl1.id, Zip_Code_s__c='94102', National_Give__c = false, Partnership_Request__c = p.Id, Highlight_Listing__c = false, Category__c = 'Hot Dogs');
		insert g3;
		Give__c g4 = new Give__c(Name='Test Give 4', Location_by_State_s__c='OR;CA;WA', National_Give__c = false, Partnership_Request__c = p.Id, Highlight_Listing__c = false, Category__c = 'Hot Dogs');
		insert g4;


		
		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u = testusers.getPortalUser();

		// First try it while user's contact has no lat/lon fields
		System.RunAs(u) {
			cov_user_utility.self.refreshSelf();
			cov_rewards_controller controller = new cov_rewards_controller();
			List<cov_rewards_controller.customReward> glist = controller.getRewards();
			System.assertEquals(2, glist.size());
			System.assertEquals('Test Give', glist[0].Title);
		}


		Contact c = testusers.getPortalContact();
		c.MailingState='CA';
		update c;
		c.MA_Latitude__c = 37.776378600000000;
		c.MA_Longitude__c = -122.456878700000000;
		update c;

		System.RunAs(u) {
			cov_user_utility.self.refreshSelf();
			cov_rewards_controller controller = new cov_rewards_controller();
			//List<Give__c> glist = controller.getRewards();
			List<cov_rewards_controller.customReward> glist = controller.getRewards();
			System.assertEquals(4, glist.size());
			System.assertEquals('Test Give 3', glist[0].Title); // lat/lon results first
			System.assertEquals('Test Give 4', glist[1].Title); // then state
			System.assert(glist[2].Title == 'Test Give 2' || glist[2].Title == 'Test Give'); // then national
			System.assertEquals(1, controller.eventRewards.size());
			System.assertEquals('Test Give 2', controller.eventRewards[0].Title);			
			System.assertEquals(3, controller.standardRewards.size());
			System.assertEquals('Test Give 3', controller.standardRewards[0].Title);			



			// Not sure anymore what these functions are for, just testing to get coverage
			controller.g = g;
			System.assertEquals('Test Give', controller.getGive().Name);
			System.assertEquals('Test Give', controller.getGiveList()[0].Name);

			Give_Request__c gr = new Give_Request__c(Applicant__c = u.ContactId, Give_Instance__c = gi.Id,
					Email_Address__c='test@test.iava.org', Address__c='1234 5th St', State__c='NY', Zip_Code__c='10012',
					Primary_Phone__c='212-555-1234', City__c='New York');
			insert gr;
			//System.assertEquals('Test Give', controller.getGiveRequests()[0].Give_Name__c);
			List<cov_rewards_controller.customRewardRequest> rqList = controller.getRewardRequests();
			System.assertEquals('Test Give', rqList[0].giveName);
			System.assertEquals('Tentative confirmation', rqList[0].publicStage);

			gr.Attended__c = 'Yes';
			update gr;
			rqList = controller.getRewardRequests();
			System.assertEquals('Attended', rqList[0].publicStage);

			gr.Attended__c = 'No';
			update gr;
			rqList = controller.getRewardRequests();
			System.assertEquals('Did not attend', rqList[0].publicStage);

			gr.Attended__c = null;
			gr.Stage__c = 'Ineligible';
			update gr;
			rqList = controller.getRewardRequests();
			System.assertEquals('Did not get reward', rqList[0].publicStage);


		}

		// Internal user with no connected contact should only get National and Highlighted gives
		User u2 = testusers.getInternalUser();
		Contact c2 = testusers.getInternalContact();
		c2.Portal_User__c = null;
		update c2;

		System.RunAs(u2) {
			cov_user_utility.self.refreshSelf();
			cov_rewards_controller controller = new cov_rewards_controller();
			List<cov_rewards_controller.customReward> glist = controller.getRewards();
			System.assertEquals(2, glist.size());
			System.assertEquals('Test Give', glist[0].Title);
		}


	}
	
	
}