prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Veteran Member</fullName>
                </value>
                <value>
                    <fullName>Veteran Supporter</fullName>
                </value>
                <value>
                    <fullName>Civilian Supporter</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</description>
        <inlineHelpText>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</inlineHelpText>
        <label>City, ST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maximum_Units_per_Member__c</fullName>
        <description>If greater than 1 and &quot;Member Cannot Select Quantity&quot; is unchecked, member can choose desired quantity of units up to this maximum,  If blank, quantity is unlimited.</description>
        <inlineHelpText>If greater than 1 and &quot;Member Cannot Select Quantity&quot; is unchecked, member can choose desired quantity of units up to this maximum,  If blank, quantity is unlimited.</inlineHelpText>
        <label>Maximum Units per Member</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>National_Give__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overides zip codes and states.</description>
        <inlineHelpText>Overrides zip codes and states.</inlineHelpText>
        <label>National Give</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <label>Num. Units</label>
        <summarizedField>Give_Instance__c.Number_of_Units__c</summarizedField>
        <summaryForeignKey>Give_Instance__c.Give__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</description>
        <inlineHelpText>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</inlineHelpText>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed Visible</fullName>
                </value>
                <value>
                    <fullName>Closed Invisible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Come First Served</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Screened Give</fullName>
                </value>
                <value>
                    <fullName>Unlimited Give</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Waitlist__c</fullName>
        <description>Dependent on “First Come First Served” type. This determines whether event should allow waitlist signups.</description>
        <inlineHelpText>Dependent on “First Come First Served” type. This determines whether event should allow waitlist signups.</inlineHelpText>
        <label>Waitlist?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>No Waitlist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <description>Quantity of give items available.</description>
        <inlineHelpText>Quantity of give items available.</inlineHelpText>
        <label>Num. Units</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Request__c.object
<CustomObject>
    <description>Connects applicants to give</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Street Address</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <description>Should be a confirmed member veteran only.</description>
        <inlineHelpText>Should be a confirmed member veteran only.</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Give_Instance__c</fullName>
        <label>Give Instance</label>
        <referenceTo>Give_Instance__c</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Units_Requested__c</fullName>
        <label>Units Requested</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Give Request</label>
    <nameField>
        <displayFormat>GR-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Give Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/dc_Rucksack_bizlogic_Tests.cls
@isTest
private class dc_Rucksack_bizlogic_Tests {

 static testMethod void FCFS_tests() {
            
            
            Partnership_Request__c p1 = new Partnership_Request__c (Name = 'p1', Public_Partner_Name__c = 'p1');
            insert p1;
            
            Give__c g1 = new Give__c(
                  Name='g1',
                  Partnership_Request__c = p1.id,
                  Type__c = 'First Come First Served',
                  Waitlist__c = 'Waitlist',
                  Status__c = 'Open',
                  Maximum_Units_per_Member__c = 2,
                  National_Give__c = true             
            );
            insert g1;
            
            Give_Instance__c i1 = new Give_Instance__c(
                  Give__c = g1.id,
                  Number_of_Units__c = 2
            );
            insert i1;
            
            Contact c1 = new Contact(LastName='c1');
            Contact c2 = new Contact(LastName='c2');
            Contact c3 = new Contact(LastName='c3');
            Contact c4 = new Contact(LastName='c4');
            Contact c5 = new Contact(LastName='c5');
            Contact c6 = new Contact(LastName='c6');
            insert new List<Contact>{c1, c2, c3, c4, c5, c6};
 

            
            Give_Request__c r1 = new Give_Request__c(
                  Applicant__c = c1.id,
                  Give_Instance__c = i1.id,
                  Units_Requested__c = 2,
                  Email_Address__c = 'samdorman+rucksackunittest@gmail.com',
                  Primary_Phone__c = '555-555-5123',
                  Address__c = '12345 Street St',
                  City__c = 'New York',
                  State__c = 'NY',
                  Zip_Code__c = '10001'
            );
            insert r1;
            
            // Test that a first-come request for a give with space will go to Tentative Conf status
            System.assertEquals('Tentative confirmation',[select Stage__c from Give_Request__c where Applicant__c=:c1.id].Stage__c);
            
            
            
            Give_Request__c r2 = new Give_Request__c(
                  Applicant__c = c2.id,
                  Give_Instance__c = i1.id,
                  Units_Requested__c = 2,
                  Email_Address__c = 'samdorman+rucksackunittest@gmail.com',
                  Primary_Phone__c = '555-555-5123',
                  Address__c = '12345 Street St',
                  City__c = 'New York',
                  State__c = 'NY',
                  Zip_Code__c = '10001'
            );
            insert r2;
            
            // Test that a first-come request for a give with waitlist and no space will go to Wait-list status
            System.assertEquals('Wait-list',[select Stage__c from Give_Request__c where Applicant__c=:c2.id].Stage__c);
            
            
            g1.Type__c = 'Screened Give';
            update g1;
            
            
            Give_Request__c r3 = new Give_Request__c(
                  Applicant__c = c3.id,
                  Give_Instance__c = i1.id,
                  Units_Requested__c = 2,
                  Email_Address__c = 'samdorman+rucksackunittest@gmail.com',
                  Primary_Phone__c = '555-555-5123',
                  Address__c = '12345 Street St',
                  City__c = 'New York',
                  State__c = 'NY',
                  Zip_Code__c = '10001'
            );
            insert r3;
            
            // Test that a premium reward request for a give will stay in Give Requested status
            System.assertEquals('Give requested',[select Stage__c from Give_Request__c where Applicant__c=:c3.id].Stage__c);
            
            
            i1.Number_of_Units__c = null;
            update i1;
            
            
            Give_Request__c r4 = new Give_Request__c(
                  Applicant__c = c4.id,
                  Give_Instance__c = i1.id,
                  Units_Requested__c = 2,
                  Email_Address__c = 'samdorman+rucksackunittest@gmail.com',
                  Primary_Phone__c = '555-555-5123',
                  Address__c = '12345 Street St',
                  City__c = 'New York',
                  State__c = 'NY',
                  Zip_Code__c = '10001'
            );
            insert r4;
            
            // Test that a give request is still created even if the Give Instance doesn't have a number of units specified.
            System.assertEquals('Give requested',[select Stage__c from Give_Request__c where Applicant__c=:c4.id].Stage__c);
            
            g1.Type__c = 'Unlimited Give';
            update g1;
            
            
            Give_Request__c r5 = new Give_Request__c(
                  Applicant__c = c5.id,
                  Give_Instance__c = i1.id,
                  Units_Requested__c = 2,
                  Email_Address__c = 'samdorman+rucksackunittest@gmail.com',
                  Primary_Phone__c = '555-555-5123',
                  Address__c = '12345 Street St',
                  City__c = 'New York',
                  State__c = 'NY',
                  Zip_Code__c = '10001'
            );
            insert r5;
            
            // Test that a unlimited reward request for a give will go to Final confirmation status
            System.assertEquals('Final confirmation',[select Stage__c from Give_Request__c where Applicant__c=:c5.id].Stage__c);


            g1.Type__c = 'Information';
            g1.Fulfillment_Instructions_rtf__c = 'Instructions';
            update g1;
            
            
            Give_Request__c r6 = new Give_Request__c(
                  Applicant__c = c6.id,
                  Give_Instance__c = i1.id,
                  Units_Requested__c = 2,
                  Email_Address__c = 'samdorman+rucksackunittest@gmail.com',
                  Primary_Phone__c = '555-555-5123',
                  Address__c = '12345 Street St',
                  City__c = 'New York',
                  State__c = 'NY',
                  Zip_Code__c = '10001'
            );
            insert r6;
            
            // Test that a information reward request for a give will go to Information sent status
            System.assertEquals('Information sent',[select Stage__c from Give_Request__c where Applicant__c=:c6.id].Stage__c);

            
            
    }
}