prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Member_Categories__c</fullName>
        <description>Semi-colon-separated list of all member categories that apply (Confirmed;Unconfirmed;OtherEra;Family)</description>
        <formula>if ( Veteran_Member_Status__c = &quot;Confirmed&quot;, &quot;Confirmed&quot;, 
  if( CONTAINS(Veteran_Member_Status__c, &quot;Unconfirmed&quot;), &quot;Unconfirmed&quot;, &quot;&quot;)
)
&amp; &quot;;&quot; &amp;
if ( Veteran_of_Other_Era__c , &quot;OtherEra&quot;, &quot;&quot;)
&amp; &quot;;&quot; &amp;
if (  Veteran_Family_Member__c , &quot;Family&quot;, &quot;&quot;)
&amp; &quot;;&quot; &amp;
if ( Not_a_Veteran__c, &quot;Non-veteran&quot;,&quot;&quot;)
&amp; &quot;;&quot; &amp; &quot;Everyone&quot;</formula>
        <inlineHelpText>Semi-colon-separated list of all member categories that apply (Confirmed;Unconfirmed;OtherEra;Family)</inlineHelpText>
        <label>Member Categories</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/IAVA_switches__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Controls to turn pieces of code on and off without having to redeploy</description>
    <fields>
        <fullName>Disable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disable the feature if this box is checked</description>
        <inlineHelpText>Disable the feature if this box is checked</inlineHelpText>
        <label>Disable</label>
        <type>Checkbox</type>
    </fields>
    <label>IAVA switches</label>
</CustomObject>

prodMetadata/src/classes/cov_redirect_controller.cls
public with sharing class cov_redirect_controller {
	public cov_redirect_controller() {
		
	}

	public PageReference init_dashboard() {
		if (UserInfo.getUserType() ==  'Standard') {
			return null;
		}

		IAVA_switches__c sw_disable_dashbord_redirect = IAVA_switches__c.getInstance('myIAVA_dashboard_redirect');
        Boolean redirectFromDashboard = sw_disable_dashbord_redirect == null || !sw_disable_dashbord_redirect.Disable__c ? true : false;

        if (redirectFromDashboard) {
			Contact c = cov_user_utility.self.getC();
			String memberCategories = c == null ? null : c.Member_Categories__c;
			Set<String> memberCats = memberCategories == null ? null : new Set<String>(memberCategories.split(';'));
			if (memberCats.contains('Confirmed') || memberCats.contains('Unconfirmed') || memberCats.contains('OtherEra')) {
				return null;
			} else {
				system.debug('Not authorized for dashboard, send instead to events page. member categories: ' + memberCategories);
				return Page.cov_events_central;
			}
		} else {
			return null;
		}
	}

	public String getEventsCentralPage() {
		if (cov_user_utility.self.isMobile()) {
			return 'cov_events_central_mobile';
		} else {
			return 'cov_events_central_full';			
		}
	}



}