prodMetadata/src/objects/Contact_PolRec_junction__c.object
<CustomObject>
    <description>Junction object to connect Policy Recommendation records and Contact records.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The Policy Priority is related to which Contact?</description>
        <inlineHelpText>The Policy Priority is related to which Contact?</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contacts_related_to_PP</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Policy_Rec__c</fullName>
        <description>Link the contact to which Policy Recommendation record?</description>
        <inlineHelpText>Link the contact to which Policy Recommendation record?</inlineHelpText>
        <label>Policy Recommendation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Policy_Rec__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Policy_Rec__c</referenceTo>
        <relationshipLabel>Contacts related to this Recommendation</relationshipLabel>
        <relationshipName>Pol_Rec_related_to_Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact related to Policy Rec</label>
    <nameField>
        <displayFormat>PR-Cont-{000000}</displayFormat>
        <label>PolRec Contact Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts related to Policy Rec</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Contact_related_to_Focus__c.object
<CustomObject>
    <description>junction object for many-to-many relationship between Contacts and Focus Areas</description>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <description>The Contact related to the Focus Area</description>
        <inlineHelpText>The Contact related to the Focus Area</inlineHelpText>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Focus Areas related to this Contact</relationshipLabel>
        <relationshipName>Contact_rel_to_Focus</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Focus_Area__c</fullName>
        <description>The Focus Area related to the Contact</description>
        <inlineHelpText>The Focus Area related to the Contact</inlineHelpText>
        <label>Related Focus Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Focus_Area__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Focus_Area__c</referenceTo>
        <relationshipLabel>Contacts related to this Focus Area</relationshipLabel>
        <relationshipName>Focus_related_to_Contact</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact related to Focus Area</label>
    <nameField>
        <displayFormat>Cn-Foc-{00000}</displayFormat>
        <label>Contact-Focus ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts related to Focus Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/DC_Event__c.object
<CustomObject>
    <description>DC events such as congressional testimonies</description>
    <label>DC Event</label>
    <nameField>
        <label>DC Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DC Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Focus_Area__c.object
<CustomObject>
    <description>A Focus Area is either a Policy Issue (Employment) or an IAVA Campaign (Combat to Careers)</description>
    <label>Focus Area</label>
    <nameField>
        <label>Focus Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Focus Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Focus_related_to_DC_Event__c.object
<CustomObject>
    <description>Junction objects to create many-to-many relationship between Focus Areas and DC Events</description>
    <fields>
        <fullName>Related_DC_Event__c</fullName>
        <description>The DC Event related to the Focus Area</description>
        <inlineHelpText>The DC Event related to the Focus Area</inlineHelpText>
        <label>Related DC Event</label>
        <referenceTo>DC_Event__c</referenceTo>
        <relationshipLabel>Focus Areas related to this DC Event</relationshipLabel>
        <relationshipName>DC_Event_rel_to_Focus</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Focus_Area__c</fullName>
        <description>The Focus Area related to the DC Event</description>
        <inlineHelpText>The Focus Area related to the DC Event</inlineHelpText>
        <label>Related Focus Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Focus_Area__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Focus_Area__c</referenceTo>
        <relationshipLabel>DC Events related to this Focus Area</relationshipLabel>
        <relationshipName>Focus_rel_to_DCEvent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Focus Area related to DC Event</label>
    <nameField>
        <displayFormat>Foc-DCE-{00000}</displayFormat>
        <label>Focus-DCev-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Focus Areas related to DC Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Focus_related_to_Legislation__c.object
<CustomObject>
    <description>junction object to establish many-to-many relationship between Focus Areas and Legislation</description>
    <fields>
        <fullName>Related_Focus_Area__c</fullName>
        <description>The Focus Area related to the Legislation</description>
        <inlineHelpText>The Focus Area related to the Legislation</inlineHelpText>
        <label>Related Focus Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Focus_Area__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Focus_Area__c</referenceTo>
        <relationshipLabel>Legislation related to this Focus Area</relationshipLabel>
        <relationshipName>Focus_rel_to_Leg</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Legislation__c</fullName>
        <description>The Legislation related to the Focus Area</description>
        <inlineHelpText>The Legislation related to the Focus Area</inlineHelpText>
        <label>Related Legislation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Legislation__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Legislation__c</referenceTo>
        <relationshipLabel>Focus Areas related to this Legislation</relationshipLabel>
        <relationshipName>Leg_rel_to_Focus</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Focus Area related to Legislation</label>
    <nameField>
        <displayFormat>Foc-Leg-{00000}</displayFormat>
        <label>Focus-Leg-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Focus Areas related to Legislation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Legislation__c.object
<CustomObject>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <description>Just the numerical part of the bill or amendment number.</description>
        <inlineHelpText>Just the numerical part of the bill or amendment number.</inlineHelpText>
        <label>Bill Number</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bill_Prefix__c</fullName>
        <description>Bill prefix corresponding to bill title, e.g. &quot;HR&quot; for HR1212</description>
        <inlineHelpText>Bill prefix corresponding to bill title, e.g. &quot;HR&quot; for HR1212</inlineHelpText>
        <label>Bill Prefix</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>HRES</fullName>
                </value>
                <value>
                    <fullName>HJRES</fullName>
                </value>
                <value>
                    <fullName>HCRES</fullName>
                </value>
                <value>
                    <fullName>SRES</fullName>
                </value>
                <value>
                    <fullName>SJRES</fullName>
                </value>
                <value>
                    <fullName>SCRES</fullName>
                </value>
                <value>
                    <fullName>HAMDT</fullName>
                </value>
                <value>
                    <fullName>SAMDT</fullName>
                </value>
                <value>
                    <fullName>IAVA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Legislation</label>
    <nameField>
        <label>Bill ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legislation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/P_Rec_DC_Event_junction__c.object
<CustomObject>
    <description>Junction object to establish many-to-many relationship between Policy Recommendations and DC Events (testimonies).</description>
    <fields>
        <fullName>DC_Event__c</fullName>
        <description>Select the DC Event that covered the Policy Recommendation</description>
        <inlineHelpText>Select the DC Event that covered the Policy Recommendation</inlineHelpText>
        <label>Related DC Event</label>
        <referenceTo>DC_Event__c</referenceTo>
        <relationshipLabel>Policy Recommendations related to this DC Event</relationshipLabel>
        <relationshipName>PolRecs_related_to_DC_Event</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Policy_Rec__c</fullName>
        <description>Select a Policy Recommendation that was covered by the DC Event</description>
        <inlineHelpText>Select a Policy Recommendation that was covered by the DC Event</inlineHelpText>
        <label>Related Policy Recommendation</label>
        <referenceTo>Policy_Rec__c</referenceTo>
        <relationshipLabel>DC Events related to this Policy Recommendation</relationshipLabel>
        <relationshipName>DC_Events_related_to_PolRec</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>P-Rec related to DC Event</label>
    <nameField>
        <displayFormat>PR-DC-{000000}</displayFormat>
        <label>PRec-DCEvent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P-Recs related to DC Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Policy_Rec__c.object
<CustomObject>
    <description>Policy Recommendations</description>
    <fields>
        <fullName>Meta_Focus_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meta Policy Issue</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Focus_Area__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Focus_Area__c</referenceTo>
        <relationshipLabel>Policy Recommendations</relationshipLabel>
        <relationshipName>Policy_Recommendations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Policy Recommendation</label>
    <nameField>
        <label>Policy Rec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/PRec_Leg_junction__c.object
<CustomObject>
    <description>Junction object to establish many-to-many relationship between Policy Recommendations and Legislation (bills).</description>
    <fields>
        <fullName>Legislation__c</fullName>
        <label>Related Legislation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Legislation__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Legislation__c</referenceTo>
        <relationshipLabel>Recommendations related to this Leg</relationshipLabel>
        <relationshipName>PolRec_covered_by_Legislation</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Policy_Rec__c</fullName>
        <label>Related Policy Recommendation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Policy_Rec__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Policy_Rec__c</referenceTo>
        <relationshipLabel>Legislation related to this Recommendation</relationshipLabel>
        <relationshipName>PolRec_covered_in_Leg</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>P-Rec/Leg relationship</label>
    <nameField>
        <displayFormat>PR-Leg-{000000}</displayFormat>
        <label>PolRec-Leg ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>P-Rec/Leg relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/FocusAreaRelatedObjectsManager.cls
public with sharing class FocusAreaRelatedObjectsManager {
// Developed by Richard Saunders, Exponent Partners for IAVA, 2011
// Class to create the related junction objects for focus areas
// This class is called from the triggers for the respective junction objects

	public static void createFocusToLegJunction(Id prid, Id legid){
		
		if (prid != null && legid != null) {
			Policy_Rec__c pr;
			
			try {
				pr = [select id, Meta_Focus_Area__c from Policy_Rec__c where id=:prid limit 1];
			} catch (DmlException e) {
				system.debug('Error querying focus area: '+e);
				return;
			}
			
			if (pr.Meta_Focus_Area__c != null) {
				// Only create the junction if a relationship doesn't already exist
				Focus_related_to_Legislation__c existing;
				try {
					existing = [select id from Focus_related_to_Legislation__c 
								where Related_Focus_Area__c =: pr.Meta_Focus_Area__c 
								and Related_Legislation__c =: legid 
								limit 1];
				} catch (QueryException e) {
					system.debug('No relationship appears to exist: ' + e);	
				}
				
				if (existing == null) {
					Focus_related_to_Legislation__c fl = new Focus_related_to_Legislation__c (
						Related_Focus_Area__c = pr.Meta_Focus_Area__c,
						Related_Legislation__c = legid	
					);
					insert fl;
				}
			}
		}
	}
	
	public static void createFocusToDCEventJunction(Id prid, Id dcid){
		
		if (prid != null && dcid != null) {
			Policy_Rec__c pr;
			
			try {
				pr = [select id, Meta_Focus_Area__c from Policy_Rec__c where id=:prid limit 1];
			} catch (DmlException e) {
				system.debug('Error querying focus area: '+e);
				return;
			}
			
			if (pr.Meta_Focus_Area__c != null) {
				// Only create the junction if a relationship doesn't already exist
				Focus_related_to_DC_Event__c existing;
				try {
					existing = [select id from Focus_related_to_DC_Event__c 
								where Related_Focus_Area__c =: pr.Meta_Focus_Area__c
								and Related_DC_Event__c =: dcid	
								limit 1];
				} catch (QueryException e) {
					system.debug('No relationship appears to exist: ' + e);	
				}
				
				if (existing == null) {
					Focus_related_to_DC_Event__c fdc = new Focus_related_to_DC_Event__c (
						Related_Focus_Area__c = pr.Meta_Focus_Area__c,
						Related_DC_Event__c = dcid	
					);
					insert fdc;
				}
			}
		}
	}
	
	public static void createFocusToContactJunction(Id prid, Id cid){
		
		if (prid != null && cid != null) {
			Policy_Rec__c pr;
			
			try {
				pr = [select id, Meta_Focus_Area__c from Policy_Rec__c where id=:prid limit 1];
			} catch (DmlException e) {
				system.debug('Error querying focus area: '+e);
				return;
			}
			
			if (pr.Meta_Focus_Area__c != null) {
				// Only create the junction if a relationship doesn't already exist
				Contact_related_to_Focus__c existing;
				try {
					existing = [select id from Contact_related_to_Focus__c 
								where Related_Focus_Area__c =: pr.Meta_Focus_Area__c
								and Related_Contact__c =: cid
								limit 1];
				} catch (QueryException e) {
					system.debug('No relationship appears to exist: ' + e);	
				}
				
				if (existing == null) {
					Contact_related_to_Focus__c fdc = new Contact_related_to_Focus__c (
						Related_Focus_Area__c = pr.Meta_Focus_Area__c,
						Related_Contact__c = cid	
					);
					insert fdc;
				}
			}
		}
	}
	

	
	// Tests
	
	static testMethod void policyRecJunctionsUnitTest() {
    // Test to verify the P_Rec_DC_Event_junction__c, PRec_Leg_junction__c, and Contact_PolRec_junction__c triggers
    
    	Focus_Area__c fa = new Focus_Area__c(Name='test focus area');
    	insert fa;
    	
        Policy_Rec__c pr = new Policy_Rec__c(Name= 'test policy rec', Meta_Focus_Area__c = fa.id);
        insert pr;
        
        Legislation__c leg = new Legislation__c(Name = 'test leg', Bill_Number__c = decimal.valueOf(1), Bill_Prefix__c='bill');
        insert leg;
        
        PRec_Leg_junction__c prleg = new PRec_Leg_junction__c(Policy_Rec__c = pr.id, Legislation__c = leg.id);
        PRec_Leg_junction__c prleg2 = new PRec_Leg_junction__c(Policy_Rec__c = pr.id, Legislation__c = leg.id);
        insert prleg;
        insert prleg2; // test to make sure we do not create multiple 
        
        DC_Event__c dc = new DC_Event__c(Name = 'test dc event');
        insert dc;
        
        P_Rec_DC_Event_junction__c prdce = new P_Rec_DC_Event_junction__c(Policy_Rec__c = pr.id, DC_Event__c = dc.id);
        P_Rec_DC_Event_junction__c prdce2 = new P_Rec_DC_Event_junction__c(Policy_Rec__c = pr.id, DC_Event__c = dc.id);
        insert prdce;
        insert prdce2;
        
        Contact con = new Contact(FirstName='fname', LastName='lname');
        insert con;
        
        Contact_PolRec_junction__c cpr = new Contact_PolRec_junction__c(Policy_Rec__c = pr.id, Contact__c = con.id);
        Contact_PolRec_junction__c cpr2 = new Contact_PolRec_junction__c(Policy_Rec__c = pr.id, Contact__c = con.id);
        insert cpr; 
        insert cpr2;
        
        // verify that related records were created on the Focus Area
        List<Focus_related_to_Legislation__c> flegs = [select id, Related_Legislation__c from Focus_related_to_Legislation__c where Related_Focus_Area__c =:fa.id];
        system.assertEquals(1, flegs.size());
        system.assertEquals(leg.id, flegs[0].Related_Legislation__c);
        
        List<Focus_related_to_DC_Event__c> fdces = [select id, Related_DC_Event__c from Focus_related_to_DC_Event__c where Related_Focus_Area__c =:fa.id]; 
        system.assertEquals(1, fdces.size());
        system.assertEquals(dc.id, fdces[0].Related_DC_Event__c);
        
        List<Contact_related_to_Focus__c> fcons = [select id, Related_Contact__c from Contact_related_to_Focus__c where Related_Focus_Area__c =: fa.id];
        system.assertEquals(1, fcons.size());
        system.assertEquals(con.id, fcons[0].Related_Contact__c);
        
    }
}