prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>IF(NOT(ISBLANK(Birthdate)),FLOOR((TODAY()-Birthdate)/365.2425),IF(NOT(ISBLANK(Age_Number__c)),Age_Number__c,null))</formula>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Date__c</fullName>
        <description>This is the date that a Member Veteran was approved for membership.</description>
        <label>Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currently Serving</fullName>
                </value>
                <value>
                    <fullName>Separated/Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Drivers_License__c</fullName>
        <description>Contacts drivers license</description>
        <inlineHelpText>Contacts drivers license</inlineHelpText>
        <label>Drivers License #</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>LastName  &amp; &quot;, &quot;  &amp;   FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name Last First</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Gender Variant/Nonconforming</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Transgender Female</fullName>
                </value>
                <value>
                    <fullName>Transgender Male</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IAVA_Board_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IAVA Board Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Categories__c</fullName>
        <description>Semi-colon-separated list of all member categories that apply (Confirmed;Unconfirmed;OtherEra;Family)</description>
        <formula>if ( Veteran_Member_Status__c = &quot;Confirmed&quot;, &quot;Confirmed&quot;, 
  if( CONTAINS(Veteran_Member_Status__c, &quot;Unconfirmed&quot;), &quot;Unconfirmed&quot;, &quot;&quot;)
)
&amp; &quot;;&quot; &amp;
if ( Veteran_of_Other_Era__c , &quot;OtherEra&quot;, &quot;&quot;)
&amp; &quot;;&quot; &amp;
if (  Veteran_Family_Member__c , &quot;Family&quot;, &quot;&quot;)
&amp; &quot;;&quot; &amp;
if ( Not_a_Veteran__c, &quot;Non-veteran&quot;,&quot;&quot;)
&amp; &quot;;&quot; &amp; &quot;Everyone&quot;</formula>
        <inlineHelpText>Semi-colon-separated list of all member categories that apply (Confirmed;Unconfirmed;OtherEra;Family)</inlineHelpText>
        <label>Member Categories</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_ID__c</fullName>
        <externalId>true</externalId>
        <label>Membership ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Shirt_size__c</fullName>
        <description>Stores the Contact’s shirt size.</description>
        <inlineHelpText>Stores the Contact’s shirt size.</inlineHelpText>
        <label>Shirt size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adult – Small (S)</fullName>
                </value>
                <value>
                    <fullName>Adult – Medium (M)</fullName>
                </value>
                <value>
                    <fullName>Adult – Large (L)</fullName>
                </value>
                <value>
                    <fullName>Adult – Extra Large (XL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Veteran_Member_Status__c</fullName>
        <description>Confirmed if Veteran Member is checked and Paperwork Status is Paperwork Accepted. Unconfirmed if Veteran Member checked but Paperwork not accepted. Blank if Veteran Member not checked.</description>
        <formula>IF( Veteran_Member__c, 
  if(
    OR(
      ispickval(Paperwork_Confirmation__c,&quot;Paperwork Accepted&quot;
      ), 
        Peer_Validated__c 
    ),
    &quot;Confirmed&quot;,
    if(
       or( 
         HasOptedOutOfEmail,isblank( Email )             
       ), 
       &quot;Disconnected&quot;,
       &quot;Unconfirmed&quot;
    )
  )
,&quot;&quot;)</formula>
        <inlineHelpText>Confirmed, Unconfirmed, Disconnected (unconfirmed with Email Opt Out or blank email).  Or blank if not a vet member.</inlineHelpText>
        <label>Veteran Member Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>npe01__AlternateEmail__c</fullName>
        <description>Alternate Email is an optional fourth email: Not personal, preferred, or work email.</description>
        <label>Alternate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>npe01__HomeEmail__c</fullName>
        <description>See Preferred Email field.</description>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>npe01__WorkEmail__c</fullName>
        <description>See Preferred Email field.</description>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>Available_To__c</fullName>
        <description>Which Membership Categories on the contact are eligible for this reward?</description>
        <inlineHelpText>Which Membership Categories on the contact are eligible for this reward?</inlineHelpText>
        <label>Available To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Everyone</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Other Era</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Guest_DL_Num__c</fullName>
        <description>This field will be used to indicate if the guest Drivers License number is to be collected.</description>
        <inlineHelpText>Indicate if the guest Drivers License number is to be collected.</inlineHelpText>
        <label>Collect Guest DL Num</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Guest_DOB__c</fullName>
        <description>This field will be used to indicate if the member DOB is to be collected.</description>
        <inlineHelpText>Indicate if the member DOB is to be collected.</inlineHelpText>
        <label>Collect Guest DOB</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Guest_Name__c</fullName>
        <label>Collect Guest Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don&apos;t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Guest_Shirt_Size__c</fullName>
        <description>This field will be used to indicate if the guest shirt size is to be collected.</description>
        <inlineHelpText>Indicate if the guest shirt size is to be collected.</inlineHelpText>
        <label>Collect Guest Shirt Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Member_DL_Num__c</fullName>
        <description>This field will be used to indicate if the guest Drivers License number is to be collected.</description>
        <inlineHelpText>Indicate if the guest Drivers License number is to be collected.</inlineHelpText>
        <label>Collect Member DL Num</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Member_DOB__c</fullName>
        <description>This field will be used to indicate if the member DOB is to be collected.</description>
        <inlineHelpText>Indicate if the member DOB is to be collected.</inlineHelpText>
        <label>Collect Member DOB</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Member_Shirt_Size__c</fullName>
        <description>This field will be used to indicate if the guest shirt size is to be collected.</description>
        <inlineHelpText>Indicate if the guest shirt size is to be collected.</inlineHelpText>
        <label>Collect Member Shirt Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Must_be_21__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Requires member verifies 21+ age during Give Request.</description>
        <inlineHelpText>Requires member verifies 21+ age during Give Request.</inlineHelpText>
        <label>Must be 21+</label>
        <type>Checkbox</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Request__c.object
<CustomObject>
    <description>Connects applicants to give</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <description>Should be a confirmed member veteran only.</description>
        <inlineHelpText>Should be a confirmed member veteran only.</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Give_Instance__c</fullName>
        <label>Give Instance</label>
        <referenceTo>Give_Instance__c</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Give Request</label>
    <nameField>
        <displayFormat>GR-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Give Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/test_dc_ctrl_requestreward.cls
@isTest
private class test_dc_ctrl_requestreward {

    static testMethod void testController() {       
        Give__c give = test_Utilities.createSimpleGive();
        give.Available_To__c = 'Confirmed;Unconfirmed';
        update give;
        
        Give_Instance__c instance = test_Utilities.createSimpleGiveInstance(give);
                
        Contact con = test_Utilities.createSimpleContact('last', 'test@test.iava.org', '12345');
        

        User guestUser = cov_user_TEST_utility.getGuestUser();

        Test.startTest();
        
        System.RunAs(guestUser) {
        
            PageReference pageRef = Page.cov_reward;
            Test.setCurrentPageReference(pageRef);
            ApexPages.currentPage().getParameters().put('giveid', give.id);          
            
            dc_ctrl_requestreward controller = new dc_ctrl_requestreward();

            // not available to guest 
            controller.ticketValue = 2;
            controller.init();
            system.assertEquals(false, controller.eligibleForReward);
        }

        give.Available_To__c = 'Everyone';
        update give;

        System.RunAs(guestUser) {
        
            PageReference pageRef = Page.cov_reward;
            Test.setCurrentPageReference(pageRef);
            ApexPages.currentPage().getParameters().put('giveid', give.id);
            
            dc_ctrl_requestreward controller = new dc_ctrl_requestreward();

            // SD - now available for guest claim
            controller.ticketValue = 2;
            controller.init();
            system.assertEquals(true, controller.eligibleForReward);
            controller.first_name = 'Fred';
            controller.last_name = 'Farfel';
            controller.ContactEmail = 'fredfarfel@test.iava.org';
            List<SelectOption> options = controller.getconfirmItems();
            controller.submitrequest();
        }

        // check that contact was added
        system.assertEquals(1, [select Id from Contact where Email = 'fredfarfel@test.iava.org'].size());
        Set<String> emails = new Set<String>{'fredfarfel@test.iava.org'};
        system.debug('emails set in test: ' + emails);
        List<Contact> testCs = [select Id, FirstName, LastName, Email, Member_Categories__c, Shirt_size__c, Drivers_License__c, MailingCountry, MailingCity, MailingState, MailingPostalCode, IAVA_Board_Member__c, HomePhone, Gender__c, Full_Name__c, Description, Department, Current_Status__c, Birthdate, Approved_Date__c, Age__c, AccountId, Membership_ID__c, MailingStreet, OtherPhone, Phone, Veteran_Member_Status__c from Contact where Email in :emails or npe01__AlternateEmail__c in :emails or npe01__HomeEmail__c in :emails or npe01__WorkEmail__c in :emails ORDER BY Veteran_Member_Status__c ASC NULLS LAST];
        system.debug('testCs: ' + testCs);
        // check that give request was created
        system.assertEquals(1, [select Id from Give_Request__c where Give_Instance__r.Give__c = :give.id and Applicant__r.Email = 'fredfarfel@test.iava.org'].size());
        

        // now check can also do guest claim for existing contact

        // check that contact exists
        system.assertEquals(1, [select Id from Contact where Email = 'test@test.iava.org'].size());

        System.RunAs(guestUser) {
        
            PageReference pageRef = Page.cov_reward;
            Test.setCurrentPageReference(pageRef);
            ApexPages.currentPage().getParameters().put('giveid', give.id);          
            
            dc_ctrl_requestreward controller = new dc_ctrl_requestreward();

            // guest claim with existing user email
            controller.ticketValue = 2;
            controller.init();
            system.assertEquals(true, controller.eligibleForReward);
            controller.first_name = 'first';
            controller.last_name = 'last';
            controller.ContactEmail = 'test@test.iava.org';
            List<SelectOption> options = controller.getconfirmItems();
            controller.submitrequest();
        }

        // check that only one contact still exists
        system.assertEquals(1, [select Id from Contact where Email = 'test@test.iava.org'].size());
        // check that give request was created
        //temporarily commenting out - guest user cant seem to send VF email to user it doesnt own (or perhaps hasnt just created)
        //system.assertEquals(1, [select Id from Give_Request__c where Give_Instance__r.Give__c = :give.id and Applicant__r.Email = 'test@test.iava.org'].size());






        // just to get coverage of loadsuccessinfo() method
        PageReference pageRef2 = Page.cov_rewardconfirmation;
        Test.setCurrentPageReference(pageRef2);

        PageReference pageRef = Page.cov_reward;
        Test.setCurrentPageReference(pageRef);
        ApexPages.currentPage().getParameters().put('giveid', give.id);


        give.Collect_Guest_Name__c = 'at request';
        give.Collect_Guest_DL_Num__c = 'at request';
        give.Collect_Guest_DOB__c = 'at request';
        give.Collect_Guest_Shirt_Size__c = 'at request';
        give.Collect_Member_DL_Num__c = 'at request';
        give.Collect_Member_DOB__c = 'at request';
        give.Collect_Member_Shirt_Size__c = 'at request';
        
        give.Must_be_21__c = true;
        give.Must_be_21_for_guest__c = true;
        update give;

        dc_ctrl_requestreward controller = new dc_ctrl_requestreward();        

        controller.loadContact(con.Id);
        controller.ticketValue = 2;
        
        controller.init();

        system.assertEquals(true, controller.eligibleForReward);
        
        
        List<SelectOption> options = controller.getconfirmItems();
        controller.submitrequest();
        
        PageReference pr = controller.redirectOnSave();
        Boolean b = controller.getShouldRenderGuests();
        b = controller.getPromptForGuests();
        b = controller.getShouldShowGuestsDivider();
        b = controller.getShowSpecialSectionDivider();
        
        
        //Test.stopTest();






        // SD - add new tests to check that Available To field works

        give.Available_To__c = 'Confirmed';
        update give;

        //Test.startTest();
        controller = new dc_ctrl_requestreward();
        controller.loadContact(con.Id);
        controller.ticketValue = 2;
        controller.init();
        system.assertEquals(true, controller.eligibleForReward);
        //Test.stopTest();

        // set contact to unconfirmed member
        con.Paperwork_Confirmation__c = 'Paperwork Requested';
        update con;

        //Test.startTest();
        controller = new dc_ctrl_requestreward();
        controller.loadContact(con.Id);
        controller.ticketValue = 2;
        controller.init();
        system.assertEquals(false, controller.eligibleForReward);
        //Test.stopTest();

        // Available To null should be the same as Confirmed
        give.Available_To__c = null;
        update give;

        //Test.startTest();
        controller = new dc_ctrl_requestreward();
        controller.loadContact(con.Id);
        controller.ticketValue = 2;
        controller.init();
        system.assertEquals(false, controller.eligibleForReward);
        //Test.stopTest();

        // Available To null should be the same as Confirmed
        give.Available_To__c = 'Everyone;';
        update give;

        //Test.startTest();
        controller = new dc_ctrl_requestreward();
        controller.loadContact(con.Id);
        controller.ticketValue = 2;
        controller.init();
        system.assertEquals(true, controller.eligibleForReward);


        Test.stopTest();


    }
    
	// R51 - allow SF platform users to request reward
	static testMethod void giveRequestByInternalPlatformUser() {
		Give__c give = test_Utilities.createSimpleGive();
		
		Give_Instance__c instance = test_Utilities.createSimpleGiveInstance(give);
		
		Contact con = test_Utilities.createSimpleContact('last', 'test@test.com', '12345');
		con.Portal_User__c = UserInfo.getUserId();
		update con;
		
		Test.setCurrentPageReference(Page.dc_ClaimReward);
		
		ApexPages.currentPage().getParameters().put('giveid', give.id);
		ApexPages.currentPage().getParameters().put('mem-id', con.Membership_ID__c);
		ApexPages.currentPage().getParameters().put('Email', con.Email);
		
		System.runAs([select Id from User where Id = :UserInfo.getUserId()][0]) {
			Test.startTest();
			
			dc_ctrl_requestreward controller = new dc_ctrl_requestreward();
			controller.init();
			
			// Contact related to the current platform User via the Portal_User__c lookup
			System.assertEquals(con.Id, controller.contact.Id);
			
			Test.stopTest();
		}
	}
}