prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Create_Portal_User__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Turning this flag on would trigger creation of a IAVA Plus Portal user for this contact if this is a confirmed IAVA member and no portal user exists for this member.</inlineHelpText>
        <label>Create Portal User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Paperwork_Confirmation_Type__c</fullName>
        <label>Paperwork Confirmation Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Paperwork_Confirmation__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Deployed OEF/OIF/OND</fullName>
                </value>
                <value>
                    <fullName>Deployed Elsewhere post 9/11</fullName>
                </value>
                <value>
                    <fullName>Not Deployed post 9/11</fullName>
                </value>
                <value>
                    <fullName>Pre-9/11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paperwork_Confirmation__c</fullName>
        <label>Paperwork Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paperwork Not Requested Yet</fullName>
                </value>
                <value>
                    <fullName>Paperwork Requested</fullName>
                </value>
                <value>
                    <fullName>Sent First Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Sent Second Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Standard Question/Issue</fullName>
                </value>
                <value>
                    <fullName>Paperwork Received</fullName>
                </value>
                <value>
                    <fullName>Paperwork Accepted</fullName>
                </value>
                <value>
                    <fullName>Paperwork Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Veteran_Member_Status__c</fullName>
        <description>Confirmed if Veteran Member is checked and Paperwork Status is Paperwork Accepted. Unconfirmed if Veteran Member checked but Paperwork not accepted. Blank if Veteran Member not checked.</description>
        <formula>IF( Veteran_Member__c, 
  if(
    OR(
      ispickval(Paperwork_Confirmation__c,&quot;Paperwork Accepted&quot;
      ), 
        Peer_Validated__c 
    ),
    &quot;Confirmed&quot;,
    if(
       or( 
         HasOptedOutOfEmail,isblank( Email )             
       ), 
       &quot;Disconnected&quot;,
       &quot;Unconfirmed&quot;
    )
  )
,&quot;&quot;)</formula>
        <inlineHelpText>Confirmed, Unconfirmed, Disconnected (unconfirmed with Email Opt Out or blank email).  Or blank if not a vet member.</inlineHelpText>
        <label>Veteran Member Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Veteran_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates whether or not a contact is a Veteran Member, confirmed or unconfirmed.  Only membership should modify this field.</description>
        <label>Veteran Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe01__AlternateEmail__c</fullName>
        <description>Alternate Email is an optional fourth email: Not personal, preferred, or work email.</description>
        <label>Alternate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>npe01__HomeEmail__c</fullName>
        <description>See Preferred Email field.</description>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>npe01__WorkEmail__c</fullName>
        <description>See Preferred Email field.</description>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/IAVA_Rewards_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Last_Member_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>AUTOMATICALLY MAINTAINED.  DO NOT UPDATE.
The Last Member ID assigned to a Contact.  Is 8 character string that looks like a number.  First number assigned to any Contact is 15325001.  Is sequential after that.</inlineHelpText>
        <label>Last Member ID</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IAVA Rewards Settings</label>
    <nameField>
        <label>IAVA Rewards Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IAVA Rewards Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/IAVAPlus_ForgotPasswordController.cls
/**
 * An apex page controller that exposes the site forgot password functionality
 */
public class IAVAPlus_ForgotPasswordController {

	public String username { get; set; }
	
	public IAVAPlus_ForgotPasswordController() {}
	
	public PageReference forgotPassword() {
		
		String startUrl = ApexPages.currentPage().getParameters().get('startUrl');
		PageReference pr = Page.IAVAPlus_ForgotPasswordConfirm;
		if (startUrl != '') pr.getParameters().put('startUrl', startUrl);
		pr.setRedirect(true);
		
		// provision license for confirmed member with no IAVAPlus login
		System.debug('username: ' + username);
		if (String.isNotBlank(username)) {
System.debug('1');
			List<User> users = [select Id from User where Username = :username and IsActive = true and isPortalEnabled = true];
System.debug('2');
			if (users.isEmpty()) {		// no IAVAPlus login
System.debug('3');
				try {
System.debug('4');
					Contact c = [select Email, Veteran_Member__c, Veteran_Member_Status__c, Create_Portal_User__c, Account.OwnerId from Contact
						where (Email = :username or npe01__HomeEmail__c = :username or npe01__WorkEmail__c = :username or npe01__AlternateEmail__c = :username)
						order by Veteran_Member_Status__c ASC NULLS LAST
						limit 1];
System.debug('5');
					if (c.Veteran_Member__c == true && c.Veteran_Member_Status__c == 'Confirmed') {		// confirmed member
System.debug('6');
						List<User> accountOwner = [select UserRoleId from User where Id = :c.Account.OwnerId];
						if (!accountOwner.isEmpty() && accountOwner[0].UserRoleId != null) {			// make sure account owner has a role
							if (c.Create_Portal_User__c == true) {		// reset flag to cause license provisioning trigger to fire
								c.Create_Portal_User__c = false;
								update c;
							}
							// provision a portal license
							c.Create_Portal_User__c = true;
							update c;
							
							return pr;
						}
					}
				} catch (Exception e) {
					System.debug('>>>>>>>>>> forgotPassword: ' + e.getMessage());
				}
			}
		}
		
		// go to Site password reset for all other cases:
		//	1) reset password if IAVAPlus login exists
		//	2) standard error handling for
		//		a) no IAVAPlus login, not a confirmed member (with or without contact record)
		//		b) no IAVAPlus login, confirmed member but cannot auto provision license because account owner missing role
		//		c) missing username
		Boolean success = Site.forgotPassword(username);
		
		if (success) {
			return pr;
		} else {
			return null;
		}
	}
	
	/*
	 * tests
	 */
	
	static testMethod void testForgotPasswordController() {
		// Instantiate a new controller with all parameters in the page
		IAVAPlus_ForgotPasswordController controller = new IAVAPlus_ForgotPasswordController();
		controller.username = 'test@salesforce.com';
		
		System.assertEquals(null, controller.forgotPassword()); 
	}
	
	static testMethod void licenseProvisionedForConfirmedMember() {
		IAVA_Rewards_Settings__c irs = new IAVA_Rewards_Settings__c(Name = 'Main', Last_Member_ID__c = '12345678');
		insert irs;
		
		Contact c = new Contact(FirstName = 'Confirmed', LastName = 'Member', Email = 'test@confirmedmember.org', 
								Veteran_Member__c = true, Paperwork_Confirmation__c = 'Paperwork Accepted');
//		c.Paperwork_Confirmation_Type__c = 'Deployed OEF/OIF/OND';
		c.Paperwork_Confirmation_Type__c = 'Dummyvalue'; // not using deployed avoids triggering the workflow which sets Create Portal User and bonks the test
		insert c;
		
		IAVAPlus_ForgotPasswordController controller = new IAVAPlus_ForgotPasswordController();
		controller.username = 'test@confirmedmember.org';
		
		PageReference pr = controller.forgotPassword();
		
		System.assertEquals(Page.IAVAPlus_ForgotPasswordConfirm.getUrl(), pr.getUrl());
		System.assertEquals(true, [select Create_Portal_User__c from Contact where Id = :c.Id].Create_Portal_User__c);
	}
	
	static testMethod void noLicenseProvisionedForUnconfirmedMember() {
		IAVA_Rewards_Settings__c irs = new IAVA_Rewards_Settings__c(Name = 'Main', Last_Member_ID__c = '12345678');
		insert irs;
		
		Contact c = new Contact(FirstName = 'Confirmed', LastName = 'Member', Email = 'test@confirmedmember.org', 
								Veteran_Member__c = true, Paperwork_Confirmation__c = 'Paperwork Requested', Paperwork_Confirmation_Type__c = 'Deployed OEF/OIF/OND');
		insert c;
		
		IAVAPlus_ForgotPasswordController controller = new IAVAPlus_ForgotPasswordController();
		controller.username = 'test@confirmedmember.org';
		
		PageReference pr = controller.forgotPassword();
		
		System.assertEquals(null, pr);
		System.assertEquals(false, [select Create_Portal_User__c from Contact where Id = :c.Id].Create_Portal_User__c);
	}
	
}