prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Drivers_License__c</fullName>
        <description>Contacts drivers license</description>
        <inlineHelpText>Contacts drivers license</inlineHelpText>
        <label>Drivers License #</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_ID__c</fullName>
        <externalId>true</externalId>
        <label>Membership ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Paperwork_Confirmation__c</fullName>
        <label>Paperwork Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paperwork Not Requested Yet</fullName>
                </value>
                <value>
                    <fullName>Paperwork Requested</fullName>
                </value>
                <value>
                    <fullName>Sent First Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Sent Second Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Standard Question/Issue</fullName>
                </value>
                <value>
                    <fullName>Paperwork Received</fullName>
                </value>
                <value>
                    <fullName>Paperwork Accepted</fullName>
                </value>
                <value>
                    <fullName>Paperwork Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shirt_size__c</fullName>
        <description>Stores the Contact’s shirt size.</description>
        <inlineHelpText>Stores the Contact’s shirt size.</inlineHelpText>
        <label>Shirt size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adult – Small (S)</fullName>
                </value>
                <value>
                    <fullName>Adult – Medium (M)</fullName>
                </value>
                <value>
                    <fullName>Adult – Large (L)</fullName>
                </value>
                <value>
                    <fullName>Adult – Extra Large (XL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Veteran_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates whether or not a contact is a Veteran Member, confirmed or unconfirmed.  Only membership should modify this field.</description>
        <label>Veteran Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>npe01__AlternateEmail__c</fullName>
        <description>Alternate Email is an optional fourth email: Not personal, preferred, or work email.</description>
        <label>Alternate Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>npe01__HomeEmail__c</fullName>
        <description>See Preferred Email field.</description>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>npe01__WorkPhone__c</fullName>
        <description>See &apos;Preferred Phone&apos; field.</description>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Registered_Device__c.object
<CustomObject>
    <description>This custom Salesforce object will be used to store information pertaining to mobile devices.</description>
    <fields>
        <fullName>Device_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to store the ID of the Contact to whom this device belongs.</description>
        <label>Device Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Registered Devices</relationshipLabel>
        <relationshipName>Registered_Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Device_Token__c</fullName>
        <description>This field will be used to store the Device Token.  It should be configured as an External ID field that is unique across all records.</description>
        <label>Device Token</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Registered Device</label>
    <nameField>
        <label>Registered Device Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registered Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/ContactUtilities.cls
/*
Copyright (c) 2010 Etherios LLC
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are not permitted.

Author: Nick Koopman, nkoopman@etherios.com
*/
public class ContactUtilities {
	
    public static final String CONFIRMED_VET = 'Paperwork Accepted';

	// Returns the Salesforce ID for a confirmed Member 
	public static ID ConfirmedMemberID(String MemberID, String eMail)
	{
		if ((StringUtilities.ISnullORblank(MemberID)) || (StringUtilities.ISnullORblank(eMail))) return null;
		List<Contact> contacts = new List<Contact>();
		contacts = [SELECT Id FROM Contact WHERE
			((Membership_Id__c = :MemberID) AND
			 (Veteran_Member__c = true) AND
			 (Paperwork_Confirmation__c = :CONFIRMED_VET) AND
			 ((Email = :eMail) OR (npe01__HomeEmail__c = :eMail) OR (npe01__AlternateEmail__c = :eMail))
			)];
		if ((contacts != null) && (contacts.size() == 1))
			return contacts[0].Id;
		return null;
	}

	// Returns true / false indicating if a member is a confirmed member
	/*public static Boolean IsConfirmedMember(String MemberID, String eMail)
	{
		ID id = ConfirmedMemberID(MemberID, eMail);
		if (id != null) return true;
		return false;
	}*/

	// Returns additional information for a confirmed Member
	public static Contact ConfirmedContactInfo(String MemberID, String eMail, String DeviceToken)
	{
		if ((StringUtilities.ISnullORblank(MemberID)) || (StringUtilities.ISnullORblank(eMail))) return null;
		List<Contact> contacts = new List<Contact>();
		contacts = [SELECT Id, Name, Email, npe01__HomeEmail__c, npe01__AlternateEmail__c,
					MailingStreet, MailingCity, MailingState, MailingPostalCode, 
					HomePhone, MobilePhone, npe01__WorkPhone__c, Phone, Drivers_License__c, Shirt_size__c
					FROM Contact WHERE
			((Membership_Id__c = :MemberID) AND
			 (Veteran_Member__c = true) AND
			 (Paperwork_Confirmation__c = :CONFIRMED_VET) AND
			 ((Email = :eMail) OR (npe01__HomeEmail__c = :eMail) OR (npe01__AlternateEmail__c = :eMail))
			)];
			
		if ((contacts != null) && (contacts.size() == 1)){
			Contact c = contacts[0];
			if(DeviceToken != null){
				try {
					Registered_Device__c rD = [SELECT Device_Owner__c FROM Registered_Device__c Where Device_Token__c =: DeviceToken];
					
					rD.Device_Owner__c = c.Id;
					update rD;
				}catch(QueryException e){
					System.debug(e.getMessage());
				}catch(DmlException e){
					System.debug(e.getMessage());
				}
			}
			return c;
		}
		return null;
	}
}