prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Primary_Mailing_List__c</fullName>
        <description>Automatically set in this order of priority: Confirmed Member, Press Contact, DC Contact, Unconfirmed Member, and if none of these are true, Supporter</description>
        <formula>IF( No_Email_Blasts__c  , &quot;Don&apos;t Email Blast&quot; ,
IF( HasOptedOutOfEmail  ,&quot;Opted Out&quot; ,
IF( ISBLANK( Email ) , &quot;No Email&quot; ,
IF(  Veteran_Member_Status__c = &quot;Confirmed&quot;,&quot;Confirmed Member&quot;,
IF( Press_Contact__c ,&quot;Press Contact&quot;,
IF(  not(isblank(kw__KnowWhoId__c))  ,&quot;DC Contact&quot;,
IF( Veteran_Member__c ,  Veteran_Member_Status__c &amp; &quot; Member&quot;,&quot;Supporter&quot;
)))))))</formula>
        <inlineHelpText>Automatically set in this order of priority: Confirmed Member, Press Contact, DC Contact, Unconfirmed Member, and if none of these are true, Supporter</inlineHelpText>
        <label>Contact Primary Mailing List</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Veteran_Member_Status__c</fullName>
        <description>Confirmed if Veteran Member is checked and Paperwork Status is Paperwork Accepted. Unconfirmed if Veteran Member checked but Paperwork not accepted. Blank if Veteran Member not checked.</description>
        <formula>IF( Veteran_Member__c, 
  if(
    OR(
      ispickval(Paperwork_Confirmation__c,&quot;Paperwork Accepted&quot;
      ), 
        Peer_Validated__c 
    ),
    &quot;Confirmed&quot;,
    if(
       or( 
         HasOptedOutOfEmail,isblank( Email )             
       ), 
       &quot;Disconnected&quot;,
       &quot;Unconfirmed&quot;
    )
  )
,&quot;&quot;)</formula>
        <inlineHelpText>Confirmed, Unconfirmed, Disconnected (unconfirmed with Email Opt Out or blank email).  Or blank if not a vet member.</inlineHelpText>
        <label>Veteran Member Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/iava_counts_TESTS.cls
@isTest
private class iava_counts_TESTS {
	
	@isTest static void test_counts() {
		iava_counts_controller controller = new iava_counts_controller();
		system.assertEquals(controller.veteran_count, [SELECT COUNT() FROM Contact WHERE Veteran_Member_Status__c in ('Confirmed', 'Unconfirmed')]);
		system.assertEquals(controller.supporter_count, [SELECT COUNT() FROM Contact WHERE Contact_Primary_Mailing_List__c = 'Supporter']);
	}
		
}