prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Member_Categories__c</fullName>
        <description>Semi-colon-separated list of all member categories that apply (Confirmed;Unconfirmed;OtherEra;Family)</description>
        <formula>if ( Veteran_Member_Status__c = &quot;Confirmed&quot;, &quot;Confirmed&quot;, 
  if( CONTAINS(Veteran_Member_Status__c, &quot;Unconfirmed&quot;), &quot;Unconfirmed&quot;, &quot;&quot;)
)
&amp; &quot;;&quot; &amp;
if ( Veteran_of_Other_Era__c , &quot;OtherEra&quot;, &quot;&quot;)
&amp; &quot;;&quot; &amp;
if (  Veteran_Family_Member__c , &quot;Family&quot;, &quot;&quot;)
&amp; &quot;;&quot; &amp;
if ( Not_a_Veteran__c, &quot;Non-veteran&quot;,&quot;&quot;)
&amp; &quot;;&quot; &amp; &quot;Everyone&quot;</formula>
        <inlineHelpText>Semi-colon-separated list of all member categories that apply (Confirmed;Unconfirmed;OtherEra;Family)</inlineHelpText>
        <label>Member Categories</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paperwork_Confirmation_Type__c</fullName>
        <label>Paperwork Confirmation Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Paperwork_Confirmation__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Deployed OEF/OIF/OND</fullName>
                </value>
                <value>
                    <fullName>Deployed Elsewhere post 9/11</fullName>
                </value>
                <value>
                    <fullName>Not Deployed post 9/11</fullName>
                </value>
                <value>
                    <fullName>Pre-9/11</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paperwork_Confirmation__c</fullName>
        <label>Paperwork Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paperwork Not Requested Yet</fullName>
                </value>
                <value>
                    <fullName>Paperwork Requested</fullName>
                </value>
                <value>
                    <fullName>Sent First Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Sent Second Paperwork Reminder</fullName>
                </value>
                <value>
                    <fullName>Standard Question/Issue</fullName>
                </value>
                <value>
                    <fullName>Paperwork Received</fullName>
                </value>
                <value>
                    <fullName>Paperwork Accepted</fullName>
                </value>
                <value>
                    <fullName>Paperwork Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/COV_Access_Profile_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to control who is able to be automatically switched to the profile that confers COV access</description>
    <fields>
        <fullName>Allow_members_of_Campaign__c</fullName>
        <description>Enter the name or ID of the campaign that contains contacts who are allowed to be automatically switched to the profile that gives them access to COV.</description>
        <inlineHelpText>Enter the name or ID of the campaign that contains contacts who are allowed to be automatically switched to the profile that gives them access to COV.</inlineHelpText>
        <label>Allow members of Campaign(Name or ID)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allowed_relationship_types_to_COVuser__c</fullName>
        <description>Semicolon-separated list of relationship-types to an existing member which would enable member to be given permission set for access to COV.</description>
        <inlineHelpText>Semicolon-separated list of relationship-types to an existing member which would enable member to be given permission set for access to COV.</inlineHelpText>
        <label>Allowed relationship types to COVuser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorized_member_categories__c</fullName>
        <description>Semicolon-separated list of member categories who are allowed to be automatically switched to the profile that gives them access to COV (spelling must match Member Categories formula values on Contact object)</description>
        <inlineHelpText>Semicolon-separated list of member categories who are allowed to be automatically switched to the profile that gives them access to COV (spelling must match Member Categories formula values on Contact object)</inlineHelpText>
        <label>Authorized member categories</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prefix_for_COV_Access_Permission_Sets__c</fullName>
        <defaultValue>&quot;COV Access&quot;</defaultValue>
        <description>Permission sets that grant COV access should all start with the same prefix, e.g. &quot;COV Access - Internal&quot; and &quot;COV Access - Overage High Volume Customer Portal&quot;. In those cases the prefix is &quot;COV Access&quot;.</description>
        <inlineHelpText>Permission sets that grant COV access should all start with the same prefix, e.g. &quot;COV Access - Internal&quot; and &quot;COV Access - Overage High Volume Customer Portal&quot;. In those cases the prefix is &quot;COV Access&quot;.</inlineHelpText>
        <label>Prefix for COV Access Permission Sets</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>COV Access Profile Settings</label>
</CustomObject>

prodMetadata/src/objects/Feedback__c.object
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>F-{0000000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prodMetadata/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Date_of_COV_Terms_and_Conduct_Acceptance__c</fullName>
        <description>Date the user joined COV, thereby accepting any terms and conditions listed on the COV Gateway page.</description>
        <inlineHelpText>Date the user joined COV, thereby accepting any terms and conditions listed on the COV Gateway page.</inlineHelpText>
        <label>Date of COV Terms and Conduct Acceptance</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

prodMetadata/src/classes/cov_gateway_controller_TESTS.cls
@isTest
public class cov_gateway_controller_TESTS {
	

	public static COV_Access_Profile_Settings__c setTheSetting() {
			COV_Access_Profile_Settings__c setting = new COV_Access_Profile_Settings__c(
				Name = 'Test Profile Setting',
				Authorized_member_categories__c = 'Confirmed',
				Prefix_for_COV_Access_Permission_Sets__c = 'COV Access',
				Allowed_relationship_types_to_COVuser__c = 'Decoy; Test Type',
				Allow_members_of_Campaign__c = 'Access Campaign'
				);
			insert setting;	
			return setting;	
	}

	static testMethod void test_gateway() {

		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u1 = testusers.getPortalUser();
		Contact c1 = testusers.getPortalContact();
		Campaign cmp;

		System.runAs(u1) {
			cov_user_utility.self.refreshSelf();
			cov_gateway_controller controller = new cov_gateway_controller();

			System.assertEquals(true, controller.checkIfAlreadyHasPermissionSet());
			System.assertEquals(false, controller.getHasAcceptedAgreement());
			System.assertEquals(false, controller.checkIfAuthorizedToGainAccess());
			System.assertEquals(false, controller.getIsAuthorized());

			//COV_Access_Profile_Settings__c setting = new COV_Access_Profile_Settings__c(
			//	Name = 'Test Profile Setting',
			//	Authorized_member_categories__c = 'Confirmed',
			//	Prefix_for_COV_Access_Permission_Sets__c = 'COV Access',
			//	Allowed_relationship_types_to_COVuser__c = 'Decoy; Test Status',
			//	Allow_members_of_Campaign__c = 'Access Campaign'
			//	);
			//insert setting;

			COV_Access_Profile_Settings__c setting = setTheSetting();

			System.debug('About to run it back');
			c1.Paperwork_Confirmation__c = 'Paperwork Accepted';
			c1.Paperwork_Confirmation_Type__c = 'Deployed OEF/OIF/OND';
			update c1;
			cov_user_utility.self.refreshSelf();
 			controller = new cov_gateway_controller();
			System.assertEquals(true, controller.checkIfAuthorizedToGainAccess());

			c1.Paperwork_Confirmation__c = 'Paperwork Requested';
			c1.Paperwork_Confirmation_Type__c = null;
			update c1;
			System.debug('c1.Member_Categories__c: ' + c1.Member_Categories__c);
			cov_user_utility.self.refreshSelf();
 			controller = new cov_gateway_controller();
			System.assertEquals(false, controller.checkIfAuthorizedToGainAccess());

			cmp = new Campaign(Name='Access Campaign');
			insert cmp;
			CampaignMember cm = new CampaignMember(CampaignId = cmp.Id, ContactId = c1.Id);
			insert cm;
			System.assertEquals(true, controller.checkIfAuthorizedToGainAccess());

			delete cm;
			System.assertEquals(false, controller.checkIfAuthorizedToGainAccess());

		}

		PermissionSetAssignment psa = [select Id from PermissionSetAssignment 
			where AssigneeId = :u1.Id
			and PermissionSetId in (select Id from PermissionSet where Label like 'COV Access%')];
		
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
        	// to avoid mixedDML error (http://salesforce.stackexchange.com/questions/13318/error-mixed-dml-operation-on-setup-and-non-setup-objects)
			delete psa;
		}

		System.runAs(u1) {
			cov_user_utility.self.refreshSelf();
 			cov_gateway_controller controller = new cov_gateway_controller();
			System.assertEquals(false, controller.checkIfAlreadyHasPermissionSet());

			System.assertEquals(null, [select Date_of_COV_Terms_and_Conduct_Acceptance__c from User where Id = :u1.Id].Date_of_COV_Terms_and_Conduct_Acceptance__c);
			PageReference pReftest = controller.accept();
			User ucheck = [select Date_of_COV_Terms_and_Conduct_Acceptance__c, UserPermissionsChatterAnswersUser from User where Id = :u1.Id limit 1];
			System.assertNotEquals(null, ucheck.Date_of_COV_Terms_and_Conduct_Acceptance__c);
			System.assertNotEquals(null, ucheck.UserPermissionsChatterAnswersUser);

			System.assertEquals(Page.cov_dashboard.getUrl(), pReftest.getUrl());
			System.assertEquals(true, controller.getHasAcceptedAgreement());
			System.assertEquals(true, controller.checkIfAlreadyHasPermissionSet());

		}

		// Also test accept() for internal user since Chatter Answers User doesnt apply

		User uint = testusers.getInternalUser();
		Contact cint = testusers.getInternalContact();
		PermissionSetAssignment psaint = [select Id from PermissionSetAssignment 
			where AssigneeId = :uint.Id
			and PermissionSetId in (select Id from PermissionSet where Label like 'COV Access%')];
		System.runAs ( new User(Id = UserInfo.getUserId()) ) {
        // to avoid mixedDML error (http://salesforce.stackexchange.com/questions/13318/error-mixed-dml-operation-on-setup-and-non-setup-objects)
			delete psaint;
		}

		System.runAs(uint) {
			cov_user_utility.self.refreshSelf();
			cov_gateway_controller controller = new cov_gateway_controller();

			System.assertEquals(false, controller.checkIfAuthorizedToGainAccess());

			CampaignMember cm = new CampaignMember(CampaignId = cmp.Id, ContactId = cint.Id);
			insert cm;
			System.assertEquals(true, controller.checkIfAuthorizedToGainAccess());

			System.assertEquals(false, controller.checkIfAlreadyHasPermissionSet());
			System.assertEquals(null, [select Date_of_COV_Terms_and_Conduct_Acceptance__c from User where Id = :uint.Id].Date_of_COV_Terms_and_Conduct_Acceptance__c);
			PageReference pReftest = controller.accept();
			User ucheck = [select Date_of_COV_Terms_and_Conduct_Acceptance__c from User where Id = :uint.Id limit 1];
			System.assertNotEquals(null, ucheck.Date_of_COV_Terms_and_Conduct_Acceptance__c);

			System.assertEquals(Page.cov_dashboard.getUrl(), pReftest.getUrl());
			System.assertEquals(true, controller.getHasAcceptedAgreement());
			System.assertEquals(true, controller.checkIfAlreadyHasPermissionSet());

		}
			


	}


	static testMethod void test_gateway_relationship() {

		COV_Access_Profile_Settings__c setting = setTheSetting();

		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u1 = testusers.getPortalUserWithoutPerm();
		Contact c1 = testusers.getPortalContact();

       	cov_user_TEST_utility testusers2 = new cov_user_TEST_utility();
		User u2 = testusers2.getPortalUser();
		Contact c2 = testusers2.getPortalContact();

		npe4__Relationship__c r1 = new npe4__Relationship__c(
											npe4__Contact__c = c1.Id
											, npe4__RelatedContact__c = c2.Id
											, npe4__Type__c = 'Test Type'
											, npe4__Status__c = 'Current'
											);
		insert r1;

		System.runAs(u1) {
			cov_user_utility.self.refreshSelf();
			cov_gateway_controller controller = new cov_gateway_controller();

			System.assertEquals(true, controller.checkIfAuthorizedToGainAccess());
		}

	}

	static testMethod void test_user_based_constructors() {

		COV_Access_Profile_Settings__c setting = setTheSetting();

		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u1 = testusers.getPortalUser();
		Contact c1 = testusers.getPortalContact();

       	cov_user_TEST_utility testusers2 = new cov_user_TEST_utility();
		User u2 = testusers2.getPortalUser();
		Contact c2 = testusers2.getPortalContact();


		// TODO - figure out why these user based constructor tests are failing

		//System.runAs(u1) {
		//	cov_user_utility.self.refreshSelf();
		//	cov_gateway_controller controller = new cov_gateway_controller(u2);
		//	// TODO -- FIX below line which currently fails
		//	System.assertEquals(true, controller.getAlreadyHasPermissionSet());
		//	System.assertEquals(true, cov_gateway_controller.alreadyHasPermissionSet(u2));
		//}

		//PermissionSetAssignment psa = [select Id from PermissionSetAssignment 
		//	where AssigneeId = :u1.Id
		//	and PermissionSetId in (select Id from PermissionSet where Label like :setting.Prefix_for_COV_Access_Permission_Sets__c+'%')];
		//delete psa;

		//System.runAs(u1) {
		//	cov_user_utility.self.refreshSelf();
 	//		cov_gateway_controller controller = new cov_gateway_controller(u2);
		//	System.assertEquals(false, controller.getAlreadyHasPermissionSet());
		//	System.assertEquals(false, cov_gateway_controller.alreadyHasPermissionSet(u2));

		//	System.assertEquals(false, controller.checkIfAuthorizedToGainAccess());
		//	Campaign cmp = new Campaign(Name='Access Campaign');
		//	insert cmp;
		//	CampaignMember cm = new CampaignMember(CampaignId = cmp.Id, ContactId = c1.Id);
		//	insert cm;
		//	System.assertEquals(true, controller.checkIfAuthorizedToGainAccess());

		//}
	}

	static testMethod void test_submit_feedback() {

		cov_user_TEST_utility testusers = new cov_user_TEST_utility();
		User u1 = testusers.getPortalUser();

		System.runAs(u1) {
			cov_gateway_controller controller = new cov_gateway_controller();
			controller.feedbackMessage = 'Please give me access.';
			controller.feedbackSave();

			List<Feedback__c> fb = [select Id from Feedback__c where OwnerId = :u1.Id];
			System.assertEquals(1, fb.size());
		}

	}

	
	
}