prodMetadata/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Veteran Member</fullName>
                </value>
                <value>
                    <fullName>Veteran Supporter</fullName>
                </value>
                <value>
                    <fullName>Civilian Supporter</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>National_Give__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overides zip codes and states.</description>
        <inlineHelpText>Overrides zip codes and states.</inlineHelpText>
        <label>National Give</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed Visible</fullName>
                </value>
                <value>
                    <fullName>Closed Invisible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Come First Served</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Screened Give</fullName>
                </value>
                <value>
                    <fullName>Unlimited Give</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Request__c.object
<CustomObject>
    <description>Connects applicants to give</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <description>Should be a confirmed member veteran only.</description>
        <inlineHelpText>Should be a confirmed member veteran only.</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Give_Instance__c</fullName>
        <label>Give Instance</label>
        <referenceTo>Give_Instance__c</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Give requested</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Wait-list</fullName>
                </value>
                <value>
                    <fullName>Tentative confirmation</fullName>
                </value>
                <value>
                    <fullName>Final confirmation</fullName>
                </value>
                <value>
                    <fullName>Information sent</fullName>
                </value>
                <value>
                    <fullName>Info requested of member</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Give Request</label>
    <nameField>
        <displayFormat>GR-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Give Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/IAVAEvent__c.object
<CustomObject>
    <fields>
        <fullName>Dont_create_Chatter_Group__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked (default) do not automatically create a chatter group for event communication.</description>
        <inlineHelpText>If checked (default) do not automatically create a chatter group for event communication.</inlineHelpText>
        <label>Don&apos;t create Chatter Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Public_Details__c</fullName>
        <label>Event Public Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Organizer_Type__c</fullName>
        <label>Organizer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Distributed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unpublished</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Flagged/Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Awareness Action</fullName>
                </value>
                <value>
                    <fullName>Bar Gathering</fullName>
                </value>
                <value>
                    <fullName>Career Development</fullName>
                </value>
                <value>
                    <fullName>Concert</fullName>
                </value>
                <value>
                    <fullName>Cookout</fullName>
                </value>
                <value>
                    <fullName>DPAA Burial</fullName>
                </value>
                <value>
                    <fullName>Fundraiser</fullName>
                </value>
                <value>
                    <fullName>Internal IAVA Training</fullName>
                </value>
                <value>
                    <fullName>Movie Screening</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outdoor Activity</fullName>
                </value>
                <value>
                    <fullName>Parade</fullName>
                </value>
                <value>
                    <fullName>Run</fullName>
                </value>
                <value>
                    <fullName>Seminar/Education</fullName>
                </value>
                <value>
                    <fullName>Service Project</fullName>
                </value>
                <value>
                    <fullName>Social</fullName>
                </value>
                <value>
                    <fullName>Sporting Event</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>VetTogether</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prodMetadata/src/objects/IAVAEvent_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <formula>Event__r.Event_Date__c</formula>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>IAVAEvent__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reply_Status__c</fullName>
        <label>Reply Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>Atnd-{000000}</displayFormat>
        <label>Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partnerships</relationshipLabel>
        <relationshipName>Partnership_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/test_randWinnerTest.cls
@isTest
public class test_randWinnerTest
{
    static testMethod void checkPageErrorSelectGiveAndEvent()
    {
        test.startTest();
        randWinnerTest controller = new randWinnerTest();
        
        PageReference rwPage = Page.randomWinner;
        test.setCurrentPage(rwPage);
        controller.isEvent = true;
        controller.isGive = true;
        controller.name = 'Test VT 1';
        controller.numWins = 1;
        controller.onScreen = true;
        controller.inCsv = false;
        pageReference newRef = controller.getWinner();
    }
    
    static testMethod void checkPageErrorDontSelectGiveOrEvent()
    {
        test.startTest();
        randWinnerTest controller = new randWinnerTest();
        
        PageReference rwPage = Page.randomWinner;
        test.setCurrentPage(rwPage);
        controller.isEvent = false;
        controller.isGive = false;
        controller.name = 'Test VT 1';
        controller.numWins = 1;
        controller.onScreen = true;
        controller.inCsv = false;
        pageReference newRef = controller.getWinner();
    }
    
    static testMethod void checkPageErrorNoWinners()
    {
        test.startTest();
        randWinnerTest controller = new randWinnerTest();
        
        PageReference rwPage = Page.randomWinner;
        test.setCurrentPage(rwPage);
        controller.isEvent = true;
        controller.isGive = false;
        controller.name = 'Test VT 1';
        controller.numWins = 0;
        controller.onScreen = true;
        controller.inCsv = false;
        pageReference newRef = controller.getWinner();
    }
    
    static testMethod void checkPageErrorSelectScreenAndCSV()
    {
        test.startTest();
        randWinnerTest controller = new randWinnerTest();
        
        PageReference rwPage = Page.randomWinner;
        test.setCurrentPage(rwPage);
        controller.isEvent = true;
        controller.isGive = false;
        controller.name = 'Test VT 1';
        controller.numWins = 1;
        controller.onScreen = true;
        controller.inCsv = true;
        pageReference newRef = controller.getWinner();
    }
    
    static testMethod void checkPageErrorDontSelectScreenOrCSV()
    {
        test.startTest();
        randWinnerTest controller = new randWinnerTest();
        
        PageReference rwPage = Page.randomWinner;
        test.setCurrentPage(rwPage);
        controller.isEvent = true;
        controller.isGive = false;
        controller.name = 'Test VT 1';
        controller.numWins = 1;
        controller.onScreen = false;
        controller.inCsv = false;
        pageReference newRef = controller.getWinner();
    }
    
    static testMethod void checkEventCSVWinners()
    {
        IAVAEvent__c e = new IAVAEvent__c(Name='Test VT 1', Type__c='VetTogether', Status__c = 'Published', Dont_create_Chatter_Group__c = false, Organizer_Type__c = 'Distributed', Event_Public_Details__c ='These are the public details for e1', Event_Date__c = System.today().addDays(10));
        insert e;
        
        List<Contact> conList = new List<Contact>();
        Contact c0 = new Contact(FirstName = 'new', LastName = 'contact0', Email = 'newcon0@iava.test');
        conList.add(c0);
        Contact c1 = new Contact(FirstName = 'new', LastName = 'contact1', Email = 'newcon1@iava.test');
        conList.add(c1);
        Contact c2 = new Contact(FirstName = 'new', LastName = 'contact2', Email = 'newcon2@iava.test');
        conList.add(c2);
        Contact c3 = new Contact(FirstName = 'new', LastName = 'contact3', Email = 'newcon3@iava.test');
        conList.add(c3);
        insert conList;
        
        List<IAVAEvent_Attendee__c> attList = new List<IAVAEvent_Attendee__c>();
        IAVAEvent_Attendee__c eA0 = new IAVAEvent_Attendee__c(Event__c = e.Id, Contact__c = c0.Id, Reply_Status__c = 'Yes');
        attList.add(eA0);
        IAVAEvent_Attendee__c eA1 = new IAVAEvent_Attendee__c(Event__c = e.Id, Contact__c = c1.Id, Reply_Status__c = 'Yes');
        attList.add(eA1);
        IAVAEvent_Attendee__c eA2 = new IAVAEvent_Attendee__c(Event__c = e.Id, Contact__c = c2.Id, Reply_Status__c = 'Yes');
        attList.add(eA2);
        IAVAEvent_Attendee__c eA3 = new IAVAEvent_Attendee__c(Event__c = e.Id, Contact__c = c3.Id, Reply_Status__c = 'Yes');
        attList.add(eA3);
        insert attList;
        
        test.startTest();
        randWinnerTest controller = new randWinnerTest();
        
        PageReference rwPage = Page.randomWinner;
        test.setCurrentPage(rwPage);
        controller.isEvent = true;
        controller.isGive = false;
        controller.name = 'Test VT 1';
        controller.numWins = 1;
        controller.onScreen = false;
        controller.inCsv = true;
        pageReference newRef = controller.getWinner();
    }
    
    static testMethod void checkEventOnScreenWinners()
    {
        IAVAEvent__c e = new IAVAEvent__c(Name='Test VT 1', Type__c='VetTogether', Status__c = 'Published', Dont_create_Chatter_Group__c = false, Organizer_Type__c = 'Distributed', Event_Public_Details__c ='These are the public details for e1', Event_Date__c = System.today().addDays(10));
        insert e;
        
        List<Contact> conList = new List<Contact>();
        Contact c0 = new Contact(FirstName = 'new', LastName = 'contact0', Email = 'newcon0@iava.test');
        conList.add(c0);
        Contact c1 = new Contact(FirstName = 'new', LastName = 'contact1', Email = 'newcon1@iava.test');
        conList.add(c1);
        Contact c2 = new Contact(FirstName = 'new', LastName = 'contact2', Email = 'newcon2@iava.test');
        conList.add(c2);
        Contact c3 = new Contact(FirstName = 'new', LastName = 'contact3', Email = 'newcon3@iava.test');
        conList.add(c3);
        insert conList;
        
        List<IAVAEvent_Attendee__c> attList = new List<IAVAEvent_Attendee__c>();
        IAVAEvent_Attendee__c eA0 = new IAVAEvent_Attendee__c(Event__c = e.Id, Contact__c = c0.Id, Reply_Status__c = 'Yes');
        attList.add(eA0);
        IAVAEvent_Attendee__c eA1 = new IAVAEvent_Attendee__c(Event__c = e.Id, Contact__c = c1.Id, Reply_Status__c = 'Yes');
        attList.add(eA1);
        IAVAEvent_Attendee__c eA2 = new IAVAEvent_Attendee__c(Event__c = e.Id, Contact__c = c2.Id, Reply_Status__c = 'Yes');
        attList.add(eA2);
        IAVAEvent_Attendee__c eA3 = new IAVAEvent_Attendee__c(Event__c = e.Id, Contact__c = c3.Id, Reply_Status__c = 'Yes');
        attList.add(eA3);
        insert attList;
        
        test.startTest();
        randWinnerTest controller = new randWinnerTest();
        
        PageReference rwPage = Page.randomWinner;
        test.setCurrentPage(rwPage);
        controller.isEvent = true;
        controller.isGive = false;
        controller.name = 'Test VT 1';
        controller.numWins = 1;
        controller.onScreen = true;
        controller.inCsv = false;
        pageReference newRef = controller.getWinner();
    }
    
    static testMethod void checkGiveCSVWinners()
    {
        Account a = new Account(Name = 'Account for Partnership');
        insert a;
        
        Partnership_Request__c p = new Partnership_Request__c(Name = 'Partnership for Give', Organization__c = a.Id, Public_Partner_Name__c = 'Give Partnership');
        insert p;
        
        Give__c g = new Give__c(Name='Test Give 1', Partnership_Request__c = p.Id, National_Give__c = true);
        insert g;
        
        Give_Instance__c gI = new Give_Instance__c(Give__c = g.Id);
        insert gI;
        
        List<Contact> conList = new List<Contact>();
        Contact c0 = new Contact(FirstName = 'new', LastName = 'contact0', Email = 'newcon0@iava.test');
        conList.add(c0);
        Contact c1 = new Contact(FirstName = 'new', LastName = 'contact1', Email = 'newcon1@iava.test');
        conList.add(c1);
        Contact c2 = new Contact(FirstName = 'new', LastName = 'contact2', Email = 'newcon2@iava.test');
        conList.add(c2);
        Contact c3 = new Contact(FirstName = 'new', LastName = 'contact3', Email = 'newcon3@iava.test');
        conList.add(c3);
        insert conList;
        
        List<Give_Request__c> grList = new List<Give_Request__c>();
        Give_Request__c gR0 = new Give_Request__c(Give_Instance__c = gI.Id, Applicant__c = c0.Id, Stage__c = 'Give Requested', Email_Address__c = 'newcon0@iava.test');
        grList.add(gR0);
        Give_Request__c gR1 = new Give_Request__c(Give_Instance__c = gI.Id, Applicant__c = c1.Id, Stage__c = 'Give Requested', Email_Address__c = 'newcon1@iava.test');
        grList.add(gR1);
        Give_Request__c gR2 = new Give_Request__c(Give_Instance__c = gI.Id, Applicant__c = c2.Id, Stage__c = 'Give Requested', Email_Address__c = 'newcon2@iava.test');
        grList.add(gR2);
        Give_Request__c gR3 = new Give_Request__c(Give_Instance__c = gI.Id, Applicant__c = c3.Id, Stage__c = 'Give Requested', Email_Address__c = 'newcon3@iava.test');
        grList.add(gR3);
        insert grList;
        
        test.startTest();
        randWinnerTest controller = new randWinnerTest();
        
        PageReference rwPage = Page.randomWinner;
        test.setCurrentPage(rwPage);
        controller.isEvent = false;
        controller.isGive = true;
        controller.name = 'Test Give 1';
        controller.numWins = 1;
        controller.onScreen = false;
        controller.inCsv = true;
        pageReference newRef = controller.getWinner();
    }
    
    static testMethod void checkGiveOnScreenWinners()
    {
        Account a = new Account(Name = 'Account for Partnership');
        insert a;
        
        Partnership_Request__c p = new Partnership_Request__c(Name = 'Partnership for Give', Organization__c = a.Id, Public_Partner_Name__c = 'Give Partnership');
        insert p;
        
        Give__c g = new Give__c(Name='Test Give 1', Partnership_Request__c = p.Id, National_Give__c = true);
        insert g;
        
        Give_Instance__c gI = new Give_Instance__c(Give__c = g.Id);
        insert gI;
        
        List<Contact> conList = new List<Contact>();
        Contact c0 = new Contact(FirstName = 'new', LastName = 'contact0', Email = 'newcon0@iava.test');
        conList.add(c0);
        Contact c1 = new Contact(FirstName = 'new', LastName = 'contact1', Email = 'newcon1@iava.test');
        conList.add(c1);
        Contact c2 = new Contact(FirstName = 'new', LastName = 'contact2', Email = 'newcon2@iava.test');
        conList.add(c2);
        Contact c3 = new Contact(FirstName = 'new', LastName = 'contact3', Email = 'newcon3@iava.test');
        conList.add(c3);
        insert conList;
        
        List<Give_Request__c> grList = new List<Give_Request__c>();
        Give_Request__c gR0 = new Give_Request__c(Give_Instance__c = gI.Id, Applicant__c = c0.Id, Stage__c = 'Give Requested', Email_Address__c = 'newcon0@iava.test');
        grList.add(gR0);
        Give_Request__c gR1 = new Give_Request__c(Give_Instance__c = gI.Id, Applicant__c = c1.Id, Stage__c = 'Give Requested', Email_Address__c = 'newcon1@iava.test');
        grList.add(gR1);
        Give_Request__c gR2 = new Give_Request__c(Give_Instance__c = gI.Id, Applicant__c = c2.Id, Stage__c = 'Give Requested', Email_Address__c = 'newcon2@iava.test');
        grList.add(gR2);
        Give_Request__c gR3 = new Give_Request__c(Give_Instance__c = gI.Id, Applicant__c = c3.Id, Stage__c = 'Give Requested', Email_Address__c = 'newcon3@iava.test');
        grList.add(gR3);
        insert grList;
        
        test.startTest();
        randWinnerTest controller = new randWinnerTest();
        
        PageReference rwPage = Page.randomWinner;
        test.setCurrentPage(rwPage);
        controller.isEvent = false;
        controller.isGive = true;
        controller.name = 'Test Give 1';
        controller.numWins = 1;
        controller.onScreen = true;
        controller.inCsv = false;
        pageReference newRef = controller.getWinner();
    }
}