prodMetadata/src/objects/Detailed_Deployment_Information__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OEF_OIF__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gulf War</fullName>
                </value>
                <value>
                    <fullName>Korean War</fullName>
                </value>
                <value>
                    <fullName>OEF</fullName>
                </value>
                <value>
                    <fullName>OIF</fullName>
                </value>
                <value>
                    <fullName>OND</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Peacetime</fullName>
                </value>
                <value>
                    <fullName>Vietnam War</fullName>
                </value>
                <value>
                    <fullName>World War II</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stop_Loss__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop-Loss</label>
        <type>Checkbox</type>
    </fields>
    <label>Detailed Deployment Information</label>
    <nameField>
        <displayFormat>DDI-{000000}</displayFormat>
        <label>Detailed Deployment Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detailed Deployment Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/cov_customdeployment.cls
public with sharing class cov_customdeployment {


	public String city {get; set;}
	public String country {get; set;}
	public Date enddate {get; set;}
	public String notes {get; set;}
	public String operation {get; set;}
	public Date startdate {get; set;}
	public Boolean stoploss {get; set;}
	public String dpId {get; set;}
	public Boolean ineditmode {get; set;}
	
	public String startdatenice {get; set;}
	public String enddatenice {get; set;}

	public cov_customdeployment() {}
	
	public static List<cov_customdeployment> createCDs(List<Detailed_Deployment_Information__c> DDIs) {
		
		List<cov_customdeployment> cds = new List<cov_customdeployment>();
		for (Detailed_Deployment_Information__c ddi : DDIs) {
			cov_customdeployment cd = new cov_customdeployment();
			cd.city = ddi.City__c;
			cd.country = ddi.Country__c;
			cd.enddate = ddi.End_Date__c;
			cd.notes = ddi.Notes__c;
			cd.operation = ddi.OEF_OIF__c;
			cd.startdate = ddi.Start_Date__c;
			cd.stoploss = ddi.Stop_Loss__c;
			cd.dpId = ddi.Id;
			
			if (cd.startdate != null) {
				cd.startdatenice = cov_utilities.niceDateSlashes(cd.startdate);
			}
			if (cd.enddate != null) {
				cd.enddatenice = cov_utilities.niceDateSlashes(cd.enddate);
			}
						
			cds.add(cd);
		}
		
		return cds;
		
	}


}