prodMetadata/src/objects/Focus_Area__c.object
<CustomObject>
    <description>A Focus Area is either a Policy Issue (Employment) or an IAVA Campaign (Combat to Careers)</description>
    <label>Focus Area</label>
    <nameField>
        <label>Focus Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Focus Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Focus_Area_Media_Request_junction__c.object
<CustomObject>
    <description>Junction object to connect Focus Areas with Media Requests</description>
    <fields>
        <fullName>Focus_Area__c</fullName>
        <label>Focus Area</label>
        <referenceTo>Focus_Area__c</referenceTo>
        <relationshipLabel>Media Requests</relationshipLabel>
        <relationshipName>Focus_Area_Media_Request_junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Media_Request__c</fullName>
        <label>Media Request</label>
        <referenceTo>Media_Request__c</referenceTo>
        <relationshipName>Focus_Area_Media_Request_junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Focus Area related to Media Request</label>
    <nameField>
        <displayFormat>FA-MR-{00000}</displayFormat>
        <label>FA-MediaReq name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Focus Areas related to Media Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Media_Request__c.object
<CustomObject>
    <fields>
        <fullName>Related_to_program__c</fullName>
        <label>Related to Program(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COV</fullName>
                </value>
                <value>
                    <fullName>Employment Workshops</fullName>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Jobs Tool</fullName>
                </value>
                <value>
                    <fullName>Local Leaders</fullName>
                </value>
                <value>
                    <fullName>NGIB</fullName>
                </value>
                <value>
                    <fullName>Referral Program</fullName>
                </value>
                <value>
                    <fullName>Storm the Hill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Request</label>
    <nameField>
        <label>Media Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/PicklistToJunctionTests.cls
/*
 * Test of class PicklistToJunction that adds or removes junction records 
 * when you add or remove values from a multi-select picklist
 *
 * Abstracted so it can be used by any two objects with junction records.
 *
 * More technically: Given a list of values (from a multi-select picklist, for example)
 * add or remove junction objects between the "home" object and the
 * target object with the same name as each value.
 *
 *
 * SD 2012
 */


@isTest
private class PicklistToJunctionTests {

  ////////// Tests //////////

    static testMethod void testPicklistToJunction() {
       
		Focus_Area__c fa1 = new Focus_Area__c (Name = 'Test Area 1');
    	insert fa1;

    	Focus_Area__c fa2 = new Focus_Area__c (Name = 'Test Area 2');
    	insert fa2;

    	Focus_Area__c fa3 = new Focus_Area__c (Name = 'Test Area 3');
    	insert fa3;

    	
    	Media_Request__c mr1 = new Media_Request__c(Name = 'Unit Test 1', Related_to_program__c = 'Test Area 1; Test Area 3');
    	insert mr1;
    	
    	System.assertEquals(1, [select count() from Focus_Area_Media_Request_junction__c
    		where Media_Request__c = :mr1.id and Focus_Area__c = :fa1.id]);
    	System.assertEquals(0, [select count() from Focus_Area_Media_Request_junction__c
    		where Media_Request__c = :mr1.id and Focus_Area__c = :fa2.id]);
    	System.assertEquals(1, [select count() from Focus_Area_Media_Request_junction__c
    		where Media_Request__c = :mr1.id and Focus_Area__c = :fa3.id]);
    	
		mr1.Related_to_program__c = 'Test Area 2; Test Area 3';
		update mr1;
		
    	System.assertEquals(0, [select count() from Focus_Area_Media_Request_junction__c
    		where Media_Request__c = :mr1.id and Focus_Area__c = :fa1.id]);
    	System.assertEquals(1, [select count() from Focus_Area_Media_Request_junction__c
    		where Media_Request__c = :mr1.id and Focus_Area__c = :fa2.id]);
    	System.assertEquals(1, [select count() from Focus_Area_Media_Request_junction__c
    		where Media_Request__c = :mr1.id and Focus_Area__c = :fa3.id]);
		


    }
}