prodMetadata/src/objects/Geo_Location__c.object
<CustomObject>
    <description>Holds a Geo cordinate, and information to build a balloon for this point</description>
    <label>Geo Location</label>
    <nameField>
        <label>Geo Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to indicate that Campaign Members are to receive notifications.</description>
        <inlineHelpText>This field will be used to indicate that Campaign Members are to receive notifications.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distance__c</fullName>
        <description>The distance for pending notifications.</description>
        <inlineHelpText>The distance for pending notifications.</inlineHelpText>
        <label>Distance</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Geo_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Geo Location object which stores Latitude, Longitude values</description>
        <label>Geo Location</label>
        <referenceTo>Geo_Location__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <description>This field will be used to store the text of the notification message that is to be delivered.</description>
        <inlineHelpText>This field will be used to store the text of the notification message that is to be delivered.</inlineHelpText>
        <label>Message Text</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>National__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to indicate that the notification will be sent nation-wide to all Contacts.</description>
        <inlineHelpText>This field will be used to indicate that the notification will be sent nation-wide to all Contacts.</inlineHelpText>
        <label>National</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</description>
        <inlineHelpText>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</inlineHelpText>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</description>
        <inlineHelpText>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</inlineHelpText>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Pending_Notification__c.object
<CustomObject>
    <description>This custom Salesforce object will be used to store pending notifications.  A Pending notification simply notes that a user has indicated that a notification message is to be sent out for a Give or non-Give.  The criteria for the notification are also stored in this object.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to store the ID of the Campaign to which a Contact belongs for this notification to be sent.</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Pending Notifications</relationshipLabel>
        <relationshipName>Pending_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distance__c</fullName>
        <description>The distance</description>
        <label>Distance</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Give__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to store the ID of the Give for which this pending notification applies (if any).</description>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Pending Notifications</relationshipLabel>
        <relationshipName>Pending_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <description>This field will be used to store the text of the notification message that is to be delivered.</description>
        <label>Message Text</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>National__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to indicate that the notification will be sent nation-wide to all</description>
        <label>National</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will become checked once the pending notification has been processed.</description>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</description>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>This field will be used to indicate the Zip code in which a Contact resides that this notification will be sent to.</description>
        <inlineHelpText>This field will be used to indicate the Zip code in which a Contact resides that this notification will be sent to.</inlineHelpText>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Pending Notification</label>
    <nameField>
        <label>Pending Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pending Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/PendingNotificationBatchProcessScheduler.cls
global class PendingNotificationBatchProcessScheduler implements Schedulable{
	
	List<Pending_Notification__c> listPendingNotifications = new List<Pending_Notification__c>();
	
	/* Necessary method which implements the Schedulable interface */
    global void execute(SchedulableContext sc){	
		try{	
			listPendingNotifications = [Select	Zip_Code__c, State__c, Processed__c, OwnerId, National__c, 
												Name, Message_Text__c, Give__c, Give__r.Geo_Location__c, Distance__c, Campaign__c 
										From 	Pending_Notification__c
										Where	Processed__c = false];
			if(listPendingNotifications.size() > 0)
			{
				PendingNotificationBatchProcessor pendingNotificationBatchProcessor = new PendingNotificationBatchProcessor();
	    		ID batchJobId = Database.executeBatch(pendingNotificationBatchProcessor,1);
	    		System.debug('PendingNotificationBatchProcessor Request Enqueued: '+batchJobId);
			}
			
		}
		catch(QueryException e){
			System.debug(e.getMessage());
		}
    }
    
    public static void start() 
 	{
		//Seconds Minutes Hours Day_of_month Month Day_of_week optional_year
		System.schedule('Pending Notifications 9AM ET - 9PM PT', '0 15 10-1 ? * 1-7', new PendingNotificationBatchProcessScheduler());
	}
}