prodMetadata/src/objects/Geo_Location__c.object
<CustomObject>
    <description>Holds a Geo cordinate, and information to build a balloon for this point</description>
    <fields>
        <fullName>lat__c</fullName>
        <label>lat</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lon__c</fullName>
        <label>lon</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <label>Geo Location</label>
    <nameField>
        <label>Geo Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</description>
        <inlineHelpText>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</inlineHelpText>
        <label>City, ST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Geo Location object which stores Latitude, Longitude values</description>
        <label>Geo Location</label>
        <referenceTo>Geo_Location__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code_s__c</fullName>
        <inlineHelpText>Multiple Zip Codes should be Separate Gives</inlineHelpText>
        <label>Location by Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/GeoCodeUpdateController.cls
public class GeoCodeUpdateController {
	
	// create Geo Location for this zip/lat/lon if none exists and set Gives with this zip to reference this Geo Location
	public PageReference updateGives() {
		Map<String, String> params = ApexPages.currentPage().getParameters();
		System.debug('>>>>>>>>>> params: ' + params);
		String latitude = params.get('lat');
		String longitude = params.get('lon');
		String zip = params.get('zip');
		String city = '';
		
		if (latitude != null && latitude != '0' && longitude != null && longitude != '0' && zip != null && zip != '') {
			
			// get all Gives with this zip that need Geo Location set
			List<Give__c> givesToUpdate = [select Id, City__c from Give__c where Zip_Code_s__c = :zip and Geo_Location__c = null];
			if (!givesToUpdate.isEmpty()) {
				city = givesToUpdate[0].City__c;
			}
			
			// check if a Geo Location already exists for this zip
			String geolocName = zip + ' - %';
			List<Geo_Location__c> geolocs = [select Id from Geo_Location__c where Name like :geolocName];
			
			Geo_Location__c geoloc;
			
			// create new Geo Location if none exists for this zip
			if (geolocs.isEmpty()) {
				geoloc = new Geo_Location__c(lat__c = Decimal.valueOf(latitude), lon__c = Decimal.valueOf(longitude), Name = zip + ' - ' + city);
				insert geoloc;
			} else {
				geoloc = geolocs[0];
			}
			
			// set geo location reference on all Gives with this zip
			for (Give__c g : givesToUpdate) {
				g.Geo_Location__c = geoloc.Id;
			}
			update givesToUpdate;
			
		}
		
		PageReference pr = Page.GeoCodeAdmin;
		if (zip!= null && zip != '') {
			pr.getParameters().put('zip', zip);
		}
		pr.setRedirect(true);
		return pr;
	}
	
}