prodMetadata/src/objects/Geo_Location__c.object
<CustomObject>
    <description>Holds a Geo cordinate, and information to build a balloon for this point</description>
    <fields>
        <fullName>About_Us__c</fullName>
        <inlineHelpText>May contain valid XHTML markup 
http://www.w3.org/TR/xhtml1/</inlineHelpText>
        <label>About Us</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Geocode_Status__c</fullName>
        <label>Geocode Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebLink__c</fullName>
        <description>Link to the website for this location</description>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>lat__c</fullName>
        <label>lat</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lon__c</fullName>
        <label>lon</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <label>Geo Location</label>
    <nameField>
        <label>Geo Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</description>
        <inlineHelpText>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</inlineHelpText>
        <label>City, ST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>E.g. “Watch the Orioles take on the Cardinals in a battle of the Birds. Seats are in the lower deck along the third base line.”</description>
        <inlineHelpText>E.g. “Watch the Orioles take on the Cardinals in a battle of the Birds. Seats are in the lower deck along the third base line.”</inlineHelpText>
        <label>Short Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Geo_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Geo Location object which stores Latitude, Longitude values</description>
        <label>Geo Location</label>
        <referenceTo>Geo_Location__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Description__c</fullName>
        <description>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</description>
        <inlineHelpText>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</inlineHelpText>
        <label>Location or Venue</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location_by_State_s__c</fullName>
        <description>E.g. “NY, CT, NJ, VA, DC”.</description>
        <inlineHelpText>E.g. “NY, CT, NJ, VA, DC”.</inlineHelpText>
        <label>Location by State(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>More_Info_Link__c</fullName>
        <description>E.g. website of a store, concert venue or show description.</description>
        <inlineHelpText>E.g. website of a store, concert venue or show description.</inlineHelpText>
        <label>More Info Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Zip_Code_s__c</fullName>
        <inlineHelpText>Multiple Zip Codes should be Separate Gives</inlineHelpText>
        <label>Location by Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/newGeoLocationExt.cls
public class newGeoLocationExt {
	
	public boolean isstep1 { get; set; } { isstep1 = true; }
	
	public boolean isstep2 { get; set; } { isstep2 = false; }
	 
	private final Give__c give;
	
	public newGeoLocationExt( ApexPages.StandardController stdController) {
        this.give = (Give__c)stdController.getRecord();
    	
    	items = new List<SelectOption>(); 
    	items.add(new SelectOption('addr','Use this address')); 
    	items.add(new SelectOption('manu','Manually locate')); 
    	method = 'manu';
    	
		if ( give.Location_Description__c != null ||  
	    		give.City__c != null ||
	    		give.Location_by_State_s__c != null  ||
	    		give.Zip_Code_s__c != null) { 
    		method = 'addr'; 
    		
    		nextAddr = GeoUtils.accountAddressString(give); 
    	}
    }
    public string nextAddr { get; set; }     
    
    public string geostatus { get; set; }

 	public string geopoint { get; set; }
    
    public boolean hasNextAddress {	get { return  ( nextAddr != '' ); } 	}
    
    public pageReference step2() {
    	isstep1 = false; 
    	isstep2 = true;	
    	
    	Geo_Location__c glnew = new Geo_Location__c( 
	    	name = give.name,
	    	webLink__c = give.More_Info_Link__c,
	    	about_us__c = give.description__c
    	); 
    	insert glnew;
    	give.Geo_Location__c = glnew.id; 
    	update give;
    	    	
    	if ( method == 'manu' ) { 
    	 	// go to the position page	
    	 	PageReference pr = Page.GeoReposition;  //new PageReference( '/apex/GeoReposition' ); 
    	 	pr.getParameters().put('id', glnew.id);
    	 	pr.setRedirect( true);
    	 	return pr;
    	}   	
        
        if ( geostatus  == '200' )  {
            string[] lat_lon = geopoint.split(',');
            glnew.lat__c = Double.valueOf(lat_lon[1]); 
            glnew.lon__c = Double.valueOf(lat_lon[0]);  
            glnew.geocode_status__c = 'G_GEO_SUCCESS';
        } else { 
            glnew.lat__c = 0.0; glnew.lon__c = 0.0;
            glnew.geocode_status__c = 
            	GeoUtils.geo_response.get( geostatus )
            	+ ' ('+ geostatus + ')';
        }         
		update glnew; 
 	 
    	return new PageReference('/'+glnew.id);
    }
         
    public Boolean automatic { set; get; } 
	public list<SelectOption> items { get; set; }  
	public string method   { get; set;} 
	
	public static testmethod void test_geo() {
		Give__c a = [select id, name,Location_Description__c ,City__c ,Location_by_State_s__c 
        	,	Zip_Code_s__c ,description__c, More_Info_Link__c
              from give__c limit 1];
		ApexPages.StandardController ssc = 
		new ApexPages.StandardController(a);
        newGeoLocationExt nge = new newGeoLocationExt(  ssc);
		System.assert( nge.automatic == null );
		System.assert( nge.isstep1 == true); 
		System.assert( nge.isstep2 == false); 
		System.assert(nge.step2() != null);
	} 
}