prodMetadata/src/objects/Geo_Location__c.object
<CustomObject>
    <description>Holds a Geo cordinate, and information to build a balloon for this point</description>
    <fields>
        <fullName>About_Us__c</fullName>
        <inlineHelpText>May contain valid XHTML markup 
http://www.w3.org/TR/xhtml1/</inlineHelpText>
        <label>About Us</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Geocode_Status__c</fullName>
        <label>Geocode Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebLink__c</fullName>
        <description>Link to the website for this location</description>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>lat__c</fullName>
        <label>lat</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lon__c</fullName>
        <label>lon</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <label>Geo Location</label>
    <nameField>
        <label>Geo Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</description>
        <inlineHelpText>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</inlineHelpText>
        <label>City, ST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>E.g. “Watch the Orioles take on the Cardinals in a battle of the Birds. Seats are in the lower deck along the third base line.”</description>
        <inlineHelpText>E.g. “Watch the Orioles take on the Cardinals in a battle of the Birds. Seats are in the lower deck along the third base line.”</inlineHelpText>
        <label>Short Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Geo_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Geo Location object which stores Latitude, Longitude values</description>
        <label>Geo Location</label>
        <referenceTo>Geo_Location__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geocode_Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this checkbox to exclude the account from the Geo Force Geocode process</description>
        <inlineHelpText>Check this box to exclude from geocoding process</inlineHelpText>
        <label>Geocode Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_Description__c</fullName>
        <description>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</description>
        <inlineHelpText>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</inlineHelpText>
        <label>Location or Venue</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location_by_State_s__c</fullName>
        <description>E.g. “NY, CT, NJ, VA, DC”.</description>
        <inlineHelpText>E.g. “NY, CT, NJ, VA, DC”.</inlineHelpText>
        <label>Location by State(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>More_Info_Link__c</fullName>
        <description>E.g. website of a store, concert venue or show description.</description>
        <inlineHelpText>E.g. website of a store, concert venue or show description.</inlineHelpText>
        <label>More Info Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zip_Code_s__c</fullName>
        <inlineHelpText>Multiple Zip Codes should be Separate Gives</inlineHelpText>
        <label>Location by Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/bulkGeoCode.cls
public class bulkGeoCode {
    
    public string nextAddr { get; set; } 
	
	public Give__c give { get; set; } 
	
	public bulkGeoCode() {		nextAddr = getNextAddress(); 	}
	
	public boolean hasNextAddress {	get { return  ( nextAddr != '' ); } 	}
	
  	public static string jsapi_script { get { return  geoApiKey.jsapi_script; }}
 
  	public static string maps_script { get { return  geoApiKey.maps_script; }}

    public string msg {get; set;}  

    public Boolean doGeocode { get; private set; } { doGeocode = false; } 
     
 	public string giveId { get; set; }

 	public string geostatus { get; set; }

 	public string geopoint { get; set; }
 	
    public void newGeoLocation() { 
    	
    	doGeocode = true;
    	// update the database, fetch a new give?
    	Geo_Location__c glnew = new Geo_Location__c( 
	    	name = give.name,
	    	webLink__c = give.More_Info_Link__c,
	    	about_us__c = give.description__c,
	    	lat__c = 0.0 ,
	    	lon__c = 0.0
    	); 
    
    	if (geostatus == null ) {
	    //	msg = 'Geococd status is null';
	    	return;
	    	
        }
        if ( geostatus  == '200' )  { 
            glnew.geocode_status__c = 'G_GEO_SUCCESS';
            string[] lat_lon = geopoint.split(',');
            if ( lat_lon.size() ==2) {
	            glnew.lat__c = Double.valueOf(lat_lon[1]); 
	            glnew.lon__c = Double.valueOf(lat_lon[0]); 
            } 

        } else { 
            
            glnew.geocode_status__c = 
            	GeoUtils.geo_response.get( geostatus )
            	+ ' ('+ geostatus + ')';
        }         
        try {
	 		insert glnew;
	    	give.Geo_Location__c = glnew.id; 
	    	update give;
	    	
	    	nextAddr = getNextAddress();  // fetch next one    	
        } catch (exception e) {
         //   msg = e.getMessage(); 
            doGeocode = false;
        }
    }
    
    /* 
     * pull the give into a class var, and generate an address string to return
     */
    string getNextAddress() { 
    	try {
    	   	
    	   	give = [select id, name,Location_Description__c ,City__c ,Location_by_State_s__c 
        	,	Zip_Code_s__c ,description__c, More_Info_Link__c
              from give__c where geo_location__c = null AND 
              Geocode_Exclude__c != true 
              limit 1];
         	giveId = give.id;
         	
         	return  GeoUtils.accountAddressString(give);
         	 
        } catch (exception e) { 
         //   msg = e.getMessage(); 
            doGeocode = false;
            return '' ;
        }
    }
    
    public static testmethod void t1 () { 
         Partnership_Request__c PR = new Partnership_Request__c();
    	PR = [select id from Partnership_Request__c where Public_Partner_Name__c!=null limit 1];
        Give__c a =  new Give__c( name='foo',Partnership_Request__c = PR.id, Location_Description__c='main', city__c='springfield',Location_by_State_s__c='il'
         );//,billingcountry='us');
         insert a;
        bulkGeoCode e = new bulkGeoCode(); 
        system.debug( e.msg );
        system.assertEquals( e.doGeocode , false);
        e.give = a;
        e.geostatus = '200';
        e.geopoint = '12.0,-33.0';
        e.newGeoLocation();
        e.doGeocode = true;
        system.assertEquals( e.doGeocode , true);
        e.geostatus = '201';
        e.newGeoLocation();
        System.assert( bulkGeoCode.jsapi_script != null);
    }
}