prodMetadata/src/objects/Geo_Location__c.object
<CustomObject>
    <description>Holds a Geo cordinate, and information to build a balloon for this point</description>
    <fields>
        <fullName>lat__c</fullName>
        <label>lat</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lon__c</fullName>
        <label>lon</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <label>Geo Location</label>
    <nameField>
        <label>Geo Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to indicate that Campaign Members are to receive notifications.</description>
        <inlineHelpText>This field will be used to indicate that Campaign Members are to receive notifications.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distance__c</fullName>
        <description>The distance for pending notifications.</description>
        <inlineHelpText>The distance for pending notifications.</inlineHelpText>
        <label>Distance</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Geo_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Geo Location object which stores Latitude, Longitude values</description>
        <label>Geo Location</label>
        <referenceTo>Geo_Location__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <description>This field will be used to store the text of the notification message that is to be delivered.</description>
        <inlineHelpText>This field will be used to store the text of the notification message that is to be delivered.</inlineHelpText>
        <label>Message Text</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>National__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to indicate that the notification will be sent nation-wide to all Contacts.</description>
        <inlineHelpText>This field will be used to indicate that the notification will be sent nation-wide to all Contacts.</inlineHelpText>
        <label>National</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</description>
        <inlineHelpText>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</inlineHelpText>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</description>
        <inlineHelpText>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</inlineHelpText>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Notification_Message__c.object
<CustomObject>
    <description>This custom Salesforce object will be used to store notification messages that need to be sent to a device.</description>
    <fields>
        <fullName>Message_Text__c</fullName>
        <description>This field will be used to store the message text.</description>
        <label>Message Text</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registered_Device__c</fullName>
        <description>This field will be used to store the ID of the Registered Device to which this Notification Message belongs.</description>
        <label>Registered Device</label>
        <referenceTo>Registered_Device__c</referenceTo>
        <relationshipLabel>Notification Messages</relationshipLabel>
        <relationshipName>Notification_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Notification Message</label>
    <nameField>
        <label>Notification Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Pending_Notification__c.object
<CustomObject>
    <description>This custom Salesforce object will be used to store pending notifications.  A Pending notification simply notes that a user has indicated that a notification message is to be sent out for a Give or non-Give.  The criteria for the notification are also stored in this object.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to store the ID of the Campaign to which a Contact belongs for this notification to be sent.</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Pending Notifications</relationshipLabel>
        <relationshipName>Pending_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distance__c</fullName>
        <description>The distance</description>
        <label>Distance</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Give__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to store the ID of the Give for which this pending notification applies (if any).</description>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Pending Notifications</relationshipLabel>
        <relationshipName>Pending_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message_Text__c</fullName>
        <description>This field will be used to store the text of the notification message that is to be delivered.</description>
        <label>Message Text</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>National__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to indicate that the notification will be sent nation-wide to all</description>
        <label>National</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will become checked once the pending notification has been processed.</description>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</description>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>This field will be used to indicate the Zip code in which a Contact resides that this notification will be sent to.</description>
        <inlineHelpText>This field will be used to indicate the Zip code in which a Contact resides that this notification will be sent to.</inlineHelpText>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Pending Notification</label>
    <nameField>
        <label>Pending Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pending Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Rucksack_Mobile_Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Settings for Rucksack Mobile Services</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value is part of a Name / Value pair based on the entries in this list of Custom Settings.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rucksack Mobile Services</label>
</CustomObject>

prodMetadata/src/classes/PendingNotificationBatchProcessor.cls
global class PendingNotificationBatchProcessor implements Database.Batchable<sObject>, Database.AllowsCallouts{
	
	final String batchQuery;
	
   	global PendingNotificationBatchProcessor(){
   		try{
			batchQuery='Select Zip_Code__c, State__c, Processed__c, OwnerId, National__c, Name, Message_Text__c, Give__c, Give__r.Geo_Location__c, Distance__c, Campaign__c	From Pending_Notification__c Where Processed__c = false';
			System.debug('batchQuery='+batchQuery);
		}catch(Exception e){
			System.debug(e.getMessage());
		}
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(batchQuery);
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){
      
		try{
			List<String> geoLocationIds = new List<String>();
			for(sObject s: scope){
				Pending_Notification__c p = (Pending_Notification__c) s;
				if(p.Give__c != null && p.Give__r.Geo_Location__c != null){
					geoLocationIds.add(p.Give__r.Geo_Location__c);
				}
			}
			
			Double defaultDistance = double.valueOf(Rucksack_Mobile_Services__c.getAll().get('Default Search Radius').Value__c);
			Map<String, Geo_Location__c> mapGeoLocations= new Map<String, Geo_Location__c>([Select Id, lat__c, lon__c From Geo_Location__c Where Id IN :geoLocationIds]);
			List<Registered_Device__c> devices = [Select Receive_Messages__c, New_Rewards__c, Device_Owner__c, Device_Owner__r.MailingState, Device_Owner__r.OtherState, Device_Owner__r.Latitude__c, Device_Owner__r.Longitude__c From Registered_Device__c Where Active__c = true];
			
			List<String> owners = new List<String>();
			for(Registered_Device__c d: devices){
				if(d.Device_Owner__c != null){
					owners.add(d.Device_Owner__c);
				}
			}
			
			List<CampaignMember> campaignMembers = new List<CampaignMember>();
			if(owners.size() > 0){
				campaignMembers = [Select ContactId, CampaignId From CampaignMember Where Id IN :owners];
			}
			
			List<Notification_Message__c> notifications = new List<Notification_Message__c>();
			for(sObject s: scope){
				Pending_Notification__c p = (Pending_Notification__c) s;
				Double distance = defaultDistance;
				if(p.Distance__c != null){
					distance = p.Distance__c;
				}
				if(p.Give__c != null || p.Campaign__c != null){
					for(Registered_Device__c d: devices){
						if(p.Give__c != null){
							d.New_Rewards__c = d.New_Rewards__c+1;
							Boolean hasState = false;
							if( d.Device_Owner__c != null){
								if(d.Device_Owner__r.OtherState != null){
									hasState = p.State__c.contains(d.Device_Owner__r.OtherState);	
								}else if(d.Device_Owner__r.MailingState != null){
									hasState = p.State__c.contains(d.Device_Owner__r.MailingState);
								}
							}
							
							Boolean isDeviceInDistance = false;
							if(p.Give__c != null){
								if(mapGeoLocations.get(p.Give__c) != null){
									if(mapGeoLocations.get(p.Give__c).lat__c != null){
										if(mapGeoLocations.get(p.Give__c).lon__c != null){
											if(d.Device_Owner__c != null){
												if(d.Device_Owner__r.Latitude__c != null){
													if(d.Device_Owner__r.Longitude__c != null){
														isDeviceInDistance = (distance >= GoogleMapUtils.DistanceBetween(double.valueOf(mapGeoLocations.get(p.Give__c).lat__c), double.valueOf(mapGeoLocations.get(p.Give__c).lon__c), double.valueOf(d.Device_Owner__r.Latitude__c), double.valueOf(d.Device_Owner__r.Longitude__c)));
													}
												}
											}
										}
									}
								}
							}										
							
							if(	d.Device_Owner__c == null || 
								p.National__c || 
								hasState ||
								(	p.Give__r.Geo_Location__c != null && 
									d.Device_Owner__r.Latitude__c != null && 
									d.Device_Owner__r.Longitude__c != null && 
									isDeviceInDistance)){
								Notification_Message__c n = new Notification_Message__c();
								n.Registered_Device__c = d.Id;
								n.Message_Text__c = p.Message_Text__c;
								n.Delivered__c = false;
								notifications.add(n);
							}
						}else {
							if(p.Campaign__c != null){
								Boolean isValidCampaignContact = false;
								for(CampaignMember c: campaignMembers){
									if(c.ContactId == d.Device_Owner__c && c.CampaignId == p.Campaign__c){
										isValidCampaignContact = true;
										break;
									}
								}
								if(isValidCampaignContact){
									Notification_Message__c n = new Notification_Message__c();
									n.Registered_Device__c = d.Id;
									n.Message_Text__c = p.Message_Text__c;
									n.Delivered__c = false;
									notifications.add(n);
								}
							} 
						}
					}
					
				}else continue;
				p.Processed__c = true;
			}	
			System.debug(notifications);
			System.debug(scope);
			insert notifications;
			update scope;	
		}catch(QueryException e){
			System.debug(e.getMessage());
	    }catch(DmlException e){
			System.debug(e.getMessage());
		}catch(NullPointerException e){
			System.debug(e.getMessage());
		}
	}
   

	global void finish(Database.BatchableContext BC){}
}