prodMetadata/src/objects/Geo_Location__c.object
<CustomObject>
    <description>Holds a Geo cordinate, and information to build a balloon for this point</description>
    <label>Geo Location</label>
    <nameField>
        <label>Geo Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</description>
        <inlineHelpText>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</inlineHelpText>
        <label>City, ST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Geo Location object which stores Latitude, Longitude values</description>
        <label>Geo Location</label>
        <referenceTo>Geo_Location__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code_s__c</fullName>
        <inlineHelpText>Multiple Zip Codes should be Separate Gives</inlineHelpText>
        <label>Location by Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/dc_Give_GeoCodeBatchProcessScheduler.cls
global class dc_Give_GeoCodeBatchProcessScheduler implements Schedulable{

	List<Give__c> listgive = new List<Give__c>();
	
	/* Necessary method which implements the Schedulable interface */
    global void execute(SchedulableContext sc){	
	try{	
		listgive = [select id, Zip_Code_s__c, city__c, Geo_Location__c from give__c where Zip_Code_s__c != null and Geo_Location__c = null limit 1];
		if(listgive.size() > 0)
		{
			dc_Give_GeoCodeBatchProcessor GeoCodeBatchProcessor = new dc_Give_GeoCodeBatchProcessor();
    		ID batchJobId = Database.executeBatch(GeoCodeBatchProcessor,1);
    		System.debug('GeoCodeBatchProcessor Request Enqueued: '+batchJobId);
		}
		
	}
	catch(exception e){}
    }
}