prodMetadata/src/objects/Geo_Location__c.object
<CustomObject>
    <description>Holds a Geo cordinate, and information to build a balloon for this point</description>
    <label>Geo Location</label>
    <nameField>
        <label>Geo Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</description>
        <inlineHelpText>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</inlineHelpText>
        <label>City, ST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Geo Location object which stores Latitude, Longitude values</description>
        <label>Geo Location</label>
        <referenceTo>Geo_Location__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code_s__c</fullName>
        <inlineHelpText>Multiple Zip Codes should be Separate Gives</inlineHelpText>
        <label>Location by Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/dc_Give_GeoCodeBatchProcessor.cls
global class dc_Give_GeoCodeBatchProcessor implements Database.Batchable<sObject> {
   
   	global String batchQuery;
	global Boolean isTest = false;
	
   global dc_Give_GeoCodeBatchProcessor(){
   			batchQuery='select id, Zip_Code_s__c, city__c, Geo_Location__c from give__c where Zip_Code_s__c != null and Geo_Location__c = null';
			System.debug('batchQuery='+batchQuery);
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(batchQuery);
   }
   
   global void execute(Database.BatchableContext BC, List<sObject> scope){
      
      try{
      List<Geo_Location__c> listgeoloc = new List<Geo_Location__c>();
      integer counter =0;
      double latitude;
	  double longitude;
	  List<Give__c> givelist = new List<Give__c>();
	  List<Give__c> updgive = new List<Give__c>();
      for(Sobject s : scope)
      {
      		Give__c s_give = (Give__c) s;
      		givelist = [Select id, Geo_Location__c from Give__c where Zip_Code_s__c =: s_give.Zip_Code_s__c and Geo_Location__c != null limit 1];
      		if(givelist.size() > 0 && !isTest)
      		{
      			s_give.Geo_Location__c = givelist[0].Geo_Location__c;
      			update s;
      		}
      }      
   }
   catch(exception e){}
   }
   

   global void finish(Database.BatchableContext BC){

   }

}