prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</description>
        <inlineHelpText>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</inlineHelpText>
        <label>City, ST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Description__c</fullName>
        <description>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</description>
        <inlineHelpText>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</inlineHelpText>
        <label>Location or Venue</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location_by_State_s__c</fullName>
        <description>E.g. “NY, CT, NJ, VA, DC”.</description>
        <inlineHelpText>E.g. “NY, CT, NJ, VA, DC”.</inlineHelpText>
        <label>Location by State(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/GeoUtils.cls
public class GeoUtils {
	// generate a KML string given a page reference, call getContent() 
	// then cleanup the output.
	public static string generateFromContent(PageReference pr) { 
		string ret = ''; 
		try {  
	        ret = (string) pr.getContent().toString();
			
			ret = ret.replaceAll('"','\'' ); // get content produces quote chars \"  
	        ret = ret.replaceAll( '&','&amp;');// we need to escape these in the node value
        } catch (exception e ) { 
        	system.debug( 'ERROR '+e); 
        }
   		
   		ret = ret.replaceAll('\n',' ');	// must use ALL since many new line may get 
        ret = ret.replaceAll('\r',' ');	// get these also!
      //  system.debug( ret); // dump the KML 
        return ret ;
	}
	
	public static Map<String, String> geo_response = new Map<String, String>{'200'=>'G_GEO_SUCCESS',
    '400'=>'G_GEO_BAD_REQUEST',
    '500'=>'G_GEO_SERVER_ERROR',
    '601'=>'G_GEO_MISSING_ADDRESS',
    '602'=>'G_GEO_UNKNOWN_ADDRESS',
    '603'=>'G_GEO_UNAVAILABLE_ADDRESS',
    '604'=>'G_GEO_UNKNOWN_DIRECTIONS',
    '610'=>'G_GEO_BAD_KEY',
    '620'=>'G_GEO_TOO_MANY_QUERIES'
    };
        
	public static string accountAddressString ( give__c give ) {
    	// form an address string given an account object
    	string adr = give.Location_Description__c + ',' + give.City__c + ',' + give.Location_by_State_s__c; 
       // if ( acct.billingcountry != null ) adr += ',' + acct.billingcountry; 
        adr = adr.replaceAll('\"', '' );
        adr = adr.replaceAll('\'', '' );
        adr = adr.replaceAll( '\n', ' ' );    
        adr = adr.replaceAll( '\r', ' ' );    
        system.debug( adr );  
        return adr;	
    }
     
	public static testmethod void t1() { 
		PageReference pageRef =  Page.kmlPreviewTemplate;
        Test.setCurrentPage(pageRef);
        Partnership_Request__c PR = new Partnership_Request__c();
    	PR = [select id from Partnership_Request__c where Public_Partner_Name__c!=null limit 1];
        system.assert ( GeoUtils.generateFromContent( pageRef ) != null );
        Give__c a =  new Give__c( name='foo', Partnership_Request__c = PR.id, Location_Description__c='main', city__c='springfield',Location_by_State_s__c='il'
         );//,billingcountry='us');
        insert a;
        system.assertEquals( 'main,springfield,il',accountAddressString( a) );
       
	}
}