prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/test_dc_ctrl_RewardDetails.cls
@isTest
private class test_dc_ctrl_RewardDetails {

    static testMethod void testController() {
    	Give__c give = test_Utilities.createSimpleGive();
    	Give_Instance__c instance = test_Utilities.createSimpleGiveInstance(give);
    	
    	ApexPages.currentPage().getParameters().put('giveid', give.Id);
    	
    	Test.startTest();
    	
    	dc_ctrl_RewardDetails rd = new dc_ctrl_RewardDetails();
    	
    	rd.givedetlist();
    	
    	rd.setgiveid(give.id);
    	
    	List<dc_CustomGive> giveList = rd.getGiveList();
    	giveList = rd.getGiveInstList();
    	String s = rd.getPartnerLogo();
    	
    	rd.its();
    	
    	Test.stopTest();
    	
    }
}