prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Request__c.object
<CustomObject>
    <description>Connects applicants to give</description>
    <fields>
        <fullName>Give_Instance__c</fullName>
        <label>Give Instance</label>
        <referenceTo>Give_Instance__c</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Give Request</label>
    <nameField>
        <displayFormat>GR-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Give Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/test_dcctrlext_GiveInstMassRequests.cls
@isTest
private class test_dcctrlext_GiveInstMassRequests {

    static testMethod void testController() {
       	Contact con = test_Utilities.createSimpleContact('doe', 'test@test.com', '12345');
    	
    	Give__c give = test_Utilities.createSimpleGive();
    	Give_Instance__c instance = test_Utilities.createSimpleGiveInstance(give);
        Give_Request__c request = test_Utilities.createSimpleGiveRequest(give, instance, con);
        
        PageReference pageRef = Page.dc_ReConfirm;
        pageRef.getParameters().put('instanceId', instance.Id);
        
        Test.setCurrentPage(pageRef);
    	
    	Test.startTest();    	
    	
        dc_ctrl_ext_GiveInstanceMassRequests controller = new dc_ctrl_ext_GiveInstanceMassRequests();
        
        controller.selectedStage = 'Give requested';
        controller.selectedEndStage = 'Give requested';
        controller.selectedStartStage = 'Give requested';
        
        List<SelectOption> stageOptions = controller.stageOptions;
        Give_Request__c[] requests = controller.requests;
        List<dc_ctrl_ext_GiveInstanceMassRequests.RequestSelect> requestselects = controller.requestSelects;
        Id id = controller.instanceId;
        
        controller.updateSelectedStage();
        controller.massUpdateStage();
        
        Test.stopTest();
    }
}