prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>Best_Status__c</fullName>
        <description>This field contains the best status of all Give Instances.  3 if at least one Give Instance is Open, 2 if none are open but at least one is waitlisted, 1 if all at closed.</description>
        <inlineHelpText>This field contains the best status of all Give Instances.  3 if at least one Give Instance is Open, 2 if none are open but at least one is waitlisted, 1 if all at closed.</inlineHelpText>
        <label>Best Status</label>
        <summarizedField>Give_Instance__c.Numerical_Status__c</summarizedField>
        <summaryForeignKey>Give_Instance__c.Give__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Giveaways</fullName>
                </value>
                <value>
                    <fullName>Discounts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location_Street_Address__c</fullName>
        <description>Street address of the venue (so it can be mapped).</description>
        <inlineHelpText>Street address of the venue (so it can be mapped).</inlineHelpText>
        <label>Location Street Address</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>National_Give__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overides zip codes and states.</description>
        <inlineHelpText>Overrides zip codes and states.</inlineHelpText>
        <label>National Give</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <label>Num. Units</label>
        <summarizedField>Give_Instance__c.Number_of_Units__c</summarizedField>
        <summaryForeignKey>Give_Instance__c.Give__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed Visible</fullName>
                </value>
                <value>
                    <fullName>Closed Invisible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Come First Served</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Screened Give</fullName>
                </value>
                <value>
                    <fullName>Unlimited Give</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code_s__c</fullName>
        <inlineHelpText>Multiple Zip Codes should be Separate Gives</inlineHelpText>
        <label>Location by Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <description>Quantity of give items available.</description>
        <inlineHelpText>Quantity of give items available.</inlineHelpText>
        <label>Num. Units</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The associated date of this give instance or start date of range.</description>
        <inlineHelpText>The associated date of this give instance or start date of range.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/IAVAEvent__c.object
<CustomObject>
    <fields>
        <fullName>Dont_create_Chatter_Group__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked (default) do not automatically create a chatter group for event communication.</description>
        <inlineHelpText>If checked (default) do not automatically create a chatter group for event communication.</inlineHelpText>
        <label>Don&apos;t create Chatter Group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Public_Details__c</fullName>
        <label>Event Public Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Relative_URL__c</fullName>
        <description>Relative URL for main event page (used so code can pull from a single source and when URL algorithm changes, can just change it in this formula)</description>
        <formula>&apos;cov_event?id=&apos; + Id</formula>
        <inlineHelpText>Relative URL for main event page (used so code can pull from a single source and when URL algorithm changes, can just change it in this formula)</inlineHelpText>
        <label>Event Relative URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location_City__c</fullName>
        <label>Location City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Street_Address__c</fullName>
        <label>Location Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Venue__c</fullName>
        <label>Location Venue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Zip_Code__c</fullName>
        <inlineHelpText>Required if you want event to be located in geographic/zip searches.</inlineHelpText>
        <label>Location Zip Code (important)</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Organizer_Type__c</fullName>
        <label>Organizer Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Distributed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unpublished</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Flagged/Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Thumbnail_image_URL__c</fullName>
        <description>When the user uploads a new photo to a published group, the URL of the thumbnail version is inserted here and takes precedence over any attached thumbnail images.</description>
        <inlineHelpText>When the user uploads a new photo to a published group, the URL of the thumbnail version is inserted here and takes precedence over any attached thumbnail images. For an external site use a secure HTTPS link to prevent a secure site certificate error.</inlineHelpText>
        <label>Thumbnail image URL (automatic) - HTTPS</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Awareness Action</fullName>
                </value>
                <value>
                    <fullName>Bar Gathering</fullName>
                </value>
                <value>
                    <fullName>Career Development</fullName>
                </value>
                <value>
                    <fullName>Concert</fullName>
                </value>
                <value>
                    <fullName>Cookout</fullName>
                </value>
                <value>
                    <fullName>DPAA Burial</fullName>
                </value>
                <value>
                    <fullName>Fundraiser</fullName>
                </value>
                <value>
                    <fullName>Internal IAVA Training</fullName>
                </value>
                <value>
                    <fullName>Movie Screening</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outdoor Activity</fullName>
                </value>
                <value>
                    <fullName>Parade</fullName>
                </value>
                <value>
                    <fullName>Run</fullName>
                </value>
                <value>
                    <fullName>Seminar/Education</fullName>
                </value>
                <value>
                    <fullName>Service Project</fullName>
                </value>
                <value>
                    <fullName>Social</fullName>
                </value>
                <value>
                    <fullName>Sporting Event</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>VetTogether</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Partnership Start Date.</description>
        <inlineHelpText>Partnership Start Date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/cov_event_marker_feed_controller_TESTS.cls
@isTest
private class cov_event_marker_feed_controller_TESTS
{

	@isTest
	static void test_event_marker_feed()
	{

		IAVAEvent__c e1 = new IAVAEvent__c(
			Name='Test VT 1'
			, Type__c='VetTogether'
			, Status__c = 'Published'
			, Dont_create_Chatter_Group__c = false
			, Organizer_Type__c = 'Distributed'
			, Event_Public_Details__c ='These are the public details for e1'
			, Event_Date__c = System.today().addDays(3)
			);
		insert e1;
		System.debug('e1: ' + e1);

		IAVAEvent__c e2 = new IAVAEvent__c(
			Name='Test Social 2'
			, Type__c='Social'
			, Status__c = 'Unpublished'
			, Organizer_Type__c = 'Distributed'
			, Event_Public_Details__c ='These are the public details for e2'
			, Event_Date__c = System.today().addDays(2)
			);
		insert e2;
		System.debug('e2: ' + e2);

		IAVAEvent__c e3 = new IAVAEvent__c(
			Name='Test Support 3'
			, Type__c='Support'
			, Status__c = 'Published'
			, Organizer_Type__c = 'Distributed'
			, Event_Public_Details__c ='These are the public details for e3'
			, Event_Date__c = System.today().addDays(-38)
			);
		insert e3;
		System.debug('e3: ' + e3);


    	// now test that Give events get included on dashboard
        Partnership_Request__c p = new Partnership_Request__c(Name='Test Partnership', Public_Partner_Name__c='Test Public Name');
		insert p;
		Give__c g1 = new Give__c(Name='Test Give', National_Give__c = true, Partnership_Request__c = p.Id, Category__c='Events', Status__c='Open');
		//insert g1;
		Give__c g2 = new Give__c(Name='Test Give 2', National_Give__c = true, Partnership_Request__c = p.Id, Category__c = 'Giveaways');
		//insert g2;
		Give__c g3 = new Give__c(Name='Test Give 3', Status__c='Waitlist', Category__c = 'Events', Latitude__c=37.778687100000000, Longitude__c=-122.421242399999980, Zip_Code_s__c='94102', National_Give__c = false, Partnership_Request__c = p.Id);
		//insert g3;
		Give__c g4 = new Give__c(Name='Test Give 4', Status__c='Closed Invisible', National_Give__c = true, Partnership_Request__c = p.Id, Category__c = 'Events');
		//insert g4;
		insert new List<Give__c>{ g1, g2, g3, g4 };
		//system.debug('g4 v1: ' + [select Id, Status__c, Best_Status__c, (select Status__c from Give_Instances__r) from Give__c where Id = :g4.Id]);

		Give_Instance__c g1i1 = new Give_Instance__c(Give__c = g1.Id, Number_of_Units__c=5, Status__c='Open', Start_Date__c=System.today().addDays(-10));
		Give_Instance__c g1i2 = new Give_Instance__c(Give__c = g1.Id, Number_of_Units__c=5, Status__c='Open', Start_Date__c=System.today().addDays(10));
		Give_Instance__c g1i3 = new Give_Instance__c(Give__c = g1.Id, Number_of_Units__c=5, Status__c='Open', Start_Date__c=System.today().addDays(2));

		Give_Instance__c g2i1 = new Give_Instance__c(Give__c = g2.Id, Number_of_Units__c=3, Status__c='Open', Start_Date__c=System.today().addDays(-35));

		Give_Instance__c g3i1 = new Give_Instance__c(Give__c = g3.Id, Number_of_Units__c=3, Status__c='Open', Start_Date__c=System.today().addDays(45));

		Give_Instance__c g4i1 = new Give_Instance__c(Give__c = g4.Id, Number_of_Units__c=0, Status__c='Closed', Start_Date__c=System.today().addDays(5));

		insert new List<Give_Instance__c>{ g1i1, g1i2, g1i3, g2i1, g3i1, g4i1 };

		//Give__c queryGive = [select Id, Status__c, Best_Status__c, (select Status__c from Give_Instances__r) from Give__c where Id = :g4.Id];
		//system.debug('g4 v2: ' + queryGive);
		//system.debug('g4 instances size: ' + queryGive.Give_Instances__r.size());
		//system.debug('queryGive.Give_Instances__r[0]: ' + queryGive.Give_Instances__r[0]);



		User guestUser = cov_user_TEST_utility.getGuestUser();

		System.runAs(guestUser) {
			cov_event_marker_feed_controller controller = new cov_event_marker_feed_controller();

			// event e1 should show up but not e2 (unpublished) or c3 (too old)
			// give g1 should show up but not g2 (too old) or g3 (too far in advance) or g4 (closed)
			system.debug('controller.markers: ' + controller.markers);
			system.assertEquals(2, controller.markers.size());

			Map<Id, cov_event_marker_feed_controller.marker> markerMap = loadMap(controller.markers);
			system.assertEquals(true, compareEventAndMarker(e1, markerMap.get(e1.Id)));
			system.assertEquals(true, compareGiveAndMarker(g1, markerMap.get(g1.Id)));


			PageReference pageRef = Page.cov_event_marker_feed;
	        Test.setCurrentPage(pageRef);
	        ApexPages.CurrentPage().getParameters().put('startdate', String.valueOf(g2i1.Start_Date__c));
			
			controller = new cov_event_marker_feed_controller();

			// g2 should now show up since startdate goes back far enough
			system.debug('controller.markers: ' + controller.markers);
			system.assertEquals(3, controller.markers.size());
			markerMap = loadMap(controller.markers);
			system.assertEquals(true, compareEventAndMarker(e1, markerMap.get(e1.Id)));
			system.assertEquals(null, markerMap.get(e2.Id));
			system.assertEquals(null, markerMap.get(e3.Id));
			system.assertEquals(true, compareGiveAndMarker(g1, markerMap.get(g1.Id)));
			system.assertEquals(true, compareGiveAndMarker(g2, markerMap.get(g2.Id)));
			system.assertEquals(null, markerMap.get(g3.Id));
			system.assertEquals(null, markerMap.get(g4.Id));


			ApexPages.CurrentPage().getParameters().put('startdate', String.valueOf(e3.Event_Date__c));
			ApexPages.CurrentPage().getParameters().put('enddate', String.valueOf(System.today()));
			
			controller = new cov_event_marker_feed_controller();

			// e3 should now show up since startdate goes back far enough
			// but e1 should not since enddate is before it starts
			system.debug('controller.markers: ' + controller.markers);
			system.assertEquals(3, controller.markers.size());
			markerMap = loadMap(controller.markers);
			system.assertEquals(null, markerMap.get(e1.Id));
			system.assertEquals(null, markerMap.get(e2.Id));
			system.assertEquals(true, compareEventAndMarker(e3, markerMap.get(e3.Id)));
			system.assertEquals(true, compareGiveAndMarker(g1, markerMap.get(g1.Id)));
			system.assertEquals(true, compareGiveAndMarker(g2, markerMap.get(g2.Id)));
			system.assertEquals(null, markerMap.get(g3.Id));
			system.assertEquals(null, markerMap.get(g4.Id));

		}
	
		e2.Status__c = 'Published';
		update e2;
		g4i1.Status__c = 'Open';
		update g4i1; // show open g4 via workflow

		System.runAs(guestUser) {

			PageReference pageRef = Page.cov_event_marker_feed;
	        Test.setCurrentPage(pageRef);

			ApexPages.CurrentPage().getParameters().put('startdate', String.valueOf(System.today()));
			ApexPages.CurrentPage().getParameters().put('enddate', String.valueOf(System.today().addDays(50)));
			
			cov_event_marker_feed_controller controller = new cov_event_marker_feed_controller();

			// e1 should show up
			// e2 show show up now since published
			// e3 no since too old
			// g1 should show up
			// g2 no (too old)
			// g3 should show up now since end date is after
			// g4 should show up since now open
			system.debug('controller.markers: ' + controller.markers);
			system.assertEquals(5, controller.markers.size());
			Map<Id, cov_event_marker_feed_controller.marker> markerMap = loadMap(controller.markers);
			system.assertEquals(true, compareEventAndMarker(e1, markerMap.get(e1.Id)));
			system.assertEquals(true, compareEventAndMarker(e2, markerMap.get(e2.Id)));
			system.assertEquals(null, markerMap.get(e3.Id));
			system.assertEquals(true, compareGiveAndMarker(g1, markerMap.get(g1.Id)));
			system.assertEquals(null, markerMap.get(g2.Id));
			system.assertEquals(true, compareGiveAndMarker(g3, markerMap.get(g3.Id)));
			system.assertEquals(true, compareGiveAndMarker(g4, markerMap.get(g4.Id)));


			// test for invalid parameters
			ApexPages.CurrentPage().getParameters().put('startdate', 'ham');
			ApexPages.CurrentPage().getParameters().put('enddate', 'sandwich');

			controller = new cov_event_marker_feed_controller();

			// should go back to default start/end dates
			// e1 and e2 yes, e3 no (too old)
			// g1, g4 yes, g2 no (too old), g3 no (too far in advance)
			system.debug('controller.markers: ' + controller.markers);
			system.assertEquals(4, controller.markers.size());
			markerMap = loadMap(controller.markers);
			system.assertEquals(true, compareEventAndMarker(e1, markerMap.get(e1.Id)));
			system.assertEquals(true, compareEventAndMarker(e2, markerMap.get(e2.Id)));
			system.assertEquals(null, markerMap.get(e3.Id));
			system.assertEquals(true, compareGiveAndMarker(g1, markerMap.get(g1.Id)));
			system.assertEquals(null, markerMap.get(g2.Id));
			system.assertEquals(null, markerMap.get(g3.Id));
			system.assertEquals(true, compareGiveAndMarker(g4, markerMap.get(g4.Id)));


		}


	}

	static Boolean compareEventAndMarker(IAVAEvent__c evt, cov_event_marker_feed_controller.marker marker) {

		// requery to get all fields
		IAVAEvent__c evnt = [select Id, Name, Event_Date__c, Event_Relative_URL__c, Type__c, Thumbnail_image_URL__c
							, Location_Venue__c, Location_Street_Address__c, Location_City__c, Location_Zip_Code__c
							, Latitude__c, Longitude__c
							from IAVAEvent__c where Id = :evt.Id limit 1];

		system.debug('comparing Event and marker');
		system.debug('evnt: ' + evnt);
		system.debug('marker: ' + marker);
		if (evnt.Id != marker.recordId) return false;
		if (evnt.Name != marker.Name) return false;
		if (evnt.Event_Date__c.format() != marker.theDate) return false;
		if (Site.getBaseUrl() + '/' + evnt.Event_Relative_URL__c != marker.link) return false;
		if (evnt.Type__c != marker.type) return false;
		if (evnt.Thumbnail_image_URL__c != marker.imageURL) return false;
		if (evnt.Location_Venue__c != marker.venue) return false;
		if (evnt.Location_Street_Address__c != marker.street) return false;
		if (evnt.Location_City__c != marker.city) return false;
		if (evnt.Location_Zip_Code__c != marker.postalcode) return false;
		if (evnt.Latitude__c != marker.lat) return false;
		if (evnt.Longitude__c != marker.lon) return false;

		return true;
	}

	static Boolean compareGiveAndMarker(Give__c giv, cov_event_marker_feed_controller.marker marker) {

		Give__c g = [select Id, Name, Subcategory__c, Category__c, Earliest_Start_Date__c, Latest_End_Date__c
					, Location_Description__c, Location_Street_Address__c, City_Formula__c, Zip_Code__c, Latitude__c, Longitude__c
					, (select Id from Attachments)
					from Give__c where Id = :giv.Id limit 1];

		system.debug('comparing Give and marker');
		system.debug('g: ' + g);
		system.debug('marker: ' + marker);

		if (g.Id != marker.recordId) return false;
		if (g.Name != marker.Name) return false;
		if ('https://my.iava.org/cov_reward?giveid=' + g.Id != marker.link) return false;
		String typeValue = g.Subcategory__c != null ? g.Subcategory__c : g.Category__c;
		if (typeValue != marker.type) return false;
		String imageValue = g.Attachments.size() == 0 ? null : 'http://my.iava.org/servlet/servlet.FileDownload?file=' + g.Attachments[0].Id;
		if (imageValue != marker.imageURL) return false;
		if (g.Location_Description__c != marker.venue) return false;
		if (g.Location_Street_Address__c != marker.street) return false;
		if (g.City_Formula__c != marker.city) return false;
		if (g.Zip_Code__c != marker.postalcode) return false;
		if (g.Latitude__c != marker.lat) return false;
		if (g.Longitude__c != marker.lon) return false;

		String theDate;
		if (g.Earliest_Start_Date__c != null) {
			if (g.Earliest_Start_Date__c < System.today() && g.Latest_End_Date__c > System.today()) {
				// this might be strange if today is in between start/end dates of different instances, but close enough for now
				theDate = System.today().format();
			} else {
				theDate = g.Earliest_Start_Date__c.format();
			}
		}
		if (theDate != marker.theDate) return false;

		return true;
	}	

	// helper method to load the markers result into a map that allows each marker's result to be pulled by its key
	static Map<Id, cov_event_marker_feed_controller.marker> loadMap(List<cov_event_marker_feed_controller.marker> markerArg) {
		Map<Id, cov_event_marker_feed_controller.marker> returnMap = new Map<Id, cov_event_marker_feed_controller.marker>();
		for (cov_event_marker_feed_controller.marker mrk : markerArg) {
			returnMap.put(mrk.recordId, mrk);
		}
		return returnMap;
	}


}