prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>National_Give__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overides zip codes and states.</description>
        <inlineHelpText>Overrides zip codes and states.</inlineHelpText>
        <label>National Give</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/geoApiKey.cls
/* 
 * Sign up for a key at this location: 
 * http://code.google.com/apis/maps/signup.html
 * place the in this file
 * the forcekey should specify *.force.com as the domain for any visualforce pages
 * the key should specify *.salesforce.com for geocode requests that start on the server
 */
 
public class geoApiKey {
	public geoApiKey() {}
	public geoApiKey(ApexPages.StandardController c) {}
	public geoApiKey(ApexPages.StandardSetController c) {}
	
	// salesforce key
	private static string k  = 'ABQIAAAAztVBfkQpR0ADsDMoBIuFHhQdMY-rqcBK7mOLf4exckLw5w98-BTuHDgP6ooNF9j0bKgAnsA_OsN7HQ';
	private static string client = 'client=gme-salesforcefoundation';
	// *.salesforce.com 
    public string key 		{ get { return k; }}
    // *.force.com 
    public string forcekey 	{ get { return k; }}
 	
 	public static string jsapi_script { 
 		get { return 'http://www.google.com/jsapi?' +client + '&key=' + k; }}
 	public static string maps_script { 
 		get { return 'http://maps.google.com/maps?file=api&v=2&' +client; }}
 	
 	public static testmethod void t1() { 
 		geoApiKey g = new geoApiKey(); 
 		system.assert( g.key != null );
 		system.assert( g.forcekey != null );
 		ApexPages.StandardController sc = new ApexPages.StandardController(new Give__c());
 		g = new geoApiKey( sc);
 		Partnership_Request__c PR = new Partnership_Request__c();
    	PR = [select id from Partnership_Request__c where Public_Partner_Name__c!=null limit 1];
 		insert new Give__c( name='foo',Partnership_Request__c = PR.id, national_give__c = true); 
 		List<Give__c> giveList = [SELECT name FROM Give__c LIMIT 1];
		ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(giveList);
		g = new geoApiKey( ssc); 
 	}
}