prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>Collect_Guest_DL_Num__c</fullName>
        <description>This field will be used to indicate if the guest Drivers License number is to be collected.</description>
        <inlineHelpText>Indicate if the guest Drivers License number is to be collected.</inlineHelpText>
        <label>Collect Guest DL Num</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Guest_DOB__c</fullName>
        <description>This field will be used to indicate if the member DOB is to be collected.</description>
        <inlineHelpText>Indicate if the member DOB is to be collected.</inlineHelpText>
        <label>Collect Guest DOB</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Guest_Name__c</fullName>
        <label>Collect Guest Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don&apos;t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Guest_Shirt_Size__c</fullName>
        <description>This field will be used to indicate if the guest shirt size is to be collected.</description>
        <inlineHelpText>Indicate if the guest shirt size is to be collected.</inlineHelpText>
        <label>Collect Guest Shirt Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Member_DL_Num__c</fullName>
        <description>This field will be used to indicate if the guest Drivers License number is to be collected.</description>
        <inlineHelpText>Indicate if the guest Drivers License number is to be collected.</inlineHelpText>
        <label>Collect Member DL Num</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Member_DOB__c</fullName>
        <description>This field will be used to indicate if the member DOB is to be collected.</description>
        <inlineHelpText>Indicate if the member DOB is to be collected.</inlineHelpText>
        <label>Collect Member DOB</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Collect_Member_Shirt_Size__c</fullName>
        <description>This field will be used to indicate if the guest shirt size is to be collected.</description>
        <inlineHelpText>Indicate if the guest shirt size is to be collected.</inlineHelpText>
        <label>Collect Member Shirt Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>don’t collect</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>at request</fullName>
                </value>
                <value>
                    <fullName>at re-confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Maximum_Units_per_Member__c</fullName>
        <description>If greater than 1 and &quot;Member Cannot Select Quantity&quot; is unchecked, member can choose desired quantity of units up to this maximum,  If blank, quantity is unlimited.</description>
        <inlineHelpText>If greater than 1 and &quot;Member Cannot Select Quantity&quot; is unchecked, member can choose desired quantity of units up to this maximum,  If blank, quantity is unlimited.</inlineHelpText>
        <label>Maximum Units per Member</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Must_be_21__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Requires member verifies 21+ age during Give Request.</description>
        <inlineHelpText>Requires member verifies 21+ age during Give Request.</inlineHelpText>
        <label>Must be 21+</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Must_be_21_for_guest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Must be 21 for guest</label>
        <type>Checkbox</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Request__c.object
<CustomObject>
    <description>Connects applicants to give</description>
    <fields>
        <fullName>Give_Instance__c</fullName>
        <label>Give Instance</label>
        <referenceTo>Give_Instance__c</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Give Request</label>
    <nameField>
        <displayFormat>GR-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Give Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/test_dc_ctrl_reconfirm.cls
@isTest
private class test_dc_ctrl_reconfirm {

    static testMethod void testController() {       
        Give__c give = test_Utilities.createSimpleGive();
        give.Collect_Guest_Name__c = 'at re-confirm';
        give.Collect_Guest_DL_Num__c = 'at re-confirm';
        give.Collect_Guest_DOB__c = 'at re-confirm';
        give.Collect_Guest_Shirt_Size__c = 'at re-confirm';
        give.Collect_Member_DL_Num__c = 'at re-confirm';
        give.Collect_Member_DOB__c = 'at re-confirm';
        give.Collect_Member_Shirt_Size__c = 'at re-confirm';
        
        give.Must_be_21__c = true;
        give.Must_be_21_for_guest__c = true;
        
        update give;
        
        Give_Instance__c instance = test_Utilities.createSimpleGiveInstance(give);
                
        Contact con = test_Utilities.createSimpleContact('last', 'test@test.com', '12345');
        
        Give_Request__c request = test_Utilities.createSimpleGiveRequest(give, instance, con);
        
        test_Utilities.createSimpleGuest(request, con);
        
        PageReference pageRef = Page.dc_ReConfirm;

        Test.setCurrentPage(pageRef);
        
        
        //rucksack/dc_ReConfirm?GiveRequestID=a0JS0000001WlGY&ContactID=003S000000OyQ57&PageAction=confirmation
        
        
        System.debug(System.LoggingLevel.INFO, 'GiveRequest: ' + request.Id);
        System.debug(System.LoggingLevel.INFO, 'ContactId: ' + con.Id);
        
        ApexPages.currentPage().getParameters().put('GiveRequestId', request.Id);
        ApexPages.currentPage().getParameters().put('ContactID', con.Id);
        ApexPages.currentPage().getParameters().put('PageAction', 'confirmation');
        ApexPages.currentPage().getParameters().put('instanceid', instance.id);
        ApexPages.currentPage().getParameters().put('mem-id', '12345');
        ApexPages.currentPage().getParameters().put('email', 'test@test.com');
        ApexPages.currentPage().getParameters().put('giveid', give.Id);
        
        
        Test.startTest();
        dc_Request_Page_Handler t = new dc_Request_Page_Handler();
        
        dc_ctrl_reconfirm controller = new dc_ctrl_reconfirm();
        controller.loadContact(con.Id);
        controller.confirm = 'yes';
        
        controller.submitrequest();
        controller.joinContactMailingAddress();
        
        controller.age_y = true;
        controller.guest_age_y = true;
        
        PageReference pr = controller.redirectOnSave();
        Boolean s = controller.getShouldShowReConfirmedMessage();
        s = controller.getShouldShowCancelledMessage();
        String s1 = controller.getdc_reconfirmed_confirmation_message();
        s1 = controller.getdc_cancelled_confirmation_message();
        List<SelectOption> options = controller.getAge();
        controller.age_y();
        controller.age_n();
        s = controller.getHasPersonalDetails();
        s = controller.getHasSpecialQuestions();
        s = controller.getPromptForGuests();
        s = controller.getShouldShowReConfirmBody();
        s = controller.getShouldShowReadonlyFields();
        s = controller.getShouldShowHeader();
        s = controller.getShouldShowConfirmationQuestion();
        s = controller.getShouldShowAlreadyConfirmed();
        s = controller.getShouldShowCancelled();
        s = controller.getShouldShowGuestsDivider();
        
        options = controller.getStateOptions();
        options = controller.getYesNoOptions();
        s1 = controller.getLogo();
        s1 = controller.getDefaultLogo();
        s1 = controller.getWhen();
        s1 = controller.getWhere();
        s1 = controller.getQuantity();
        s1 = controller.getDeadline();
        s1 = controller.getAgeLimit();
        options = controller.getTicketOptions();
        options = controller.getShirtSizeOptions();
        options = controller.getStateOptions();
        controller.refreshGuests();
        
        pr = controller.its();
        pr = controller.its_conf();
        
        options = controller.getInstanceOptions();
        s = controller.getMultipleInstances();
        
        s1 = controller.getSpecialInstructions2();
        s1 = controller.getSpecialInstructions3();
        s1 = controller.getSpecialInstructions4();
        s1 = controller.getSpecialInstructions5();
        
        s = controller.getPromptForGuestAge21();
        s = controller.getCollectMemberAgeVerification();
        
        s = controller.getCollectSpecialResponse();
        s = controller.getCollectSpecialResponse2();
        s = controller.getCollectSpecialResponse3();
        s = controller.getCollectSpecialResponse4();
        s = controller.getCollectSpecialResponse5();
        
        s = controller.getCollectGuestDLNum();
        s = controller.getCollectGuestDOB();
        s = controller.getCollectGuestName();
        s = controller.getCollectGuestShirtSize();
        s = controller.getCollectMemberAgeVerification();
        s = controller.getCollectMemberDLNum();
        s = controller.getCollectMemberDOB();
        s = controller.getCollectMemberShirtSize();
        s = controller.getCollectQuantity();

		controller.ticketValue = 10;
        controller.selectedNumberOfGuests = 10;
        controller.refreshGuests();
        controller.ticketValue = 5;
        controller.selectedNumberOfGuests = 5;
        controller.refreshGuests();
        
        s = controller.commitGuests();
        
        
        controller.give.Maximum_Units_per_Member__c = null;
        s1 = controller.getQuantity();
        
        Test.stopTest();
    }
    
    private static testMethod void testCtrlTemplate() {
    	dc_ctrl_template tmp = new dc_ctrl_template();
    	String s = tmp.gettitle();
    	s = tmp.getoldieversion();
    	s = tmp.getMacos();
    }
}