prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</description>
        <inlineHelpText>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</inlineHelpText>
        <label>City, ST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fulfillment_Instructions_for_Winner__c</fullName>
        <description>E.g. &quot;Pick up your tickets at Will Call on the date of the event.&quot;</description>
        <inlineHelpText>E.g. &quot;Pick up your tickets at Will Call on the date of the event.&quot;</inlineHelpText>
        <label>Fulfillment Instruct for Winner (deprec)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</description>
        <inlineHelpText>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</inlineHelpText>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</description>
        <inlineHelpText>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</inlineHelpText>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give_Name__c</fullName>
        <formula>Give__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Give Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Request__c.object
<CustomObject>
    <description>Connects applicants to give</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Street Address</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirmed_21__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the applicant confirmed age 21+ (only relevant on 21+ gives)</description>
        <inlineHelpText>Checked if the applicant confirmed age 21+ (only relevant on 21+ gives)</inlineHelpText>
        <label>Confirmed 21+</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_ID_plus_Give_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>A workflow sets this value in order to prevent more than one Give Request with confirmation stage for the same Give and Applicant.</description>
        <inlineHelpText>A workflow sets this value in order to prevent more than one Give Request with confirmation stage for the same Give and Applicant.</inlineHelpText>
        <label>Contact ID plus Give ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Give_Instance_Start_Date__c</fullName>
        <formula>Give_Instance__r.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Give Instance Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Give_Instance__c</fullName>
        <label>Give Instance</label>
        <referenceTo>Give_Instance__c</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Give_Name__c</fullName>
        <formula>Give_Instance__r.Give__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Give Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make_Address_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Make Address Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Make_Email_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when user requests that their email address become the primary email on the account</description>
        <inlineHelpText>Checked when user requests that their email address become the primary email on the account</inlineHelpText>
        <label>Make Email Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes</description>
        <inlineHelpText>Notes</inlineHelpText>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Special_Response__c</fullName>
        <description>If Give required special response it is stored here.</description>
        <inlineHelpText>If Give required special response it is stored here.</inlineHelpText>
        <label>Special Response #1 (at request)</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Give requested</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Wait-list</fullName>
                </value>
                <value>
                    <fullName>Tentative confirmation</fullName>
                </value>
                <value>
                    <fullName>Final confirmation</fullName>
                </value>
                <value>
                    <fullName>Information sent</fullName>
                </value>
                <value>
                    <fullName>Info requested of member</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Units_Requested__c</fullName>
        <label>Units Requested</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Give Request</label>
    <nameField>
        <displayFormat>GR-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Give Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/classes/dc_ctrl_ext_GiveInstanceMassRequests.cls
public with sharing class dc_ctrl_ext_GiveInstanceMassRequests {

    public final Give_Instance__c instance      {get;set;}
    public String selectedStage                 {get;set;}
    public String selectedStartStage            {get;set;}
    public String selectedEndStage              {get;set;}
    
    public List<SelectOption> stageOptions{
        get{
            if(stageOptions==null){
                stageOptions = new List<SelectOption>();
                stageOptions.add(new SelectOption('null','--Select One--'));
                for(Schema.Picklistentry entry : Schema.sObjectType.Give_Request__c.fields.Stage__c.getPicklistValues()){
                    stageOptions.add(new SelectOption(entry.getValue(),entry.getLabel()));
                }
            }
            return stageOptions;
        }
        set;
    }
  
 	public Give_Request__c[] requests { 
 		get { 
 			return (List<Give_Request__c>)pgr.getRecords(); 
 		} 
 		set; 
 	}
 	
 	public List<RequestSelect> requestSelects{
        get{
            if(requestSelects==null && !requests.isEmpty()){
                requestSelects = new List<RequestSelect>();
                for(Give_Request__c gr:requests){
                    requestSelects.add(new RequestSelect(gr));
                }
            }
            return requestSelects;
        }
        set;
    }
	
	public ID instanceId {
		get{
			try{
				instanceId = ApexPages.currentPage().getParameters().get('instanceId');
			} catch(Exception e){
				System.debug('******** Invalid InstanceId: '+ApexPages.currentPage().getParameters().get('instanceId'));
				ApexPages.addMessages(e);
			}
			return instanceId;
		}
		set;
	}
	
	public ApexPages.StandardSetController pgr {
	    get {
	      if (pgr == null) pgr = initPager();
	      return pgr;
	      }
	    set;
    }
	
	
	
    /***************************************** Action Methods ******************************************/
    
    public ApexPages.StandardSetController initPager() {
		ApexPages.StandardSetController ret = new ApexPages.StandardSetController(Database.getQueryLocator(
													[Select g.Zip_Code__c, g.Units_Requested__c, g.State__c, g.Stage__c, g.Special_Response__c, g.Secondary_Phone__c, 
							                                g.Primary_Phone__c, g.Notes__c, g.Name, g.Make_Email_Primary__c, g.Make_Address_Primary__c, g.Id, 
							                                g.Give_Name__c, g.Give_Instance__c, g.Give_Instance_Start_Date__c, g.Give_Instance__r.Give__r.Fulfillment_Instructions_for_Winner__c, 
							                                g.Email_Address__c, g.Contact_ID_plus_Give_ID__c, g.Confirmed_21__c, g.City__c, g.Availability__c, 
							                                g.Applicant__c, g.Address__c, g.CreatedDate, g.Num_Confirmed_Give_Requests__c
							                        From Give_Request__c g
							                        WHERE g.Give_Instance__c=:instanceId
							                        ORDER BY Stage__c,CreatedDate]
							                        ));
		ret.setPageSize(250);
		return ret;	
	}
    
    
    public PageReference nextPage() { requestSelects=null; pgr.next(); return null;     }
  	public PageReference prevPage() { requestSelects=null; pgr.previous(); return null; }
    
    public PageReference updateSelectedStage(){
        if(selectedStage!=null && selectedStage!='' && selectedStage!='null' && requestSelects!=null){
            List<Give_Request__c> reqUpdates = new List<Give_Request__c>();
            for(RequestSelect req : requestSelects){
                if(req.checked){
                    req.record.Stage__c=selectedStage;
                    reqUpdates.add(req.record);
                }
            }

            try{
                if(!reqUpdates.isEmpty()) { System.debug('reqUpdates='+reqUpdates); update reqUpdates; }
            } catch(Exception e){
                System.debug(e);            
                ApexPages.addMessages(e);
            } finally {
                requestSelects=null;
            }
        }
        return null;
    }
    
    public PageReference massUpdateStage(){
        if(selectedStartStage!=null && selectedStartStage!='null' && selectedEndStage!=null && selectedEndStage!='null'){
            
        	List<Give_Request__c> updates = new List<Give_Request__c>();
            for(SObject req : pgr.getRecords()){
            	Give_Request__c gr = (Give_Request__c) req;
                if(gr.stage__c==selectedStartStage){
                    gr.stage__c = selectedEndStage;
                    updates.add(gr);
                }
            }
            try{
                if(!updates.isEmpty()) update updates;
            } catch(Exception e){
                System.debug(e);            
                ApexPages.addMessages(e);
            } finally {
            	requestSelects = null;
            }
            
        }
        return null;
    }
    
    
    /***************************************** Helper Class ******************************************/
    public class RequestSelect{
        public Give_Request__c record {get;set;}
        public Boolean checked {get;set;}
        
        public RequestSelect(Give_Request__c obj){
            record = obj;
            checked = false;
        }
    }
}