prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Giveaways</fullName>
                </value>
                <value>
                    <fullName>Discounts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</description>
        <inlineHelpText>E.g. &quot;New York, NY&quot;.  Should be filled out for every Give. Appears on search results to identify Give location.</inlineHelpText>
        <label>City, ST</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <formula>if(isblank(Latest_Application_Deadline__c),&quot;&quot;, 
IF(MONTH(Latest_Application_Deadline__c ) == 1,&quot;Jan&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 2,&quot;Feb&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 3,&quot;Mar&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 4,&quot;Apr&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 5,&quot;May&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 6,&quot;Jun&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 7,&quot;Jul&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 8,&quot;Aug&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 9,&quot;Sep&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 10,&quot;Oct&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 11,&quot;Nov&quot;,
(IF(MONTH(Latest_Application_Deadline__c ) == 12,&quot;Dec&quot;,&quot;&quot;))))))))))))))))))))))) &amp; &quot; &quot; &amp; TEXT(DAY(Latest_Application_Deadline__c )) &amp; &quot;, &quot; &amp; TEXT(YEAR(Latest_Application_Deadline__c ))
)</formula>
        <label>Deadline</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>E.g. “Watch the Orioles take on the Cardinals in a battle of the Birds. Seats are in the lower deck along the third base line.”</description>
        <inlineHelpText>E.g. “Watch the Orioles take on the Cardinals in a battle of the Birds. Seats are in the lower deck along the third base line.”</inlineHelpText>
        <label>Short Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Latest_Application_Deadline__c</fullName>
        <label>Latest Application Deadline</label>
        <summarizedField>Give_Instance__c.Application_Deadline__c</summarizedField>
        <summaryForeignKey>Give_Instance__c.Give__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location_Description__c</fullName>
        <description>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</description>
        <inlineHelpText>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</inlineHelpText>
        <label>Location or Venue</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location_Formula__c</fullName>
        <formula>IF(NOT(National_Give__c),IF(ISBLANK( Zip_Code_s__c ),&quot;Various Locations&quot;, City__c ),&quot;National&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_by_State_s__c</fullName>
        <description>E.g. “NY, CT, NJ, VA, DC”.</description>
        <inlineHelpText>E.g. “NY, CT, NJ, VA, DC”.</inlineHelpText>
        <label>Location by State(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Units_per_Member__c</fullName>
        <description>If greater than 1 and &quot;Member Cannot Select Quantity&quot; is unchecked, member can choose desired quantity of units up to this maximum,  If blank, quantity is unlimited.</description>
        <inlineHelpText>If greater than 1 and &quot;Member Cannot Select Quantity&quot; is unchecked, member can choose desired quantity of units up to this maximum,  If blank, quantity is unlimited.</inlineHelpText>
        <label>Maximum Units per Member</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Must_be_21__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Requires member verifies 21+ age during Give Request.</description>
        <inlineHelpText>Requires member verifies 21+ age during Give Request.</inlineHelpText>
        <label>Must be 21+</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Remaining__c</fullName>
        <label>Num. Remaining</label>
        <summarizedField>Give_Instance__c.Number_Remaining__c</summarizedField>
        <summaryFilterItems>
            <field>Give_Instance__c.Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </summaryFilterItems>
        <summaryForeignKey>Give_Instance__c.Give__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Partnership_Request__c</fullName>
        <label>Partnership</label>
        <referenceTo>Partnership_Request__c</referenceTo>
        <relationshipLabel>Gives</relationshipLabel>
        <relationshipName>Gives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zip_Code_s__c</fullName>
        <inlineHelpText>Multiple Zip Codes should be Separate Gives</inlineHelpText>
        <label>Location by Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Date_From__c</fullName>
        <formula>IF(ISNULL(Start_Date__c),&quot;&quot;,(IF(MONTH(Start_Date__c) == 1,&quot;Jan&quot;, 
(IF(MONTH(Start_Date__c) == 2,&quot;Feb&quot;,
(IF(MONTH(Start_Date__c) == 3,&quot;Mar&quot;,
(IF(MONTH(Start_Date__c) == 4,&quot;Apr&quot;,
(IF(MONTH(Start_Date__c) == 5,&quot;May&quot;,
(IF(MONTH(Start_Date__c) == 6,&quot;Jun&quot;,
(IF(MONTH(Start_Date__c) == 7,&quot;Jul&quot;,
(IF(MONTH(Start_Date__c) == 8,&quot;Aug&quot;,
(IF(MONTH(Start_Date__c) == 9,&quot;Sep&quot;,
(IF(MONTH(Start_Date__c) == 10,&quot;Oct&quot;,
(IF(MONTH(Start_Date__c) == 11,&quot;Nov&quot;,
(IF(MONTH(Start_Date__c) == 12,&quot;Dec&quot;,&quot;&quot;))))))))))))))))))))))) &amp;  &quot; &quot; &amp; TEXT(DAY(Start_Date__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date From</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_To__c</fullName>
        <formula>IF(ISNULL(End_Date__c), &quot;&quot;,(IF(MONTH(End_Date__c) == 1,&quot;Jan&quot;,
(IF(MONTH(End_Date__c) == 2,&quot;Feb&quot;,
(IF(MONTH(End_Date__c) == 3,&quot;Mar&quot;,
(IF(MONTH(End_Date__c) == 4,&quot;Apr&quot;,
(IF(MONTH(End_Date__c) == 5,&quot;May&quot;,
(IF(MONTH(End_Date__c) == 6,&quot;Jun&quot;,
(IF(MONTH(End_Date__c) == 7,&quot;Jul&quot;,
(IF(MONTH(End_Date__c) == 8,&quot;Aug&quot;,
(IF(MONTH(End_Date__c) == 9,&quot;Sep&quot;,
(IF(MONTH(End_Date__c) == 10,&quot;Oct&quot;,
(IF(MONTH(End_Date__c) == 11,&quot;Nov&quot;,
(IF(MONTH(End_Date__c) == 12,&quot;Dec&quot;,&quot;&quot;))))))))))))))))))))))) &amp; &quot; &quot; &amp; TEXT(DAY(End_Date__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>In format (HH:MM XX) where XX is AM or PM in upper case. (e.g. 11:30 AM)</description>
        <inlineHelpText>In format (HH:MM XX) where XX is AM or PM in upper case. (e.g. 11:30 AM)</inlineHelpText>
        <label>End Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Give__c</fullName>
        <description>The parent Give object that these dates and times relate to.</description>
        <inlineHelpText>The parent Give object that these dates and times relate to.</inlineHelpText>
        <label>Give</label>
        <referenceTo>Give__c</referenceTo>
        <relationshipLabel>Give Instances</relationshipLabel>
        <relationshipName>Give_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_Remaining__c</fullName>
        <formula>Number_of_Units__c  -  Number_of_Confirmed_Units__c -  Number_of_Tentative_Confirmed_Units__c -  Number_of_Waitlist_Units__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Num. Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>In format (HH:MM XX) where XX is AM or PM in upper case. (e.g. 11:30 AM)</description>
        <inlineHelpText>In format (HH:MM XX) where XX is AM or PM in upper case. (e.g. 11:30 AM)</inlineHelpText>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_End_Date__c</fullName>
        <formula>TEXT(YEAR(End_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year (End Date)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Start_Date__c</fullName>
        <formula>TEXT(YEAR(Start_Date__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year (Start Date)</label>
        <type>Text</type>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Public_Description__c</fullName>
        <inlineHelpText>For related Gives, this description will appear on the Rucksack site wherever a short description of the partner is needed.</inlineHelpText>
        <label>Public Brief Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/dc_CustomGive.cls
public with sharing class dc_CustomGive {

        public Id giveid {get; set;}
        public string title {get; set;}
        public string description {get; set;}
        public string available {get; set;}
        public string gwhen {get; set;}
        public string gwhere {get; set;}
        public string quantity {get; set;}
        public string deadline {get; set;}
        public string agelimit {get; set;}
        public string noofgiveinst {get; set;}
        public string logo {get; set;}
        public string partner {get; set;}
        public string defaultlogo {get; set;}
        public string givetype {get; set;}
        public string partnerid {get; set;}
        public string partnerlogo {get; set;}
        public string instanceId {get;set;}
        public string fulfillmentInstructions {get; set;}
        public string latitude {get; set;}
        public string longitude {get; set;}
        public string instDifferentiator {get; set;}
        
        public dc_customgive(){}
        public dc_customgive(id gId, string t, string descr, string avail, string gw, string gwher, string qty,string dline, string alimit,
          string noofgivein, string lo, string part, string dl, string gt, string p, string plogo, string fulfill, string lat, string lon)      
        {
            
            giveid = gId;
            title = t;
            description =  descr;
            available = avail;
            gwhen = gw;
            gwhere = gwher;
            quantity = qty;
            deadline = dline;
            agelimit =  alimit;
            noofgiveinst = noofgivein;
            logo = lo;
            partner = part;
            defaultlogo = dl;
            givetype = gt;
            partnerid  = p;
            partnerlogo = plogo;
            fulfillmentInstructions = fulfill;
            latitude = lat;
            longitude = lon;
            system.debug('gwhere here+++' + gwhere);
            system.debug('quantity here+++' +quantity );
            system.debug('deadline here+++' +deadline);
            system.debug('agelimit here+++' +agelimit +'-'+noofgivein);

        }

        public List<string> dc_createlist(Give__c give)     
        {
            List<string> listcg = new list<string>();
            
            string gwhen = ' ';
            string noofgiveinst = ' ';
            list<string> date_to = new list<string>();
            list<string> date_from = new list<string>();
            list<string> time_to = new list<string>();
            list<string> time_from = new list<string>();
            
            if(give.Give_Instances__r.size() > 1)
                {
                    //multigive = true;
                    gwhen = 'Multiple Dates & Times | ';
                    if(give.Give_Instances__r[0].date_from__c != null && give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c != null && give.Give_Instances__r[0].date_from__c.contains(' ') && give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c.contains(' ') && give.Give_Instances__r[0].date_from__c.split(' ')[0] == give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c.split(' ')[0]) 
                        gwhen = gwhen + give.Give_Instances__r[0].date_from__c.split(' ')[0] + ' ' + give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c.split(' ')[1];
                    if(give.Give_Instances__r[0].date_from__c != null && give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c != null && give.Give_Instances__r[0].date_from__c.contains(' ') && give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c.contains(' ') && give.Give_Instances__r[0].date_from__c.split(' ')[0] != give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c.split(' ')[0]) 
                        gwhen = gwhen + give.Give_Instances__r[0].date_from__c + ' - ' + give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c;
                    if(give.Give_Instances__r[0].date_from__c != null && give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c == null)    
                        gwhen = gwhen + give.Give_Instances__r[0].date_from__c; 
                    if(give.Give_Instances__r[0].date_from__c == null && give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c != null)    
                        gwhen = gwhen + give.Give_Instances__r[give.Give_Instances__r.size()-1].date_to__c;
                    noofgiveinst = 'true';
                    system.debug('noofgiveinst = true');
                }
                else
                {
                    gwhen = ' ';
                     if(give.Give_Instances__r[0].date_from__c != null && give.Give_Instances__r[0].date_to__c != null && give.Give_Instances__r[0].date_from__c.contains(' ') && give.Give_Instances__r[0].date_to__c.contains(' ') &&  give.Give_Instances__r[0].date_from__c.split(' ')[0] == give.Give_Instances__r[0].date_to__c.split(' ')[0] && give.Give_Instances__r[0].date_from__c != give.Give_Instances__r[0].date_to__c) 
                        gwhen = gwhen + give.Give_Instances__r[0].date_from__c + '-' + give.Give_Instances__r[0].date_to__c.split(' ')[1];

                     if(give.Give_Instances__r[0].date_from__c != null && give.Give_Instances__r[0].date_to__c != null && give.Give_Instances__r[0].date_from__c.contains(' ') && give.Give_Instances__r[0].date_to__c.contains(' ') &&  give.Give_Instances__r[0].date_from__c.split(' ')[0] != give.Give_Instances__r[0].date_to__c.split(' ')[0] && give.Give_Instances__r[0].date_from__c != give.Give_Instances__r[0].date_to__c) 
                        gwhen = gwhen + give.Give_Instances__r[0].date_from__c + ' - ' + give.Give_Instances__r[0].date_to__c;
            
                    if(give.Give_Instances__r[0].date_from__c != null && give.Give_Instances__r[0].date_to__c != null && give.Give_Instances__r[0].date_from__c == give.Give_Instances__r[0].date_to__c) 
                        gwhen = gwhen + give.Give_Instances__r[0].date_from__c + ', ' + give.Give_Instances__r[0].Year_Start_Date__c; 
                //  if(give.Give_Instances__r[0].date_from__c != null && give.Give_Instances__r[0].date_to__c != null && give.Give_Instances__r[0].date_from__c.split(' ')[0] != give.Give_Instances__r[0].date_to__c.split(' ')[0]) 
                //      gwhen = gwhen + give.Give_Instances__r[0].date_from__c + ' - ' + give.Give_Instances__r[0].date_to__c + ', ' + give.Give_Instances__r[0].Year_Start_Date__c;
                    if(give.Give_Instances__r[0].date_from__c != null && give.Give_Instances__r[0].date_to__c == null)  
                        gwhen = gwhen + give.Give_Instances__r[0].date_from__c + ', ' + give.Give_Instances__r[0].Year_Start_Date__c; 
                    if(give.Give_Instances__r[0].date_from__c == null && give.Give_Instances__r[0].date_to__c != null)  
                        gwhen = gwhen + give.Give_Instances__r[0].date_to__c  + ', ' + give.Give_Instances__r[0].Year_End_Date__c;
                    if(give.Give_Instances__r[0].start_time__c != null || give.Give_Instances__r[0].end_time__c != null)
                        gwhen = gwhen + ' - ';
                    if(give.Give_Instances__r[0].start_time__c != null) 
                        gwhen = gwhen + give.Give_Instances__r[0].start_time__c;
                    if(give.Give_Instances__r[0].start_time__c != null && give.Give_Instances__r[0].end_time__c != null)
                        gwhen = gwhen + ' - ';
                    if(give.Give_Instances__r[0].end_time__c != null    )
                        gwhen = gwhen + give.Give_Instances__r[0].end_time__c;
                        noofgiveinst = 'false';
                }
                
                string gwhere = ' ';
                if(give.Location_Description__c != null)
                    gwhere = give.Location_Description__c;
                else if(give.City__c != null)
                    gwhere = give.City__c;
                else if(give.Location_Formula__c == 'National')
                    gwhere = 'National';
                else if(give.Location_Description__c != null)
                    gwhere = give.Location_Description__c;
                else if(give.City__c != null && give.Location_by_State_s__c != null)
                    gwhere = give.City__c + ', ' + give.Location_by_State_s__c;
                else if(give.City__c != null && give.Location_by_State_s__c == null) 
                    gwhere = give.City__c + ', ' + give.Zip_Code_s__c;
                else if(give.City__c == null && give.Location_by_State_s__c != null)
                    gwhere = give.Location_by_State_s__c;
                else if(give.City__c == null && give.Location_by_State_s__c == null)
                    gwhere = give.Zip_Code_s__c;    
                else gwhere = give.Location_Formula__c;
                string quantity = ' ';
                // MD: commented out 6/10 
                /*
                if(give.Number_Remaining__c != null && give.Number_Remaining__c != 0)
                    quantity = give.Number_Remaining__c + ' total' ;
                if(give.Number_Remaining__c != null && give.Number_Remaining__c != 0 && give.Maximum_Units_per_Member__c != null && give.Maximum_Units_per_Member__c != 0)
                    quantity = quantity + '| ';     
                */              
                if(give.Maximum_Units_per_Member__c != null && give.Maximum_Units_per_Member__c != 0)   
                    quantity = give.Maximum_Units_per_Member__c.intValue() + ' per person';
                    // quantity = quantity + give.Maximum_Units_per_Member__c + ' per veteran';
                if(give.Maximum_Units_per_Member__c == null)
                    quantity = 'Unlimited';
                string deadline = ' ';
                if(give.Latest_Application_Deadline__c != null)
                deadline = give.Deadline__c;
                else deadline = 'N/A';
                
                string agelimit = ' ';
                if(give.Must_be_21__c == true)
                agelimit = 'Age 21+';
                          
                
                system.debug(give.name + '::::noofgiveinst::' + noofgiveinst);
                string logo = ' ';

                if(give.Attachments.size() > 0)
                {
                    //logo = '/servlet/servlet.FileDownload?file=' + give.Attachments[0].id;

                    List<String> imageIds = cov_utilities.parseImagesFromAttachments(give.Attachments);
                    if (!String.isEmpty(imageIds[0])) {
                        //hasPicFull = true;
                        //picFullId = imageIds[0];
                        logo = 'servlet/servlet.FileDownload?file=' + imageIds[0];
                    }
                    //} else {
                    //    hasPicFull = false;
                    //}
                    //if (!String.isEmpty(imageIds[1])) {
                    //    hasPicThumb = true;
                    //    picThumbId = imageIds[1];
                    //    picThumb = 'servlet/servlet.FileDownload?file=' + imageIds[1];
                    //} else {
                    //    hasPicThumb = false;
                    //}


                }
                
                string partner = ' ';
                partner = give.Partnership_Request__r.Public_Partner_Name__c;   
                string defaultlogo  = give.Category__c + '.jpg';    
                
                Attachment FP_at = new Attachment();
                string strFP = ' ';
                /**for(Partnership_Request__c FP:[Select Id, Public_Description__c,(select id From Attachments where Name like '%logo%' limit 1) from Partnership_Request__c where id = :give.Partnership_Request__c limit 1])
                                {
                                    
                                    if(FP.Attachments.size() > 0){
                                    for(integer i=0;i<FP.Attachments.size();i++)
                                    {   
                                        FP_at = FP.Attachments.get(i);
                                        system.debug('at::::::::::::::' + FP_at);
                                        system.debug('at::id::::::::::::' + FP_at.id);
                                        strFP = '/servlet/servlet.FileDownload?file=' + FP_at.id;
                                    }}
                                }**/
                string partnerid = ' ';
                partnerid = give.Partnership_Request__c;

                string latString = give.Latitude__c == null ? ' ' : String.valueof(give.Latitude__c);
                string lonString = give.Longitude__c == null ? ' ' : String.valueof(give.Longitude__c);


            if(give.name != null)
                listcg.add(give.name);
                    else listcg.add(' ');
            if(give.description__c != null)
                listcg.add(give.description__c);
                    else listcg.add(' ');
            if(give.available__c != null)
                listcg.add(give.available__c);
                    else listcg.add(' ');
            listcg.add(gwhen);
            listcg.add(gwhere);
            listcg.add(quantity);
            listcg.add(deadline);
            listcg.add(agelimit);
            listcg.add(noofgiveinst);
            listcg.add(logo);
            listcg.add(partner);
            listcg.add(defaultlogo);
            if(give.type__c != null)
                listcg.add(give.type__c);
                    else listcg.add(' ');
            listcg.add(partnerid);
            listcg.add(strFP);
            listcg.add(give.Fulfillment_Instructions_for_Winner__c);
            listcg.add(latString);
            listcg.add(lonString);
            return listcg;
        }   
        
        public List<string> dc_createinstlist(Give_Instance__c giveinst)        
        {
            List<string> listcgi = new list<string>();
            
            string inst_avail = ' ';
            string inst_when = ' ';
            string inst_differentiator = ' ';
            if(giveinst.Status__c == 'Closed'){
                inst_avail = 'Closed';
            } else if(giveinst.Status__c == 'Waitlist'){
                inst_avail = 'Waitlist';
            } else if(giveinst.Number_Remaining__c >= 25){
                inst_avail = '25+ Available';
            } else if(giveinst.Number_Remaining__c > 0){
                inst_avail = giveinst.Number_Remaining__c.intValue() +  ' Available';
            } else inst_avail = 'Closed';
            
            /*
            if(giveinst.Number_Remaining__c > 0)
                inst_avail = giveinst.Number_Remaining__c +  ' LEFT';
            else inst_avail = 'Closed';
            */
                    
            string gwhen = ' ';
            
             if(giveinst.date_from__c != null && giveinst.date_to__c != null &&  giveinst.date_from__c.contains(' ') && giveinst.date_to__c.contains(' ') && giveinst.date_from__c.split(' ')[0] == giveinst.date_to__c.split(' ')[0] && giveinst.date_from__c != giveinst.date_to__c) 
                gwhen = gwhen + giveinst.date_from__c + ' - ' + giveinst.date_to__c  + ', ' + giveinst.Year_Start_Date__c;
            
             if(giveinst.date_from__c != null && giveinst.date_to__c != null &&  giveinst.date_from__c == giveinst.date_to__c) 
                gwhen = gwhen + giveinst.date_from__c + ', ' + giveinst.Year_Start_Date__c; 
            
            
            system.debug('gwhen........2....................................' + gwhen);
            //else if(giveinst.date_from__c != null && giveinst.date_to__c != null && giveinst.date_from__c.split(',')[0] != giveinst.date_to__c.split(',')[0]) 
            //  gwhen = gwhen + giveinst.date_from__c + ' - ' + giveinst.date_to__c;
            
            system.debug('gwhen.........3...................................' + gwhen);
            if(giveinst.date_from__c != null && giveinst.date_to__c == null)    
                gwhen = gwhen + giveinst.date_from__c  + ', ' + giveinst.Year_Start_Date__c; 
            
            system.debug('gwhen.........4...................................' + gwhen);
            if(giveinst.date_from__c == null && giveinst.date_to__c != null)    
                gwhen = gwhen + giveinst.date_to__c + ', ' + giveinst.Year_End_Date__c;
            
            system.debug('gwhen............5................................' + gwhen);
            if((giveinst.date_from__c != null && giveinst.date_to__c != null && giveinst.date_from__c == giveinst.date_to__c) || giveinst.date_to__c == null || giveinst.date_from__c == null)
            {
                if(giveinst.start_time__c != null || giveinst.end_time__c != null)
                    gwhen = gwhen + ' | ';
            
                system.debug('gwhen............6................................' + gwhen);
                if(giveinst.start_time__c != null) 
                    gwhen = gwhen + giveinst.start_time__c;
            
                system.debug('gwhen..............7..............................' + gwhen);
                if(giveinst.end_time__c != null)
                    gwhen = gwhen + '-';
            
                system.debug('gwhen...............8.............................' + gwhen);
                if(giveinst.end_time__c != null )
                    gwhen = gwhen + giveinst.end_time__c;   
           
                system.debug('gwhen................9............................' + gwhen);
            }

            inst_differentiator = giveinst.Differentiator__c == null ? ' ' : giveinst.Differentiator__c;


            listcgi.add(' ');//title
            listcgi.add(' ');//desc
            listcgi.add(inst_avail);//avail
            listcgi.add(gwhen);//when
            listcgi.add(' ');//where
            listcgi.add(' '); //qty
            listcgi.add(' ');//deadline
            listcgi.add(' ');//agelimit
            listcgi.add(' ');//noofgiveinst
            listcgi.add(' ');//logo
            listcgi.add(' ');//partner
            listcgi.add(' ');//default logo
            listcgi.add(' ');//give type
            listcgi.add(' ');//partner id
            listcgi.add(' ');//partner logo
            listcgi.add(giveinst.id); // instance id
            listcgi.add(inst_differentiator); // instance differentiator
            return listcgi;
        }
    }