prodMetadata/src/objects/Give__c.object
<CustomObject>
    <description>Stores details of a specific giveaway opportunity (experience or reward), like tickets to baseball game.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Giveaways</fullName>
                </value>
                <value>
                    <fullName>Discounts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City_Formula__c</fullName>
        <description>Tries to pull city name from the City, ST field. Fields are not separated because State functionality is based on multi-select picklist Location by State.</description>
        <formula>left(City__c,find(&quot;,&quot;,City__c)-1)</formula>
        <inlineHelpText>Tries to pull city name from the City, ST field (takes everything until the first comma).</inlineHelpText>
        <label>City Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date__c</fullName>
        <label>Earliest Start Date</label>
        <summarizedField>Give_Instance__c.Start_Date__c</summarizedField>
        <summaryForeignKey>Give_Instance__c.Give__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Latest_End_Date__c</fullName>
        <label>Latest End Date</label>
        <summarizedField>Give_Instance__c.End_Date__c</summarizedField>
        <summaryForeignKey>Give_Instance__c.Give__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Latest_Start_Date__c</fullName>
        <label>Latest Start Date</label>
        <summarizedField>Give_Instance__c.Start_Date__c</summarizedField>
        <summaryForeignKey>Give_Instance__c.Give__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location_Description__c</fullName>
        <description>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</description>
        <inlineHelpText>E.g. “22nd &amp; Main”
E.g. “Madison Square Garden”
E.g. “Tres Agaves Restaurant, back patio”</inlineHelpText>
        <label>Location or Venue</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Location_Street_Address__c</fullName>
        <description>Street address of the venue (so it can be mapped).</description>
        <inlineHelpText>Street address of the venue (so it can be mapped).</inlineHelpText>
        <label>Location Street Address</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
                <value>
                    <fullName>Closed Visible</fullName>
                </value>
                <value>
                    <fullName>Closed Invisible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>MLB</fullName>
                </value>
                <value>
                    <fullName>NBA</fullName>
                </value>
                <value>
                    <fullName>NFL</fullName>
                </value>
                <value>
                    <fullName>NHL</fullName>
                </value>
                <value>
                    <fullName>NASCAR</fullName>
                </value>
                <value>
                    <fullName>PGA</fullName>
                </value>
                <value>
                    <fullName>Other Sports</fullName>
                </value>
                <value>
                    <fullName>Movie</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Excursions</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Come First Served</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Screened Give</fullName>
                </value>
                <value>
                    <fullName>Unlimited Give</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</description>
        <inlineHelpText>This field will be used to indicate the states in which a Contact resides that this notification will be sent to.</inlineHelpText>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Give</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/IAVAEvent__c.object
<CustomObject>
    <fields>
        <fullName>Do_not_show_in_public_event_marker_feed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this event will not show up on the map of event markers</description>
        <inlineHelpText>If checked, this event will not show up on the map of event markers</inlineHelpText>
        <label>Do not show in public event marker feed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Relative_URL__c</fullName>
        <description>Relative URL for main event page (used so code can pull from a single source and when URL algorithm changes, can just change it in this formula)</description>
        <formula>&apos;cov_event?id=&apos; + Id</formula>
        <inlineHelpText>Relative URL for main event page (used so code can pull from a single source and when URL algorithm changes, can just change it in this formula)</inlineHelpText>
        <label>Event Relative URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location_City__c</fullName>
        <label>Location City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Street_Address__c</fullName>
        <label>Location Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Venue__c</fullName>
        <label>Location Venue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Zip_Code__c</fullName>
        <inlineHelpText>Required if you want event to be located in geographic/zip searches.</inlineHelpText>
        <label>Location Zip Code (important)</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unpublished</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Flagged/Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Thumbnail_image_URL__c</fullName>
        <description>When the user uploads a new photo to a published group, the URL of the thumbnail version is inserted here and takes precedence over any attached thumbnail images.</description>
        <inlineHelpText>When the user uploads a new photo to a published group, the URL of the thumbnail version is inserted here and takes precedence over any attached thumbnail images. For an external site use a secure HTTPS link to prevent a secure site certificate error.</inlineHelpText>
        <label>Thumbnail image URL (automatic) - HTTPS</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Awareness Action</fullName>
                </value>
                <value>
                    <fullName>Bar Gathering</fullName>
                </value>
                <value>
                    <fullName>Career Development</fullName>
                </value>
                <value>
                    <fullName>Concert</fullName>
                </value>
                <value>
                    <fullName>Cookout</fullName>
                </value>
                <value>
                    <fullName>DPAA Burial</fullName>
                </value>
                <value>
                    <fullName>Fundraiser</fullName>
                </value>
                <value>
                    <fullName>Internal IAVA Training</fullName>
                </value>
                <value>
                    <fullName>Movie Screening</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outdoor Activity</fullName>
                </value>
                <value>
                    <fullName>Parade</fullName>
                </value>
                <value>
                    <fullName>Run</fullName>
                </value>
                <value>
                    <fullName>Seminar/Education</fullName>
                </value>
                <value>
                    <fullName>Service Project</fullName>
                </value>
                <value>
                    <fullName>Social</fullName>
                </value>
                <value>
                    <fullName>Sporting Event</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>VetTogether</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isIAVAEndorsed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IAVA Endorsed Event</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prodMetadata/src/classes/cov_event_marker_feed_controller.cls
public without sharing class cov_event_marker_feed_controller {

	Public List<marker> markers {get; set;}

	public cov_event_marker_feed_controller() {
		markers = new List<marker>();
		loadEvents();
	}


	public class marker implements Comparable {
		public Id recordId {get; set;}
		public String Name {get; set;}
		public String theDate {get; set;}
		public String link {get; set;}
		public String type {get; set;}
        // lines 17-18 added 2016-10-27 by SP for IAVA Endorsed Event flags
        public Boolean isEndorsed {get; set;}
		//public Boolean hasImage {get; set;}
		public String imageURL {get; set;}
		public String venue {get; set;}
		public String street {get; set;}
		public String city {get; set;}
		public String postalcode {get; set;}
		public Double lat {get; set;}
		public Double lon {get; set;}


		public marker(IAVAEvent__c evnt) {
			recordId = evnt.Id;
			Name = evnt.Name;
			theDate = evnt.Event_Date__c == null ? null : evnt.Event_Date__c.format();
			type = evnt.Type__c;
            // lines 34-35 added 2016-10-27 by SP for IAVA Endorsed Event flags
            isEndorsed = evnt.isIAVAEndorsed__c;
			venue = evnt.Location_Venue__c;
			street = evnt.Location_Street_Address__c;
			city = evnt.Location_City__c;
			postalcode = evnt.Location_Zip_Code__c;
			lat = evnt.Latitude__c;
			lon = evnt.Longitude__c;
			link = Site.getBaseUrl() + '/' + evnt.Event_Relative_URL__c;
			imageURL = evnt.Thumbnail_image_URL__c;

			//hasImage = false;
			//String fullImageId;

			//system.debug('evnt.Attachments: ' + evnt.Attachments);
			//while (i < evnt.Attachments.size() && !hasImage) {
			//	if (!hasImage && evnt.Attachments[i].Name == 'image-thumb') {
			//		system.debug('we have a thumbnail');
			//		imageURL = 'servlet/servlet.FileDownload?file=' + evnt.Attachments[i].Id;
			//		hasImage = true;
			//	} else if (!hasImage && fullImageId == null && evnt.Attachments[i].Name == 'image-full') {
			//		system.debug('full image');
			//		fullImageId = evnt.Attachments[i].Id;
			//	}
			//}
			//if (!hasImage && fullImageId == null) {
			//	imageURL = 'servlet/servlet.FileDownload?file=' + fullImageId;
			//	hasImage = true;
			//}
		}

		public marker(Give__c g) {
			recordId = g.Id;
			Name = g.Name;
			theDate = null;
			if (g.Earliest_Start_Date__c != null) {
				if (g.Earliest_Start_Date__c < System.today() && g.Latest_End_Date__c > System.today()) {
					// this might be strange if today is in between start/end dates of different instances, but close enough for now
					theDate = System.today().format();
				} else {
					theDate = g.Earliest_Start_Date__c.format();
				}
			}

			type = g.Subcategory__c != null ? g.Subcategory__c : g.Category__c;
			venue = g.Location_Description__c;
			street = g.Location_Street_Address__c;
			city = g.City_Formula__c;
			postalcode = g.Zip_Code__c;
			lat = g.Latitude__c;
			lon = g.Longitude__c;
			//link = Site.getBaseUrl() + '/' + g.Event_Relative_URL__c;
			link = 'https://my.iava.org/cov_reward?giveid=' + g.Id;
			imageURL = g.Attachments.size() == 0 ? null : 'http://my.iava.org/servlet/servlet.FileDownload?file=' + g.Attachments[0].Id;
		}

		public Integer compareTo(Object compareTo) {
			marker compareToMarker = (marker)compareTo;
	        if (theDate == compareToMarker.theDate) return 0;
	        if (theDate > compareToMarker.theDate) return 1;
	        return -1;  
		}

	}


	public void loadEvents() {

		String startdateString = ApexPages.CurrentPage().getParameters().get('startdate');
		String enddateString = ApexPages.CurrentPage().getParameters().get('enddate');

		Date startdate;
		if (startdateString != null && startdateString != '') {
			try {
				startdate = Date.valueOf(startdateString);
			} catch (Exception e) {
				system.debug('startdate parameter was invalid: ' + startdateString);
			}
		}
		startdateString = startdate == null ? String.valueOf(Date.today()) : startdateString;

		Date enddate;
		if (enddateString != null && enddateString != '') {
			try {
				enddate = Date.valueOf(enddateString);
			} catch (Exception e) {
				system.debug('enddate parameter was invalid: ' + enddateString);
			}
		}
		enddateString = enddate == null ? String.valueOf(Date.today().addDays(31)) : enddateString;


		String theQuery = 'select Id' 
						+ ', Name, Location_Venue__c, Location_Street_Address__c, Location_City__c, Location_Zip_Code__c'
						+ ', Event_Date__c, Type__c'
                        // lines 129-130 added 2016-10-27 by SP for IAVA Endorsed Event flags
            			+ ', isIAVAEndorsed__c'
						+ ', Latitude__c, Longitude__c'
						+ ', Thumbnail_image_URL__c'
						+ ', Event_Relative_URL__c'
						+ ', (select Id, Name from Attachments where name like \'%image%\' order by CreatedDate DESC)'
						+ ' from IAVAEvent__c'
						+ ' where Status__c = \'Published\''
						+ ' and Do_not_show_in_public_event_marker_feed__c = false'
						;

		theQuery += ' and Event_Date__c >= ' + startdateString
				+ ' and Event_Date__c <= ' + enddateString;

		system.debug('theQuery: ' + theQuery);

		List<IAVAEvent__c> theEvents = Database.query(theQuery);

		for (IAVAEvent__c ev : theEvents) {
			markers.add(new marker(ev));
		}


		String giveQuery = 'select Id' 
						+ ', Name, Earliest_Start_Date__c, Latest_End_Date__c, Category__c, Subcategory__c'
						+ ', Location_Description__c, Location_Street_Address__c, City_Formula__c, Zip_Code__c'
						+ ', Type__c'
						+ ', Latitude__c, Longitude__c'
						+ ', (select Id, Name from Attachments where name like \'%logo%\' order by CreatedDate DESC)'
						+ ' from Give__c'
						+ ' where (Status__c = \'Open\' or Status__c = \'Waitlist\')'
						//+ ' and Do_not_show_in_public_event_marker_feed__c = false'
						;

		giveQuery += ' and ('
				+ '(Earliest_Start_Date__c >= ' + startdateString
				+ ' and Earliest_Start_Date__c <= ' + enddateString + ')'
				+ ' or (Latest_Start_Date__c >= ' + startdateString
				+ ' and Latest_Start_Date__c <= ' + enddateString + ')'
				+ ' or (Latest_End_Date__c >= ' + startdateString
				+ ' and Latest_End_Date__c <= ' + enddateString + ')'
				+ ')';

		system.debug('giveQuery: ' + giveQuery);

		List<Give__c> theGives = Database.query(giveQuery);

		system.debug('theGives: ' + theGives);

		for (Give__c gv : theGives) {
			markers.add(new marker(gv));
		}

		markers.sort();


	}
}