prodMetadata/src/objects/Give_Instance__c.object
<CustomObject>
    <description>This is a sub-object of the Give object containing the Date, Date Range and Time for a given Give.</description>
    <fields>
        <fullName>Give_Name__c</fullName>
        <formula>Give__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Give Name</label>
        <type>Text</type>
    </fields>
    <label>Give Instance</label>
    <nameField>
        <displayFormat>GI-{000}</displayFormat>
        <label>Give Instance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Request__c.object
<CustomObject>
    <description>Connects applicants to give</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Street Address</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <description>Should be a confirmed member veteran only.</description>
        <inlineHelpText>Should be a confirmed member veteran only.</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Availability__c</fullName>
        <description>Checks Tentative Number Remaining on Give Instance to see if quantity requested is available.</description>
        <formula>IF(  Give_Instance__r.Tentative_Number_Remaining__c - Units_Requested__c  &gt;= 0,&quot;Available&quot;,&quot;Unavailable&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Checks Tentative Number Remaining on Give Instance to see if quantity requested is available.</inlineHelpText>
        <label>Availability</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirmed_21__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the applicant confirmed age 21+ (only relevant on 21+ gives)</description>
        <inlineHelpText>Checked if the applicant confirmed age 21+ (only relevant on 21+ gives)</inlineHelpText>
        <label>Confirmed 21+</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_ID_plus_Give_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>A workflow sets this value in order to prevent more than one Give Request with confirmation stage for the same Give and Applicant.</description>
        <inlineHelpText>A workflow sets this value in order to prevent more than one Give Request with confirmation stage for the same Give and Applicant.</inlineHelpText>
        <label>Contact ID plus Give ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Give_Fulfillment_Instructions__c</fullName>
        <formula>Give_Instance__r.Give__r.Fulfillment_Instructions_for_Winner__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Give Fulfillment Instructions</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Give_Instance_Start_Date__c</fullName>
        <formula>Give_Instance__r.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Give Instance Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Give_Instance__c</fullName>
        <label>Give Instance</label>
        <referenceTo>Give_Instance__c</referenceTo>
        <relationshipLabel>Give Requests</relationshipLabel>
        <relationshipName>Give_Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Give_Name__c</fullName>
        <formula>Give_Instance__r.Give__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Give Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make_Address_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Make Address Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Make_Email_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when user requests that their email address become the primary email on the account</description>
        <inlineHelpText>Checked when user requests that their email address become the primary email on the account</inlineHelpText>
        <label>Make Email Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes</description>
        <inlineHelpText>Notes</inlineHelpText>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Num_Confirmed_Give_Requests__c</fullName>
        <formula>Applicant__r.Num_Confirmed_Give_Requests__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Conf Give Reqs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Re_confirm_Status__c</fullName>
        <label>Re-confirm Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Re-confirm sent</fullName>
                </value>
                <value>
                    <fullName>Re-confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Special_Response__c</fullName>
        <description>If Give required special response it is stored here.</description>
        <inlineHelpText>If Give required special response it is stored here.</inlineHelpText>
        <label>Special Response #1 (at request)</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Give requested</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Wait-list</fullName>
                </value>
                <value>
                    <fullName>Tentative confirmation</fullName>
                </value>
                <value>
                    <fullName>Final confirmation</fullName>
                </value>
                <value>
                    <fullName>Information sent</fullName>
                </value>
                <value>
                    <fullName>Info requested of member</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Units_Requested__c</fullName>
        <label>Units Requested</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Give Request</label>
    <nameField>
        <displayFormat>GR-{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Give Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Give Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prodMetadata/src/objects/Give_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for Give Instance and Give Requests UI</description>
    <fields>
        <fullName>Give_Request_Page_Size__c</fullName>
        <description>Page size of Give Requests related list. Must be less than or equal to 1,000 so as not to exceed Visualforce limit.</description>
        <label>Give Request Page Size</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Give Settings</label>
</CustomObject>

prodMetadata/src/classes/dc_ctrl_ext_GiveInstance.cls
public with sharing class dc_ctrl_ext_GiveInstance {


    /***************************************** Properties ******************************************/
    public final Give_Instance__c instance      {get;set;}
    //public ApexPages.Standardcontroller con     {get;set;}
    public String selectedStage                 {get;set;}
    public String selectedStartStage            {get;set;}
    public String selectedEndStage              {get;set;}
	
	public ApexPages.StandardSetController setCon { get; private set; }
	public Boolean isFirstPage { get {return setCon != null && setCon.getPageNumber() == 1;} }
	public Boolean hasNextRequests { get {return setCon != null && setCon.getHasNext();} }
	public Boolean hasPrevRequests { get {return setCon != null && setCon.getHasPrevious();} }
	public Boolean isLastPage { get {return setCon != null && setCon.getPageNumber() == totalPageNum;} }
	public Integer thisPageNum  { get {return (setCon != null && setCon.getResultSize() > 0) ? setCon.getPageNumber() : 0;} } // getPageNumber() returns 1 even for empty page
	public Integer totalPageNum { get {return (setCon != null) ? Math.ceil(Double.valueOf(setCon.getResultSize()) / Double.valueOf(setCon.getPageSize())).intValue() : 0;} }
	
	public String updateMessage { get; private set; }
	
	private static final integer PAGESIZE;
	
	static {
		Give_Settings__c gs = Give_Settings__c.getInstance('IAVA');
        if (gs != null && gs.Give_Request_Page_Size__c != null) {
        	PAGESIZE = gs.Give_Request_Page_Size__c.intValue();
        } else {
        	PAGESIZE = 100;
        }
	}
    
    public List<SelectOption> stageOptions{
        get{
            if(stageOptions==null){
                stageOptions = new List<SelectOption>();
                stageOptions.add(new SelectOption('null','--Select One--'));
                for(Schema.Picklistentry entry : Schema.sObjectType.Give_Request__c.fields.Stage__c.getPicklistValues()){
                    stageOptions.add(new SelectOption(entry.getValue(),entry.getLabel()));
                }
            }
            return stageOptions;
        }
        set;
    }
    
    public List<Give_Request__c> requests {
        get{
            if(instance.id!=null && requests==null){
                requests = [Select g.Zip_Code__c, g.Units_Requested__c, g.State__c, g.Stage__c, g.Special_Response__c, g.Secondary_Phone__c, 
                                g.Primary_Phone__c, g.Notes__c, g.Name, g.Make_Email_Primary__c, g.Make_Address_Primary__c, g.Id, 
                                g.Give_Name__c, g.Give_Instance__c, g.Give_Instance_Start_Date__c, g.Give_Fulfillment_Instructions__c, 
                                g.Email_Address__c, g.Contact_ID_plus_Give_ID__c, g.Confirmed_21__c, g.City__c, g.Availability__c, 
                                g.Applicant__c, g.Address__c, g.CreatedDate, g.Num_Confirmed_Give_Requests__c, g.Re_confirm_Status__c
                            From Give_Request__c g
                            WHERE Give_Instance__c=:instance.id 
                            ORDER BY Stage__c,CreatedDate
                            limit :Limits.getLimitQueryRows()];
				setCon = new ApexPages.StandardSetController(requests);
				setCon.setPageSize(PAGESIZE);
            }
            return requests;
        }
        set;
    }
    
    public List<RequestSelect> requestSelects {
        get{
            if(requestSelects==null && !requests.isEmpty()){
                requestSelects = new List<RequestSelect>();
                for (Give_Request__c gr: (List<Give_Request__c>) setCon.getRecords()) {
                    requestSelects.add(new RequestSelect(gr));
                }
            }
            return requestSelects;
        }
        set;
    }
	
	public PageReference toFirst() {
		updateMessage = null;
		if (setCon == null) return null;
		setCon.first();
		requestSelects = null;
		return null;
	}
	
	public PageReference toPrevious() {
		updateMessage = null;
		if (setCon == null) return null;
		setCon.previous();
		requestSelects = null;
		return null;
	}
	
	public PageReference toNext() {
		updateMessage = null;
		if (setCon == null) return null;
		setCon.next();
		requestSelects = null;
		return null;
	}
	
	public PageReference toLast() {
		updateMessage = null;
		if (setCon == null) return null;
		setCon.last();
		requestSelects = null;
		return null;
	}
    
    /***************************************** Constructors ******************************************/
    public dc_ctrl_ext_GiveInstance(ApexPages.standardController sc) {
        //con = sc;
        instance = (Give_Instance__c)sc.getRecord();
        if (requests != null && requests.isEmpty()) { /* force initialization of requests and setCon for reference in page components */ }
    }
    
    public dc_ctrl_ext_GiveInstance(Give_Instance__c instance){
        this.instance = instance;
    }
    
    /***************************************** Action Methods ******************************************/
    public PageReference updateSelectedStage(){
    	updateMessage = null;
        if(selectedStage!=null && selectedStage!='' && selectedStage!='null' && requestSelects!=null){
            List<Give_Request__c> reqUpdates = new List<Give_Request__c>();
            for(RequestSelect req : requestSelects){
                if(req.checked){
                    req.record.Stage__c=selectedStage;
                    reqUpdates.add(req.record);
                }
            }
            try{
                if(!reqUpdates.isEmpty()) update reqUpdates;
                updateMessage = reqUpdates.size() + ' Give Request ' + (reqUpdates.size() > 1 ? 'records' : 'record') + ' updated.';
            } catch(Exception e){
                System.debug(e);            
                ApexPages.addMessages(e);
            } finally {
                requestSelects=null;
                requests=null;
            }
        }
        return null;
    }
    
    public PageReference massUpdateStage(){
    	updateMessage = null;
        if(selectedStartStage!=null && selectedStartStage!='null' && selectedEndStage!=null && selectedEndStage!='null'){
            // Select first 50k Requests in the StartStage
            for(List<Give_Request__c> reqs : [select id,stage__c from Give_Request__c where give_instance__c=:instance.id and stage__c=:selectedStartStage limit :Limits.getLimitQueryRows()]){
                List<Give_Request__c> updates = new List<Give_Request__c>();
                for(Give_Request__c req : reqs){
                    req.stage__c = selectedEndStage;
                    updates.add(req);
                }
                try{
                    if(!updates.isEmpty()) update updates;
                    updateMessage = updates.size() + ' Give Request ' + (updates.size() > 1 ? 'records' : 'record') + ' updated.';
                } catch(Exception e){
                    System.debug(e);            
                    ApexPages.addMessages(e);
                } finally {
                    requestSelects=null;
                    requests=null;
                }
            }
        }
        return null;
    }
    
    
    /***************************************** Helper/Utility Methods ******************************************/
    
    
    
    /***************************************** Helper Class ******************************************/
    public class RequestSelect{
        public Give_Request__c record {get;set;}
        public Boolean checked {get;set;}
        
        public RequestSelect(Give_Request__c obj){
            record = obj;
            checked = false;
        }
    }
}