prodMetadata/src/objects/IAVA_Rewards_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Last_Member_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>AUTOMATICALLY MAINTAINED.  DO NOT UPDATE.
The Last Member ID assigned to a Contact.  Is 8 character string that looks like a number.  First number assigned to any Contact is 15325001.  Is sequential after that.</inlineHelpText>
        <label>Last Member ID</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IAVA Rewards Settings</label>
    <nameField>
        <label>IAVA Rewards Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IAVA Rewards Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/MemberSettingsController.cls
/*
 * Controller for Member Settings page
 *	1) Easy button that increments the IAVA Rewards Setting object's Last Member ID field
 *
 * WH, Exponent Partners, 2012
 */
public class MemberSettingsController {
	
	public final static String CUSTOM_SETTINGS_NAME = 'Main';
	
	public IAVA_Rewards_Settings__c settings { get; private set; }
	
	public MemberSettingsController() {
		try {
			settings = [select Name, Last_Member_ID__c from IAVA_Rewards_Settings__c where Name =:CUSTOM_SETTINGS_NAME limit 1];
		} catch (Exception e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error retrieving IAVA Rewards Settings.'));
			System.debug('>>>>>>>>>> Error retrieving IAVA Rewards Settings: ' + e.getMessage());
		}
	}
	
	public PageReference incrementMemberId() {
		try {
			settings = [select Name, Last_Member_ID__c from IAVA_Rewards_Settings__c where Name =:CUSTOM_SETTINGS_NAME limit 1];
			settings.Last_Member_ID__c = String.valueOf(Integer.valueOf(settings.Last_Member_ID__c) + 1);
			update settings;
		} catch (Exception e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error incrementing Last Member ID in IAVA Rewards Settings.'));
			System.debug('>>>>>>>>>> Error incrementing Last Member ID in IAVA Rewards Settings: ' + e.getMessage());
		}
		return null;
	}
	
	////////// Tests //////////
	
	static void setupSettings() {
		IAVA_Rewards_Settings__c settings = new IAVA_Rewards_Settings__c(Name = CUSTOM_SETTINGS_NAME, Last_Member_ID__c = '11111');
		insert settings;
	}
	
	static testMethod void testMemberSettingsController() {
		setupSettings();
		MemberSettingsController controller = new MemberSettingsController();
		System.assertNotEquals(null, controller.settings);
	}
	
	static testMethod void testIncrementMemberId() {
		setupSettings();
		MemberSettingsController controller = new MemberSettingsController();
		Integer oldMemberNumber = Integer.valueOf(controller.settings.Last_Member_ID__c);
		controller.incrementMemberId();
		System.assertEquals(oldMemberNumber + 1, Integer.valueOf(controller.settings.Last_Member_ID__c));
	}
	
}