prodMetadata/src/objects/Partnership_Request__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Information__c</fullName>
        <label>Contact Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Partnership End Date.</description>
        <inlineHelpText>Partnership End Date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Featured_Partner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will make this partner appear on the rewards site as the featured partner (only one partnership record should have this checked).</description>
        <inlineHelpText>Will make this partner appear on the rewards site as the featured partner (only one partnership record should have this checked).</inlineHelpText>
        <label>Featured Partner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Total_Gives__c</fullName>
        <description>Number of total related Gives on the partnership record</description>
        <inlineHelpText>Number of total related Gives on the partnership record</inlineHelpText>
        <label>Num. Total Gives</label>
        <summaryForeignKey>Give__c.Partnership_Request__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partnerships</relationshipLabel>
        <relationshipName>Partnership_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partnership_Type__c</fullName>
        <label>Partnership Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Film</fullName>
                </value>
                <value>
                    <fullName>Ticket Give</fullName>
                </value>
                <value>
                    <fullName>Resources &amp; Benefits</fullName>
                </value>
                <value>
                    <fullName>Nonprofit &amp; Government Org</fullName>
                </value>
                <value>
                    <fullName>Corporation &amp; Sponsorship</fullName>
                </value>
                <value>
                    <fullName>PRISM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Public_Description__c</fullName>
        <inlineHelpText>For related Gives, this description will appear on the Rucksack site wherever a short description of the partner is needed.</inlineHelpText>
        <label>Public Brief Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Public_Detail_Description__c</fullName>
        <inlineHelpText>This is the long description that will appear on the Rucksack site when someone drills into this specific partnership record.</inlineHelpText>
        <label>Public Detail Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Public_Partner_Name__c</fullName>
        <description>Name of partner to appear on Rewards site</description>
        <inlineHelpText>Name of partner to appear on Rewards site</inlineHelpText>
        <label>Public Partner Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Partner_Logo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines whether logo appears in partner section of Rucksack website</description>
        <inlineHelpText>Determines whether logo appears in partner section of Rucksack website</inlineHelpText>
        <label>Partner logo on partners page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_partner_logo_on_rewards_homepage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines whether logo shows up in logo block on Rewards site</description>
        <inlineHelpText>Determines whether logo shows up in logo block on Rewards site</inlineHelpText>
        <label>Partner logo in logo block</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted by Partner</fullName>
                </value>
                <value>
                    <fullName>IAVA to Outreach</fullName>
                </value>
                <value>
                    <fullName>Needs Followup</fullName>
                </value>
                <value>
                    <fullName>Closed/Rejected</fullName>
                </value>
                <value>
                    <fullName>Active Partnership</fullName>
                </value>
                <value>
                    <fullName>Inactive/Completed Partnership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Partnership Start Date.</description>
        <inlineHelpText>Partnership Start Date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ticket_Give_Stage__c</fullName>
        <label>Ticket Give Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Partnership_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted by Partner</fullName>
                </value>
                <value>
                    <fullName>Accepted by SP &amp; Sent to Membership</fullName>
                </value>
                <value>
                    <fullName>Accepted by Membership &amp; Sent to Online</fullName>
                </value>
                <value>
                    <fullName>Rejected by Membership</fullName>
                </value>
                <value>
                    <fullName>Form Setup Online</fullName>
                </value>
                <value>
                    <fullName>Offer Sent to Members</fullName>
                </value>
                <value>
                    <fullName>Ticket Winners Confirmed</fullName>
                </value>
                <value>
                    <fullName>Names Sent to Partner</fullName>
                </value>
                <value>
                    <fullName>Partner Followup Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partnership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prodMetadata/src/classes/dc_ctrl_PartnerDetails.cls
public with sharing class dc_ctrl_PartnerDetails 
{
	private Partnership_Request__c partner;
	public string logoURL {get; set;}
	public string Partnerdefaultlogo {get; set;}
	

	public dc_ctrl_PartnerDetails()
	{
		if ( partner == null )
		{
				logoURL = ' ';
				Partnerdefaultlogo = 'Partner.jpg';
			partner = [SELECT id,
				        Contact_Information__c,
				        End_Date__c,
				        Featured_Partner__c,
				        Number_of_Total_Gives__c,
				        Organization__c,
				        Partnership_Type__c,
				        Priority__c,
				        Public_Description__c,
				        Public_Detail_Description__c,
				        Public_Partner_Name__c,
				        Show_Partner_Logo__c,
				        Show_partner_logo_on_rewards_homepage__c,
				        Stage__c,
				        Start_Date__c,
				        Ticket_Give_Stage__c, (select id From Attachments where Name like '%logo%' limit 1)
	        		FROM Partnership_Request__c
	                WHERE id = :ApexPages.currentPage().getParameters().get('id')];
	                
	                if(partner.Attachments.size() > 0)
					{
						Attachment at = new Attachment();
						for(integer i=0;i<partner.Attachments.size();i++)
						{	
							at = partner.Attachments.get(i);
							logoURL = '/servlet/servlet.FileDownload?file=' +  at.id;
						}
					}
		}
			
	}
	

    public Partnership_Request__c getPartner() {
        return partner;
    }	
    
    public void its()
  	{
  		Staticvar.dc_homepage = false;
  		Staticvar.dc_rewardsearch = false;
  		Staticvar.dc_rewarddetail = false;
  		Staticvar.dc_claimreward = false;
  		Staticvar.dc_partner = true;
  		Staticvar.dc_faq = false;
  		Staticvar.title = 'IAVA Rucksack - Partners';

  	}
}